/*
 TeeChart(tm) for JavaScript(tm)
 @fileOverview TeeChart for JavaScript(tm)
 v1.3 October 2012
 Copyright(c) 2012 by Steema Software SL. All Rights Reserved.
 http://www.steema.com

 Licensed with commercial and non-commercial attributes,
 specifically: http://www.steema.com/licensing/html5

 JavaScript is a trademark of Oracle Corporation.
*/
var Tee=Tee||{};
(function(){function q(d,c){this.x=d;this.y=c}function G(d,c,a,b){function e(){var b,f;if(a.x==c.x&&a.y==c.y)b=d.x-c.x,f=d.y-c.y;else{b=a.x-c.x;f=a.y-c.y;var g=((d.x-c.x)*b+(d.y-c.y)*f)/(b*b+f*f);0>g?(b=d.x-c.x,f=d.y-c.y):1<g?(b=d.x-a.x,f=d.y-a.y):(b=d.x-(c.x+g*b),f=d.y-(c.y+g*f))}return Math.sqrt(b*b+f*f)}return d.x==c.x&&d.y==c.y||d.x==a.x&&d.y==a.y?!0:Math.abs(e())<=b+1}function n(d,c,a,b){this.set(d,c,a,b)}function D(){this.left=this.right=this.top=this.bottom=2;this.apply=function(d){var c=d.width,
a=d.height;d.x+=0.01*c*this.left;d.width-=0.01*c*Math.min(100,this.left+this.right);d.y+=0.01*a*this.top;d.height-=0.01*a*Math.min(100,this.top+this.bottom)}}function H(d,c,a){this.format=a;this.bounds=c;var b=this,c=a.shadow;this.old=new y;this.old.set(c);c.visible=!0;c.color="rgba(0,255,0,0.1)";c.blur=10;c.width=0;c.height=0;this.enabled=!0;a=new Tee.Animation(a.chart,function(a){b.enabled&&(1>a?b.format.shadow.color="rgba(0,255,0,"+a.toString()+")":b.autoHide&&b.restore())});a.duration=d;a.animate();
this.restore=function(){this.format.shadow.set(this.old);this.enabled=!1}}function z(d){this.chart=d;this.visible=!1;this.colors=["white","silver"];this.direction="topbottom";this.stops=null;this.offset={x:0,y:0};this.create=function(c,a){return this.rect(c.x,c.y,c.width,c.height,a)};this.rect=function(c,a,b,e,d){var f;f=this.chart.ctx;var g=f.createLinearGradient;"topbottom"==this.direction?f=g.call(f,c,a,c,a+e):"bottomtop"==this.direction?f=g.call(f,c,a+e,c,a):"leftright"==this.direction?f=g.call(f,
c,a,c+b,a):"rightleft"==this.direction?f=g.call(f,c+b,a,c,a):"radial"==this.direction?(c=c+0.5*b+this.offset.x,a=a+0.5*e+this.offset.y,b=Math.max(b,e),f=f.createRadialGradient(c,a,0,c,a,b)):f="diagonalup"==this.direction?g.call(f,c,a+e,c+b,a):g.call(f,c,a,c+b,a+e);d&&this.setEndColor(d);b=this.colors;e=b.length;c=(a=this.stops)?a.length:0;if(1<e)for(d=0;d<e;d++)f.addColorStop(c<=d?d/(e-1):a[d],b[d]);else f.addColorStop(0,0<e?b[0]:"white");return f}}function y(d){this.chart=d;this.visible=!1;this.blur=
4;this.color="rgba(80,80,80,0.75)";this.height=this.width=4;this.prepare=function(c){this.visible?(c.shadowBlur=this.blur,c.shadowColor=this.color,c.shadowOffsetX=this.width,c.shadowOffsetY=this.chart.isAndroid?-this.height:this.height):c.shadowColor="transparent"}}function I(d){this.url="";this.chart=d;this.visible=!0;this.tryDraw=function(c,a,b,e){this.image||(this.image=new Image,this.image.onload=function(){d.draw()});""==this.image.src?(d=this.chart,this.image.src=this.url):d.ctx.drawImage(this.image,
c,a,b,e)}}function A(d){this.chart=d;this.fill="black";this.size=1;this.join="round";this.cap="square";this._g=this.dash=null;Object.defineProperty(this,"gradient",{get:function(){this._g||(this._g=new z(this.chart));return this._g}});this.prepare=function(c,a){var a=a||this.chart.ctx,b=this._g;a.strokeStyle=b&&b.visible?b.create(this.chart.bounds):c?c:this.fill;a.lineWidth=this.size;a.lineJoin=this.join;a.lineCap=this.cap;a.shadowColor="transparent";a.setLineDash?a.setLineDash(this.dash):a.mozCurrentTransform?
a.mozDash=this.dash:this.chart.isChrome&&(a.webkitLineDash=this.dash)};this.setChart=function(c){this.chart=c;this._g&&(this._g.chart=c)}}function x(d){this.chart=d;this.style="11px Tahoma";this._g=null;Object.defineProperty(this,"gradient",{get:function(){this._g||(this._g=new z(this.chart));return this._g}});this.fill="black";this._sh=null;Object.defineProperty(this,"shadow",{get:function(){this._sh||(this._sh=new y(this.chart));return this._sh}});this._s=null;Object.defineProperty(this,"stroke",
{get:function(){this._s||(this._s=new A(this.chart),this._s.fill="");return this._s}});this.textAlign="center";this.baseLine="alphabetic"}function J(d){this.chart=d;this.items=[];this.draw=function(){for(var c=0,a;a=this.items[c++];)a.active&&a.draw()};this.mousemove=function(c){for(var a=0,b;b=this.items[a++];)b.active&&b.mousemove(c)};this.mousedown=function(c){for(var a=0,b,e=!1;b=this.items[a++];)b.active&&b.mousedown(c)&&(e=!0);return e};this.clicked=function(c){for(var a=0,b,e=!1;b=this.items[a++];)b.active&&
b.clicked(c)&&(e=!0,b.onclick&&(e=b.onclick(b,c.x,c.y)));return e};this.add=function(c){this.items.push(c);return c}}function K(d){function c(a){var c=a.chart.chartRect,f=a.direction,g="both"==f;b.set(c.x,c.y,c.width,c.height);if(a.old){if(g||"horizontal"==f)0>a.old.x?(b.x=a.chart.oldPos.x+a.old.x,b.width=-a.old.x):(b.x=a.chart.oldPos.x,b.width=a.old.x);if(g||"vertical"==f)0>a.old.y?(b.y=a.chart.oldPos.y+a.old.y,b.height=-a.old.y):(b.y=a.chart.oldPos.y,b.height=a.old.y)}return b}this.chart=d;this.active=
!1;this.enabled=!0;this.done=!1;this.direction="both";this.mouseButton=0;var a=this.format=new Tee.Format(d);a.fill="rgba(255,255,255,0.5)";a.stroke.fill="darkgray";a.stroke.size=2;var b=new n;this.draw=function(){a.rectangle(c(this))};this.apply=function(){0>this.old.x||0>this.old.y?this.reset():(c(this),this.chart.axes.each(function(){this.horizontal?this.calcMinMax(b.x,b.x+b.width):this.calcMinMax(b.y+b.height,b.y)}))};this.reset=function(){this.chart.axes.each(function(){this.automatic=!0})}}
function L(d){this.chart=d;this.active=!1;this.enabled=!0;this.done=!1;this.mouseButton=2;this.direction="both";this.position=new q(0,0)}function C(d,c){Tee.Annotation.call(this,d);this.transparent=!0;this._expand=!1;Object.defineProperty(this,"expand",{get:function(){return this._expand},set:function(a){this._expand=a;this._expand||(a=this.format,a.round.x=8,a.round.y=8,a.round.corners=null,a.stroke.fill="black")}});var a=this.format.font,b=a.shadow,e=this.position;b.visible=!0;b.width=2;b.height=
2;b.blur=8;a.style="18px Tahoma";a.fill=c;this.padding=4;this.calcRect=function(a){this.resize();var b=this.bounds,g=b.height+(this.transparent?1:2)*this.padding,i=d.chartRect;a?(e.y=i.y,i.setTop(i.y+g)):(e.y=i.y+i.height-b.height-this.padding,i.height-=g);0>i.height&&(i.height=0);e.x=0.5*(d.canvas.width-b.width)};this.tryDraw=function(a){if(this.visible&&this.text&&""!==this.text){this.calcRect(a);var b=this.bounds;if(this._expand){var g=d.panel.format;e.x=""!=g.stroke.fill?g.stroke.size:0;e.y=a?
e.x:d.canvas.height-(g.shadow.visible?g.shadow.height:0)-e.x-b.height;b.width=d.canvas.width-(g.shadow.visible?g.shadow.width:0)-2*e.x;var i=this.format;i.round.x=g.round.x;i.round.y=g.round.y;i.round.corners=[a,a,!a,!a];i.stroke.fill="";this.transparent=!1}b.x=e.x;b.y=e.y;this.doDraw()}}}function M(d){var c=this.format=new Tee.Format(d);c.round.x=12;c.round.y=12;c.stroke.size=3;c.gradient.visible=!0;c.gradient.direction="bottomtop";c.shadow.visible=!0;c.stroke.fill="#606060";this.transparent=!1;
this.margins=new D;this.clear=function(){var a=d.bounds;d.ctx.clearRect(a.x,a.y,a.width,a.height)};this.draw=function(){if(this.transparent)this.clear();else{var a=d.chartRect,b=c.shadow;b.visible&&(a.width-=0.5*Math.abs(b.width)+2,a.height-=0.5*Math.abs(b.height)+2,0>b.width&&(a.x-=b.width),0>b.height&&(a.y-=b.height));var e=0;""!=c.stroke.fill&&(e=c.stroke.size,1<e&&(e*=0.5,a.x+=e,a.y+=e,a.width-=2*e,a.height-=2*e));(b.visible||0<c.round.x||0<c.round.y)&&this.clear();c.rectangle(a);0<e&&(a.x+=e,
a.y+=e,a.width-=2*e,a.height-=2*e)}}}function B(d){this.format=new Tee.Format(d);this.format.fill="#E6E6E6";this.format.stroke.fill="black";this.visible=!0;this.bounds=new n;this.draw=function(){this.format.rectangle(this.bounds)}}function u(d,c,a){function b(a){this.chart=a;this.stroke=new A(a);this.stroke.cap="butt";this.visible=!0;this.length=4}function e(a){Tee.Annotation.call(this,a);this.padding=4;this.transparent=!0;this.format.font.textAlign="center"}function h(a){return isFinite(a)?10<=a?
10*h(0.1*a):1>a?0.1*h(10*a):2>a?2:5>a?5:10:1}this.chart=d;this.visible=!0;this.inverted=!1;this.horizontal=c;this.otherSide=a;this.bounds=new n;this.position=0;this.format=new Tee.Format(d);this.format.stroke.size=2;this.custom=!1;this.labels=new function(a,b){this.chart=a;this.format=new Tee.Format(a);this.decimals=2;this.padding=4;this.separation=10;this.visible=!0;this.rotation=0;this.alternate=!1;this.maxWidth=0;this.labelStyle="auto";this.dateFormat="shortDate";this.checkStyle=function(){var a=
this.labelStyle,g=b.firstSeries;this._text=null;if("auto"==a)0<g.data.labels.length&&g.notmandatory==b&&(this._text=g);else if("mark"==a||"text"==a)this._text=g};this.getLabel=function(a){var g=a|0,c;this._text&&g==a?(c=this._text.data,c.x&&(g=c.x.indexOf(g)),g=c.labels[g]||""):g=b.dateTime&&Date.prototype.format?(new Date(a)).format(this.dateFormat):a.toFixed(g==a?0:this.decimals);this.ongetlabel&&(g=this.ongetlabel(a,g),this.format.font.prepare());return g};this.width=function(a){return this.format.textWidth(this.getLabel(a))}}(d,
this);var f=this.labels.format.font;this.scroll=function(a){this.automatic=!1;this.inverted&&(a=-a);this.minimum+=a;this.maximum+=a};c?(f.textAlign="center",f.baseLine=a?"bottom":"top"):(f.textAlign=a?"left":"right",f.baseLine="middle");this.grid=new function(a){this.chart=a;a=this.format=new Tee.Format(a);a.stroke.fill="silver";a.stroke.cap="butt";a.fill="";this.visible=!0;this.lineDash=!1}(d);this.ticks=new b(d);this.innerTicks=new b(d);this.innerTicks.visible=!1;f=this.minorTicks=new b(d);f.visible=
!1;f.length=2;f.count=3;e.prototype=new Tee.Annotation;this.title=new e(d);this.automatic=!0;this.increment=this.maximum=this.minimum=0;this.log=!1;this.start=this.endPos=this.startPos=0;this.end=100;this.increm=this.scale=this.axisSize=0;this.minmaxLabelWidth=function(){var a=this.labels,b=a._text,c=0,f;if(null!=b)for(var e=0,d=b.data.labels.length;e<d;e++)f=b.data.labels[e],this.ongetlabel&&(f=this.ongetlabel(e,f)),f&&(c=Math.max(c,a.format.textWidth(f)));else c=this.roundMin(),b=this.maximum,c=
Math.max(a.width(c),a.width(0.5*(c+b))),c=Math.max(c,a.width(1E-7)),c=Math.max(c,a.width(b));return c};this.checkMinMax=function(){var a=this.chart.series,b=this.horizontal;this.automatic&&(this.minimum=b?a.minXValue(this):a.minYValue(this),this.maximum=b?a.maxXValue(this):a.maxYValue(this))};this.calcScale=function(){var a=this.labels,b;a.format.font.prepare();b=this.horizontal?this.minmaxLabelWidth():a.format.textHeight("Wj");a.alternate&&(b*=0.5);b+=0.02*b*a.separation;if(0==this.increment)if(this.maximum==
this.minimum)a=1;else{var a=this.axisSize/b,c;b:{c=a;var f,e,d;for(f=0;e=this.chart.series.items[f++];)if(e.visible&&((d=e.yMandatory)&&this.horizontal||!d&&!this.horizontal)&&e.associatedToAxis(this)&&e.count()<=c){c=!0;break b}c=!1}a=Math.abs(this.maximum-this.minimum)/(a+1);a=c?Math.max(1,a):h(a)}else a=this.increment;this.increm=a;0>=this.increm&&(this.increm=0.1);a=this.maximum-this.minimum;0==a?a=1:this.log&&(a=Math.log(a));this.scale=this.axisSize/a;this.calc(this.minimum+this.increm)-this.startPos<
b&&(this.increm*=2)};this.hasAnySeries=function(){var a=this.chart.series.items,b,c;for(b=0;c=a[b++];)if(c.visible&&c.associatedToAxis(this))return a=this.horizontal,c.yMandatory&&(a=!a),this.dateTime=(a=a?c.data.values:c.data.x)&&0<a.length&&a[0]instanceof Date,c;return null};this.drawAxis=function(){var a=this.chart.ctx;a.beginPath();c?(a.moveTo(this.startPos,this.axisPos),a.lineTo(this.endPos,this.axisPos)):(a.moveTo(this.axisPos,this.startPos),a.lineTo(this.axisPos,this.endPos));this.format.stroke.prepare();
a.stroke()};this.drawGrids=function(){var b=this.chart.ctx,f,e=this.chart.chartRect,d=this.grid.format,h,m,v,p,r=this.roundMin();this.grid.centered&&(f=0.5*this.increm,r=r-f>=this.minimum?r-f:r+f);b.beginPath();c?(m=this.bounds.y,p=a?e.getBottom()-1:e.y+1):(h=this.bounds.x,v=a?e.x+1:e.getRight()-1);if(""!=d.fill){var e=r,s=d.stroke.fill;d.stroke.fill="";for(var t,q=-1;e<=this.maximum;)f=this.calc(e),0==q%2&&(c?d.rectangle(t,p,f-t,m-p):d.rectangle(h,t,v-h,f-t)),t=f,e+=this.increm,q++;d.stroke.fill=
s;b.fillStyle=""}for(e=r;e<=this.maximum;){c?h=v=this.calc(e):m=p=this.calc(e);if(d.stroke.dash&&!b.setLineDash&&!b.mozCurrentTransform){r=b;t=h;var q=m,n=v,s=p;f=void 0;f=[10,5];r.save();var n=n-t,w=s-q,s=Math.sqrt(n*n+w*w),n=Math.atan2(w,n);r.translate(t,q);r.moveTo(0,0);r.rotate(n);q=f.length;n=0;w=!0;for(t=0;s>t;)t+=f[n++%q],t>s&&(t=s),w?r.lineTo(t,0):r.moveTo(t,0),w=!w;r.restore()}else b.moveTo(h,m),b.lineTo(v,p);e+=this.increm}d.stroke.prepare();d.shadow.prepare(b);b.stroke()};this.roundMin=
function(){var a=this.minimum/this.increm|0;return this.increm*(0>=this.minimum?a:1+a)};this.drawTicks=function(b,f,e){var d=this.roundMin(),h=1+b.length,m=1;if(c&&a||!c&&!a)h=-h,m=-1;var h=h*f+this.axisPos,m=m*f+this.axisPos,q,p=1,r=0;0==e?q=this.increm:(p+=e,q=this.increm/p);var s=this.chart.ctx;for(s.beginPath();d<=this.maximum;){if(0==e||0!=r++%p)f=this.calc(d),c?(s.moveTo(f,m),s.lineTo(f,h)):(s.moveTo(m,f),s.lineTo(h,f));d+=q}b.stroke.prepare();s.stroke()};this.drawTitle=function(){var a=this.labels,
b,f;""!=this.title.text&&(c?(f=this.axisPos+this.title.padding,this.ticks.visible&&(f+=this.ticks.length),a.visible&&(a.format.font.prepare(),b=a.format.textHeight("Wj"),a.alternate&&(b*=2),f+=b),b=this.startPos+0.5*this.axisSize-0.5*this.title.bounds.width,this.title.position.x=b,this.title.position.y=f,this.title.forceDraw()):(b=this.axisPos-this.title.bounds.height-this.title.padding,this.ticks.visible&&(b-=this.ticks.length),a.visible&&(f=a.maxWidth,a.alternate&&(f*=2),b-=f),f=this.startPos+0.5*
this.axisSize+this.title.bounds.height,a=this.chart.ctx,a.save(),a.translate(b,f),a.rotate(-Math.PI/2),a.textAlign="center",this.title.position.x=0,this.title.position.y=0,this.title.forceDraw(),a.restore()))};this.drawLabel=function(a,b){var f=this.labels,c=f.getLabel(a);b.width=f.format.textWidth(c);b.width>f.maxWidth&&(f.maxWidth=b.width);this.horizontal?b.x-=0.5*b.width:b.y+=0.5*b.height;if(0!=f.rotation){var e=this.chart.ctx;e.save();e.translate(b.x,b.y);e.rotate(-Math.PI*f.rotation/180);e.textAlign=
"right";b.x=-8;b.y=3}"right"==f.format.font.textAlign&&(b.x-=b.width);f.format.drawText(b,c);0!=f.rotation&&this.chart.ctx.restore()};this.drawLabels=function(){var a=this.roundMin(),b=new n,f=this.axisPos,c=this.labels;c.maxWidth=0;c.format.font.prepare();var e=this.ticks.visible?this.ticks.length:0,e=e+c.padding;this.horizontal?this.otherSide?f-=e:f+=e:this.otherSide?f+=e:f-=e;e=f;b.height=c.format.textHeight("Wj");for(var d=(c=c.alternate)?this.minmaxLabelWidth():0,h;a<=this.maximum;)h=this.calc(a),
this.horizontal?(b.x=h,b.y=f,c&&(f=f==e?this.otherSide?e-b.height:e+b.height:e)):(b.x=f,b.y=h-0.5*b.height,c&&(f=f==e?this.otherSide?e+d:e-d:e)),this.drawLabel(a,b),a+=this.increm};this.calc=function(a){a!==a?a=0:this.log?(a-=this.minimum,a=0>=a?0:Math.log(a)*this.scale):a=(a-this.minimum)*this.scale;return this.horizontal?this.inverted?this.endPos-a:this.startPos+a:this.inverted?this.startPos+a:this.endPos-a};this.fromPos=function(a){var b=this.horizontal;this.inverted&&(b=!b);return this.minimum+
(b?a-this.startPos:this.endPos-a)/this.scale};this.fromSize=function(a){return a/this.scale};this.calcSize=function(a){return Math.abs(this.calc(a)-this.calc(0))};this.calcMinMax=function(a,b){this.automatic=!1;var f=this.fromPos(a),c=this.fromPos(b),e;f>c&&(e=f,f=c,c=e);this.minimum=f;this.maximum=c};this.setMinMax=function(a,b){this.automatic=!1;this.minimum=a;this.maximum=b}}function N(d){this.chart=d;this.transparent=!1;var c=this.format=new Tee.Format(d);c.fill="white";c.round.x=8;c.round.y=
8;c.font.baseLine="top";c.shadow.visible=!0;this.title=new Tee.Annotation(d);this.title.transparent=!0;this.bounds=new n;this.position="right";this.visible=!0;this.inverted=!1;this.padding=5;this.align=0;this.fontColor=!1;var a=this.dividing=new A(d);a.fill="";a.cap="butt";this.over=-1;this.symbol=new function(a){this.chart=a;var b=this.format=new Tee.Format(a);b.shadow.visible=!0;b.shadow.color="silver";this.padding=this.height=this.width=8;this.visible=!0;this.draw=function(c,e,d,h){var m=a.ctx;
if(c.isColorEach&&-1!=e){c.format.stroke.prepare();var q=m.fillStyle;b.fill=c.getFill(e);b.rectangle(d,h-0.5*this.height,this.width,this.height);c.hover.enabled&&c.over==e&&c.hover.rectangle(d,h-0.5*this.height,this.width,this.height);m.fillStyle=q}else if(m.beginPath(),m.moveTo(d,h),m.lineTo(d+this.width,h),b.stroke.prepare(c.format.fill),m.stroke(),c.hover.enabled&&((d=this.chart.legend.showValues())&&c.over==e||!d&&0<=c.over))c.hover.stroke.prepare(),m.stroke()}}(d);this.itemHeight=10;this.innerOff=
0;this.textStyle=this.legendStyle="auto";this.totalWidth=function(){var a=this.itemWidth+8,b=this.symbol;b.visible&&(a+=b.width+b.padding);return a};this.availRows=function(){var a=this.bounds.y;a||(a=0);return(d.chartRect.getBottom()-a)/this.itemHeight|0};this.itemsCount=function(){var a=d.series,b=a.visibleCount(),c=d.chartRect;if(0==b)return 0;"values"==this.legendStyle&&0<b?b=a.firstVisible().count():"auto"==this.legendStyle&&1<b||"series"==this.legendStyle||1==b&&(b=a.firstVisible().count());
if(this.isVertical())b*this.itemHeight>c.height&&(b=this.availRows());else{this.rows=1;var a=this.totalWidth(),e=this.calcPadding(c),e=c.width-2*e;b*a>e?(this.perRow=e/a|0,b>this.perRow&&(this.rows=1+(b/this.perRow|0),this.rows*this.itemHeight>c.height&&(this.rows=this.availRows(),b=this.rows*this.perRow))):this.perRow=b}return b};this.showValues=function(){var a=this.legendStyle;return"values"==a||"auto"==a&&1==d.series.visibleCount()};this.itemText=function(a,b){var c=a.dataText(b,this.textStyle,
!1);return this.ongettext?this.ongettext(this,a,b,c):c};var b=0;this.calcItemPos=function(a,c){var e=this.itemHeight,d=this.bounds;c.x=d.x;c.y=d.y+this.innerOff;this.isVertical()?(c.x+=d.width-6-this.innerOff,c.y+=0.4*e+a*e+b):(c.x+=this.innerOff+(1+a%this.perRow)*this.totalWidth(),c.y+=e*((a/this.perRow|0)+0.25))};this.calcItemRect=function(a,c){var e=this.itemHeight,d=this.bounds;c.height=e;c.x=d.x;c.y=d.y;this.isVertical()?(c.width=d.width,c.y+=0.4*e+a*e+b):(c.width=this.totalWidth(),c.x+=this.innerOff+
a%this.perRow*c.width,c.y+=e*((a/this.perRow|0)+0.25))};this.mousemove=function(a){var b=this.over,c=new n;if(this.bounds.contains(a))for(var e=this.itemsCount(),d=0;d<e;d++){if(this.calcItemRect(d,c),c.contains(a)){b=d;break}}else b=-1;if(b!=this.over){if(this.onhover)this.onhover(this.over,b);this.over=b;var h=this.chart;window.requestAnimFrame(function(){h.draw()})}};this.drawSymbol=function(a,b,c){var e=this.symbol;e.draw(a,b,c.x-this.itemWidth-e.width-e.padding,c.y+0.4*this.itemHeight)};var e=
{x:0,y:0},h=new n;this.drawItem=function(a,b,i,j){this.calcItemPos(i,e);h.x=e.x;h.y=e.y;this.isVertical()?h.y-=this.chart.isMozilla?0:2:this.chart.isMozilla?h.y++:h.y--;var k=c.font.fill;this.fontColor&&(c.font.fill=this.showValues()?b.getFill(i):b.format.fill);this.over==i&&(c.font.fill="red");c.font.textAlign=j?"start":"end";h.x-=this.itemWidth;j=this.chart.ctx;j.textAlign=c.font.textAlign;c.drawText(h,a);c.font.fill=k;j=!b.isColorEach||this.showValues();this.symbol.visible&&j&&this.drawSymbol(b,
i,e);0<i&&""!=this.dividing.fill&&(j=d.ctx,b=this.bounds,j.beginPath(),this.isVertical()?(j.moveTo(b.x,h.y-2),j.lineTo(b.getRight(),h.y-2)):(i=h.x-this.itemWidth-4,a=this.symbol,a.visible&&(i-=a.width+a.padding),j.moveTo(i,b.y),j.lineTo(i,b.getBottom())),this.dividing.prepare(),j.stroke())};this.drawSeries=function(a,b){var c=d.series.items[a];return c.visible?(this.drawItem(""==c.title?"Series "+a.toString():c.title,c,b,!0),!0):!1};this.draw=function(){var a=this.itemsCount(),e,i;e=this.title;var j=
d.ctx,k,l=this.format.transparency;if(0<a){this.transparent||c.rectangle(this.bounds);0<l&&(k=j.globalAlpha,j.globalAlpha=(1-l)*k);0<b&&(e.bounds.x=this.bounds.x+4,e.bounds.y=this.bounds.y+2,e.doDraw());c.font.prepare();h.width=this.itemWidth;h.height=this.itemHeight;if(this.showValues()){var m=d.series.firstVisible();i=0;e=a;if(this.inverted)for(;e--;)this.drawItem(this.itemText(m,e),m,i++);else for(i=0;i<e;i++)this.drawItem(this.itemText(m,i),m,i)}else if(e=d.series.count(),this.isVertical()&&(e=
Math.min(e,this.availRows())),a=0,this.inverted)for(;e--;)this.drawSeries(e,a)&&a++;else for(i=0;i<e;i++)this.drawSeries(i,a)&&a++;0<l&&(j.globalAlpha=k)}};this.largest=function(){var a=0,b,e,h,k,l=d.series;if(this.showValues()){b=l.firstVisible();k=this.itemsCount();for(e=0;e<k;e++)h=c.textWidth(this.itemText(b,e)),h>a&&(a=h)}else{k=l.count();for(e=0;e<k;e++)b=l.items[e],b.visible&&(h=c.textWidth(b.title),h>a&&(a=h))}return a};this.calcPadding=function(a){return 0.01*this.padding*(this.isVertical()?
a.width:a.height)};this.isVertical=function(){return"right"==this.position||"left"==this.position};this.calcrect=function(){var a=0,e=this.title,h=d.chartRect;c.font.prepare();this.itemHeight=c.textHeight("Wj");this.itemWidth=this.largest();e.visible&&""!=e.text?(e.resize(),b=e.bounds.height,a=e.bounds.width):b=0;var e=this.calcPadding(h),j,k=this.bounds,l=this.align;this.isVertical()?(j=this.symbol.visible?this.symbol.width+this.symbol.padding:0,k.width=6+Math.max(a,6+this.itemWidth+j),0==l&&(l=
20),k.y=0.01*d.bounds.height*l,a=this.itemsCount(),k.height=(0.5+a)*this.itemHeight+b):(a=this.itemsCount(),k.width=e+this.perRow*this.totalWidth(),k.x=0.01*l*h.width+0.5*(h.width-k.width),k.height=this.itemHeight*(this.rows+0.25));""!=c.stroke.fill&&(j=+c.stroke.size,1<j&&(k.width+=j,k.height+=j,this.innerOff=0.5*j));0!=a&&("right"==this.position?(k.x=h.getRight()-k.width,h.setRight(Math.max(h.x,k.x-e))):"left"==this.position?(k.x=h.x,h.setLeft(k.x+k.width+e)):"top"==this.position?(k.y=h.y+e,h.setTop(k.getBottom()+
e)):(k.y=h.getBottom()-k.height-e,h.setBottom(k.y-e)))}}function E(d,c){Tee.Annotation.call(this,c);this.series=d;this.arrow=new Tee.Format(c);this.arrow.length=10;this.arrow.underline=!1;this.style="auto";this.drawEvery=1;this.visible=!1;this.setChart=function(a){this.chart=a;this.format.setChart(a);this.arrow.setChart(a)};this.drawPolar=function(a,b,c,d){var f=this.series.markText(d),d=a.x+Math.cos(c)*b,g=a.y+Math.sin(c)*b,i=this.chart.ctx;this.text=f;this.resize();var f=this.bounds,j,k=this.position,
b=b+this.arrow.length;j=a.x+Math.cos(c)*b;b=a.y+Math.sin(c)*b;0>j-f.width&&(j-=j-f.width-4);k.x=Math.abs(j-a.x)<f.width?j-0.5*f.width:j<a.x?j-f.width:j;k.y=Math.abs(b-a.y)<f.height?b-0.5*f.height:b<a.y?b-f.height:b;i.beginPath();i.moveTo(d,g);i.lineTo(j,b);if(this.arrow.underline&&(b<=k.y||b>=k.y+f.height))i.moveTo(k.x,b),i.lineTo(k.x+f.width,b);this.arrow.stroke.prepare();i.stroke();this.draw()};this.canDraw=function(a,b,c,d){var f=this.series.markText(c),c=this.arrow;if(f&&""!=f){this.text=f;this.resize();
var f=d?-1:1,g=this.bounds;this.series.yMandatory?(g.x=a-0.5*g.width,g.y=b-f*(c.length+(d?0:g.height))):(g.x=a+f*c.length,d&&(g.x-=g.width),g.y=b-0.5*g.height);this.position.x=g.x;this.position.y=g.y;return!0}return!1};this.drawMark=function(a,b,c,d){if(this.canDraw(a,b,c,d)){this.draw();var c=this.bounds,f=this.series.yMandatory,g=this.arrow,i=d?c.y:c.getBottom(),j=this.chart.ctx;j.beginPath();f?(j.moveTo(a,i),j.lineTo(a,b),g.underline&&(j.moveTo(c.x,i),j.lineTo(c.x+c.width,i))):(b=c.y+0.5*c.height,
j.moveTo(a,b),d&&(c.x+=c.width),j.lineTo(c.x,b),g.underline&&(j.moveTo(c.x,c.y+c.height),j.lineTo(c.x+(d?-c.width:c.width),c.y+c.height)));g.stroke.prepare();j.stroke()}}}function O(d){for(var c=0,a=d.length;a--;)c+=d[a];return c}function F(d){this.chart=d;this.items=[];this.count=function(){return this.items.length};this.clicked=function(c){var a=!1;this.each(function(b){if(b.visible&&b.onclick){var e=b.clicked(c);-1!=e&&(a=b.onclick(b,e,c.x,c.y))}});return a};this.mousedown=function(c){for(var a=
0,b,e=!1;b=this.items[a++];)b.visible&&b.mousedown(c)&&(e=!0);return e};this.mousemove=function(c){for(var a=this.items.length,b;a--&&!(b=this.items[a],b.visible&&b.mousemove(c)););};this.visibleCount=function(c,a,b){for(var e=0,d=this.items.length,f;d--,f=this.items[d];)if(f.visible&&(!a||f instanceof a))b&&f==c&&(b.index=e),e++;b&&(b.total=e,b.index=b.total-1-b.index);return e};this.beforeDraw=function(){this.each(function(c){c.useAxes&&c.recalcAxes();c.calcColorEach()})};this.anyUsesAxes=function(){for(var c=
this.items.length,a;c--;)if(a=this.items[c],a.visible&&a.useAxes)return!0;return!1};this.firstVisible=function(){for(var c=0,a;a=this.items[c++];)if(a.visible)return a;return null};this.vertMargins=function(){var c,a=this.items,b=a.length,e,d;if(0<b){c={x:0,y:0};e={x:0,y:0};a[0].vertMargins(c);for(d=1;d<b;d++)e.x=e.y=0,a[d].vertMargins(e),e.x>c.x&&(c.x=e.x),e.y>c.y&&(c.y=e.y)}return c};this.horizMargins=function(){var c,a=this.items,b=a.length,e,d;if(0<b){c={x:0,y:0};e={x:0,y:0};a[0].horizMargins(c);
for(d=1;d<b;d++)e.x=e.y=0,a[d].horizMargins(e),e.x>c.x&&(c.x=e.x),e.y>c.y&&(c.y=e.y)}return c};this.minXValue=function(c){for(var a=Infinity,b=this.items.length,e;b--;)if(e=this.items[b],e.visible&&(!c||e.associatedToAxis(c)))e=e.minXValue(),e<a&&(a=e);return a};this.minYValue=function(c){for(var a=Infinity,b=this.items.length,e;b--;)if(e=this.items[b],e.visible&&(!c||e.associatedToAxis(c)))e=e.minYValue(),e<a&&(a=e);return a};this.maxXValue=function(c){for(var a=-Infinity,b=this.items.length,e;b--;)if(e=
this.items[b],e.visible&&(!c||e.associatedToAxis(c)))e=e.maxXValue(),e>a&&(a=e);return a};this.maxYValue=function(c){for(var a=-Infinity,b=this.items.length,e;b--;)if(e=this.items[b],e.visible&&(!c||e.associatedToAxis(c)))e=e.maxYValue(),e>a&&(a=e);return a};this.draw=function(){var c=this.items.length,a=this.chart,b=a.ctx,e=a.aspect,d,f;if(0<c){var g=e.clip&&this.anyUsesAxes();g&&e.clipRect(a.chartRect);try{for(d=0;d<c;d++)if(f=this.items[d],f.visible){var i=b.globalAlpha;b.globalAlpha=1-f.format.transparency;
f.transform&&(b.save(),f.transform());f.draw();if(f.ondraw)f.ondraw(f);f.transform&&b.restore();b.globalAlpha=i}}finally{g&&b.restore()}for(d=0;d<c;d++)f=this.items[d],f.visible&&f.marks.visible&&(f.transform&&(b.save(),f.transform()),f.drawMarks(),f.transform&&b.restore())}}}function P(d){this.chart=d;this.visible=!0;this.left=new u(d,!1,!1);this.top=new u(d,!0,!0);this.right=new u(d,!1,!0);this.bottom=new u(d,!0,!1);this.items=[this.left,this.top,this.right,this.bottom];this.each=function(c){for(var a=
0,b;b=this.items[a++];)c.call(b)};this.add=function(c,a){var b=new u(d,c,a);b.custom=!0;this.items.push(b);return b}}"undefined"!==typeof exports&&(exports.Tee=Tee);"undefined"!==typeof window&&(window.requestAnimFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(d){window.setTimeout(d,1E3/60,(new Date).getTime())});n.prototype.set=function(d,c,a,b){this.x=d;this.y=c;this.width=
a;this.height=b};n.prototype.setFrom=function(d){this.x=d.x;this.y=d.y;this.width=d.width;this.height=d.height};n.prototype.getRight=function(){return this.x+this.width};n.prototype.getBottom=function(){return this.y+this.height};n.prototype.setTop=function(d){this.height-=d-this.y;this.y=d};n.prototype.setBottom=function(d){this.height=d-this.y};n.prototype.setLeft=function(d){this.width-=d-this.x;this.x=d};n.prototype.setRight=function(d){this.width=d-this.x};n.prototype.contains=function(d){return d.x>=
this.x&&d.x<=this.x+this.width&&d.y>=this.y&&d.y<=this.y+this.height};Tee.Tool=function(d){this.chart=d;this.active=!0};Tee.Animation=function(d,c){Tee.Tool.call(this,d);this.active=!0;this.mode="linear";this.duration=500;this.items=[];d&&(d instanceof Tee.Chart?this.chart=d:d instanceof Tee.Animation&&(this.chart=d.chart,d.items.push(this)));var a=null;this.animate=function(b){b&&(this.chart=b);this.init=(new Date).getTime();a=this;a.start();for(var b=0,c;c=a.items[b++];)c.active&&(c.chart=a.chart,
c.start());a.chart.draw();requestAnimFrame(this.step,this)};this.start=function(){};this.stop=function(){};this.doStep=function(a){c&&c(a)};this.step=function(b){b||(b=(new Date).getTime());var c,b=(b-a.init)/a.duration,d="linear"==a.mode?b:Math.pow(2,10*(b-1));if(0<=d&&1>d){a.doStep(d);for(b=0;c=a.items[b++];)c.active&&(c.chart=a.chart,c.doStep(d));a.chart.draw();requestAnimFrame(a.step,a)}else{a.stop();for(b=0;c=a.items[b++];)c.active&&(c.chart=a.chart,c.stop());if(a.onstop)a.onstop(a);a.chart.draw()}}};
Tee.Animation.prototype=new Tee.Tool;Tee.Tool.prototype.mousedown=function(){};Tee.Tool.prototype.mousemove=function(){};Tee.Tool.prototype.clicked=function(){return!1};Tee.Tool.prototype.draw=function(){};z.prototype.setEndColor=function(d){for(var c=1,a=this.colors.length;c<a;c++)this.colors[c]=d};y.prototype.set=function(d){this.visible=d.visible;this.color=d.color;this.blur=d.blur;this.width=d.width;this.height=d.height};x.prototype.getSize=function(){var d=this.style.split(" "),c,a;for(c=0;c<
d.length;c++)if(a=parseFloat(d[c]))return a;return 20};x.prototype.setSize=function(d){var c="",a=this.style.split(" "),b;for(b=0;b<a.length;b++)parseFloat(a[b])?c+=d.toString()+"px ":c+=a[b]+" ";this.style=c};x.prototype.prepare=function(){var d=this.chart.ctx;d.textAlign=this.textAlign;d.textBaseline=this.baseLine;this._sh&&this._sh.prepare(d);d.font!=this.style&&(d.font=this.style)};x.prototype.setChart=function(d){this.chart=d;this._g&&(this._g.chart=d);this._sh&&(this._sh.chart=d);this._s&&this._s.setChart(d)};
Tee.Format=function(d){this.chart=d;this.gradient=new z(d);this.fill="rgb(200,200,200)";this.stroke=new A(d);this.round={x:0,y:0};this.transparency=0;this.font=new x(d);this._img=null;Object.defineProperty(this,"image",{get:function(){this._img||(this._img=new I(this.chart));return this._img}});this.shadow=new y(d);this.roundRect=function(a,b,c,d,f){if(a.roundRect)a.roundRect(b,c,d,f,this.round.x,this.round.y);else{var g=b+d,i=c+f,j=this.round.x,k=this.round.y,l=this.round.corners;0>f&&(c=i,i=c-f);
0>d&&(b=g,g=b-d);2*j>d&&(j=0.5*d);2*k>f&&(k=0.5*f);!l||l[0]?a.moveTo(b+j,c):a.moveTo(b,c);!l||l[1]?(a.lineTo(g-j,c),a.quadraticCurveTo(g,c,g,c+k)):a.lineTo(g,c);!l||l[2]?(a.lineTo(g,i-k),a.quadraticCurveTo(g,i,g-j,i)):a.lineTo(g,i);!l||l[3]?(a.lineTo(b+j,i),a.quadraticCurveTo(b,i,b,i-k)):a.lineTo(b,i);!l||l[0]?(a.lineTo(b,c+k),a.quadraticCurveTo(b,c,b+j,c)):a.lineTo(b,c);a.closePath()}};this.textHeight=function(){return 1.3*this.font.getSize()};this.textWidth=function(a){return this.chart.ctx.measureText(a).width};
this.draw=function(a,b,c,d,f,g){var i=this._img,j;0<this.transparency&&(j=a.globalAlpha,a.globalAlpha=(1-this.transparency)*j);this.shadow.prepare(a);i&&i.visible&&""!=i.url?(a.save(),a.clip(),b?(b=b(),i.tryDraw(b.x,b.y,b.width,b.height)):i.tryDraw(c,d,f,g),a.restore()):(a.fillStyle=this.gradient.visible?b?this.gradient.create(b()):this.gradient.rect(c,d,f,g):this.fill,a.fill());""!=this.stroke.fill&&(this.stroke.prepare(),a.stroke());0<this.transparency&&(a.globalAlpha=j)};this.drawText=function(a,
b){function c(a,b,d){f.fillText(d,a,b);g&&""!=g.fill&&(g.prepare(),f.strokeText(d,a,b))}var d=this.font._g,f=this.chart.ctx,g=this.font._s,i=this.font.textAlign;f.fillStyle=d&&d.visible&&a?d.create(a):this.font.fill;if("center"==i)a.x+=0.5*a.width;else if("right"==i||"end"==i)a.x+=a.width;d=b.split("\n");i=d.length;if(1<i)for(var j=this.textHeight(d[0]),k=a.y,l=0;l<i;l++)c(a.x,k,d[l]),k+=j;else c(a.x,a.y,b)};this.rectPath=function(a,b,c,d){var f=this.chart.ctx;f.beginPath();0<this.round.x||0<this.round.y?
this.roundRect(f,a,b,c,d):f.rect(a,b,c,d)};this.rectangle=function(a,b,c,d){1>this.transparency&&("object"===typeof a?this.rectangle(a.x,a.y,a.width,a.height):(this.rectPath(a,b,c,d),this.draw(this.chart.ctx,null,a,b,c,d)))};var c=new n;this.polygon=function(a){var b=this.chart.ctx,d=a.length,h;b.beginPath();b.moveTo(a[0].x,a[0].y);for(h=1;h<d;h++)b.lineTo(a[h].x,a[h].y);b.closePath();this.draw(b,function(){var b=0,d=0,e=0,h=0,k=a.length,l,m;if(0<k){b=e=a[0].x;d=h=a[0].y;for(m=1;m<k;m++)l=a[m].x,
l<b?b=l:l>e&&(e=l),l=a[m].y,l<d?d=l:l>h&&(h=l)}c.x=b;c.y=d;c.width=e-b;c.height=h-d;return c})};this.ellipsePath=function(a,b,c,d,f){a.save();a.translate(b,c);a.scale(0.5*d,0.5*f);a.beginPath();a.arc(0,0,1,0,2*Math.PI,!1);a.restore()};this.ellipse=function(a,b,c,d){var f=this.chart.ctx;this.ellipsePath(f,a,b,c,d);this.draw(f,null,a-0.5*c,b-0.5*d,c,d)}};Tee.Format.prototype.setChart=function(d){this.chart=d;this.shadow.chart=d;this.gradient.chart=d;this.font.setChart(d);this._img&&(this._img.chart=
d);this.stroke.setChart(d)};Tee.Annotation=function(d,c,a,b){Tee.Tool.call(this,d);this.position=new q(a||10,b||10);var e=this.margins=new D;this.items=[];var h=this.bounds=new n;this.visible=!0;this.transparent=!1;this.text=c||"";var f=this.format=new Tee.Format(d);f.font.textAlign="center";f.font.baseLine="top";f.fill="beige";f.round={x:4,y:4};f.stroke.fill="silver";f.shadow.visible=!0;var g,i,j;this.moveTo=function(a,b){this.position.x=a;this.position.y=b;this.resize()};this.resize=function(){if(this.text){f.font.prepare();
this.rows=this.text.split("\n");g=f.textHeight(this.text);var a=this.rows.length;i=g*a+e.top;var b,c=i+e.bottom;if(1<a)for(b=0;a--;)b=Math.max(b,f.textWidth(this.rows[a]+"W"));else b=f.textWidth(this.text+"W");b+=e.left+e.right;var a=this.position,d=a.y+i,j,r;for(j=0;r=this.items[j++];){var s=r.bounds;r.resize();c+=s.height;b=Math.max(b,s.width);s.x=a.x;s.y=d;d+=s.height}for(j=0;r=this.items[j++];)r.bounds.width=b-e.right;h.set(a.x,a.y,b,c)}};this.add=function(a){a=new Tee.Annotation(this.chart,a);
this.items.push(a);a.transparent=!0;return a};this.doDraw=function(){if(""!=this.text){this.transparent||f.rectangle(h);var a,b=this.format.transparency,c=this.chart?this.chart.ctx:null;0<b&&(a=c.globalAlpha,c.globalAlpha=(1-b)*a);f.font.prepare();h.y+=e.top+0.1*g;h.x+=e.left;var d=h.width;h.width-=e.right;f.drawText(h,this.text);h.x=this.position.x;h.y=this.position.y;h.width=d}for(var d=0,j;j=this.items[d++];)j.doDraw();0<b&&(c.globalAlpha=a)};this.clicked=function(a){return this.visible&&h.contains(a)};
this.doMouseMove=function(a){(this.mouseinside=this.clicked(a))?(this.cursor&&(this.chart.newCursor=this.cursor),this.wasinside||(j=new H(250,h,f))):this.wasinside&&(j.restore(),this.chart.draw());this.wasinside=this.mouseinside};this.mousemove=function(a){this.cursor&&"default"!=this.cursor&&this.doMouseMove(a)};this.forceDraw=function(){this.resize();this.doDraw()}};Tee.Annotation.prototype=new Tee.Tool;Tee.Annotation.prototype.draw=function(){this.visible&&this.forceDraw()};Tee.DragTool=function(d){Tee.Tool.call(this,
d);this.series=null;var c=this.target={series:null,index:-1};this.clicked=function(){c.series=null;c.index=-1};var a=new q(0,0);this.mousedown=function(b){var d=this.chart.series.items,h=d.length;this.chart.calcMouse(b,a);c.series=null;c.index=-1;if(this.series&&this.series.visible)c.index=this.series.clicked(a),-1!=c.index&&(c.series=this.series);else for(b=0;b<h;b++)if(d[b].visible&&(c.index=d[b].clicked(a),-1!=c.index)){c.series=d[b];break}return-1!=c.index};this.mousemove=function(a){if(-1!=c.index){var d=
c.series,a=d.mandatoryAxis.fromPos(d.yMandatory?a.y:a.x);this.onchanging&&(a=this.onchanging(this,a));d.data.values[c.index]=a;if(this.onchanged)this.onchanged(this,a);this.chart.draw()}}};Tee.DragTool.prototype=new Tee.Tool;Tee.CursorTool=function(d){Tee.Tool.call(this,d);this.direction="both";this.size=new q(0,0);this.followMouse=!0;this.dragging=-1;this.format=new Tee.Format(d);this.horizAxis=d?d.axes.bottom:null;this.vertAxis=d?d.axes.left:null;var c,a=new n;this.over=function(b){var d=-1;if(a.contains(b)){var e=
3>Math.abs(c.x-b.x),b=3>Math.abs(c.y-b.y),h=this.direction;if("both"==h&&e&&b)d=0;else if(e&&("both"==h||"vertical"==h))d=1;else if(b&&("both"==h||"horizontal"==h))d=2}return d};this.calcRect=function(){var b=d.chartRect;a.x=this.horizAxis?this.horizAxis.startPos:b.x;a.width=this.horizAxis?this.horizAxis.endPos-a.x:b.width;a.y=this.vertAxis?this.vertAxis.startPos:b.y;a.height=this.vertAxis?this.vertAxis.endPos-a.y:b.height};var b=new q(0,0);this.mousedown=function(a){this.chart.calcMouse(a,b);this.dragging=
this.followMouse?-1:this.over(b);return-1<this.dragging};this.clicked=function(){this.dragging=-1};this.mousemove=function(b){var g=this.dragging,i=this.followMouse;if(i||-1<g)if(c||(c=new q),c.x!=b.x||c.y!=b.y)if(this.calcRect(),a.contains(b)){if(i||0==g||1==g)c.x=b.x;if(i||0==g||2==g)c.y=b.y;"full"==this.render?this.chart.draw():(e&&("copy"==this.render?this.chart.ctx.drawImage(e,0,0):(g=d.bounds,h.clearRect(g.x,g.y,g.width,g.height))),this.dodraw("copy"==this.render?this.chart.ctx:h));if(this.onchange)this.onchange(b);
return}b=this.over(b);this.chart.newCursor=c&&-1<b?0==b?"move":1==b?"e-resize":"n-resize":"default"};this.render="copy";var e,h;this.setRender=function(a){this.render=a;e&&(this.resetCopy(),this.chart.draw())};this.resetCopy=function(){var a=this.chart.canvas;"layer"==this.render?(e.style.position="absolute",a.parentNode.appendChild(e),e.style.left=a.offsetLeft,e.style.top=a.offsetTop,e.style.zIndex=10,e.style.pointerEvents="none"):e.parentNode&&e.parentNode.removeChild(e)};this.draw=function(){"full"==
this.render?this.dodraw(this.chart.ctx):(e||(e=this.chart.canvas.cloneNode(),this.resetCopy(),h=e.getContext("2d")),"copy"==this.render?(h.drawImage(d.canvas,0,0),this.dodraw(this.chart.ctx)):this.dodraw(h))};this.dodraw=function(b){var d=this.direction,e="both"==d,h;this.calcRect();c||(c=new q(a.x+0.5*a.width,a.y+0.5*a.height));b.beginPath();if(e||"vertical"==d)h=0.5*this.size.y,b.moveTo(c.x,0==h?a.y:c.y-h),b.lineTo(c.x,0==h?a.y+a.height:c.y+h);if(e||"horizontal"==d)h=0.5*this.size.x,b.moveTo(0==
h?a.x:c.x-h,c.y),b.lineTo(0==h?a.x+a.width:c.x+h,c.y);this.format.stroke.prepare(this.format.stroke.fill,b);b.stroke()}};Tee.CursorTool.prototype=new Tee.Tool;Tee.ToolTip=function(d){function c(a){function d(a){b.moveTo(b.oldX+a*b.deltaX,b.oldY+a*b.deltaY);b.autoRedraw&&b.chart.draw()}a||(a=(new Date).getTime());a=(a-b.init)/b.animated;1>a?(d(a),window.requestAnimFrame(c,b)):d(1)}Tee.Annotation.call(this,d);this.visible=!1;this.currentSeries=null;this.currentIndex=-1;this.timID=null;this.autoHide=
!1;this.delay=1E3;this.animated=100;this.autoRedraw=!0;this.hide=function(){if(this.visible){if(this.onhide)this.onhide(this);this.visible=!1;this.autoRedraw&&this.chart.draw();this.currentIndex=-1;this.currentSeries=null}};var a=function(a){a&&a[0].hide()};this.mousemove=function(b){for(var c=this.chart.series,d=c.count(),g=null,i,j=0;j<d;j++){var k=c.items[j];if(k.visible&&(i=k.clicked(b),-1!=i)){g=k;break}}if(-1==i)this.hide(),this.currentIndex=-1,this.currentSeries=null;else if(i!=this.currentIndex||
g!=this.currentSeries){this.currentIndex=i;this.currentSeries=g;if(this.onshow)this.onshow(this,g,i);this.refresh(g,i);this.autoHide&&0<this.delay&&(clearTimeout(this.timID),this.timID=window.setTimeout(a,this.delay,[this]))}};var b=null;this.refresh=function(a,d){this.visible=!0;this.text=a.markText(d);this.ongettext&&(this.text=this.ongettext(this,this.text,a,d));if(""!=this.text){this.resize();var f=new q;a.calc(d,f);f.x-=0.5*this.bounds.width;f.y-=1.5*this.bounds.height;!this.autoHide&&0<this.animated&&
!isNaN(this.position.x)&&!isNaN(this.position.y)?(this.oldX=this.position.x,this.oldY=this.position.y,this.deltaX=f.x-this.oldX,this.deltaY=f.y-this.oldY,this.init=(new Date).getTime(),b=this,window.requestAnimFrame(c,this)):(this.moveTo(f.x,f.y),this.autoRedraw&&this.chart.draw())}}};Tee.ToolTip.prototype=new Tee.Annotation;Tee.RainbowPalette=function(){return"#FF0000 #FF7F00 #FFFF00 #00FF00 #0000FF #6600FF #8B00FF".split(" ")};Tee.Palette=function(d){this.colors=d};Tee.Palette.prototype.get=function(d){return this.colors[-1==
d?0:d%this.colors.length]};C.prototype=new Tee.Annotation;u.adjustRect=function(){if(this.visible){var d=0,c=this.labels,a=this.chart.chartRect;if((this.firstSeries=this.hasAnySeries())&&this.visible)this.checkMinMax(),c.checkStyle(),this.custom||(c.visible&&(c.format.font.prepare(),d=this.horizontal?c.format.textHeight("Wj"):this.minmaxLabelWidth(),c.alternate&&(d*=2),d+=c.padding),this.ticks.visible&&(d+=this.ticks.length),c=this.title,c.visible&&(c.text&&""!=c.text)&&(c.resize(),d+=c.bounds.height),
this.horizontal?this.otherSide?a.setTop(a.y+d):a.height-=d:this.otherSide?a.width-=d:a.setLeft(a.x+d))}};u.prototype.setPos=function(d,c){this.startPos=d+0.01*this.start*c;this.endPos=d+0.01*this.end*c;this.axisSize=this.endPos-this.startPos};u.calcRect=function(){if(this.firstSeries){this.checkMinMax();var d=this.chart.chartRect,c=this.bounds;this.horizontal?(c.y=this.otherSide?d.y:d.y+d.height,c.width=d.width,this.setPos(d.x,d.width)):(c.x=this.otherSide?d.x+d.width:d.x,c.height=d.height,this.setPos(d.y,
d.height));this.calcScale();this.automatic&&(c=this.chart.series,c=this.horizontal?c.horizMargins():c.vertMargins(),0<c.x&&(this.minimum-=this.fromSize(c.x)),0<c.y&&(this.maximum+=this.fromSize(c.y)),this.calcScale());c=this.horizontal?d.height:d.width;c*=0.01*this.position;this.axisPos=this.horizontal?this.otherSide?d.y+c:d.getBottom()-c:this.otherSide?d.getRight()-c:d.x+c}};u.draw=function(){this.visible&&this.firstSeries&&(this.drawAxis(),this.roundMin()+1E3*this.increm>this.maximum&&(this.grid.visible&&
this.drawGrids(),this.ticks.visible&&this.drawTicks(this.ticks,1,0),this.innerTicks.visible&&this.drawTicks(this.innerTicks,-1,0),this.minorTicks.visible&&this.drawTicks(this.minorTicks,1,Math.max(0,this.minorTicks.count)),this.labels.visible&&this.drawLabels()),this.title.visible&&(this.title.text&&""!=this.title.text)&&this.drawTitle())};E.prototype=new Tee.Annotation;Tee.Series=function(d,c){this.chart=null;this.data={values:[],labels:[],source:null};this.yMandatory=!0;this.horizAxis="bottom";
this.vertAxis="left";var a=this.format=new Tee.Format(this.chart),b=this.hover=new Tee.Format(this.chart),e=b.shadow;a.fill="";a.stroke.fill="";this.visible=!0;b.stroke.size=3;b.fill="";b.stroke.fill="red";e.visible=!0;e.color="red";e.blur=10;e.width=0;e.height=0;this.cursor="default";this.over=-1;this.marks=new E(this,this.chart);this.palette=new Tee.Palette;this.colorEach="auto";this.useAxes=!0;this.decimals=2;this.init=function(a,b){"object"===typeof a&&a&&(a instanceof Array?(this.data.values=
a,b instanceof Array&&(this.data.labels=b)):a instanceof Tee.Chart?(this.chart=a,b instanceof Array&&(this.data.values=b)):(this.data.source=a,this.refresh()))};this.init(d,c);this.getFill=function(a,b){var c=this.palette,c=c&&c.colors?c.get(a):null;return null==c?this.isColorEach||!b?this.chart.palette.get(a):b.fill:c};this.getFillStyle=function(b,c){return a.gradient.visible?a.gradient.create(b,c):c};this.recalcAxes=function(){var a=this.chart.axes;this._horizAxis=this.horizAxis instanceof u?this.horizAxis:
"top"==this.horizAxis?a.top:a.bottom;this._vertAxis=this.vertAxis instanceof u?this.vertAxis:"right"==this.vertAxis?a.right:a.left;this.mandatoryAxis=this.yMandatory?this._vertAxis:this._horizAxis;this.notmandatory=this.yMandatory?this._horizAxis:this._vertAxis};this.title="";this.refresh=function(a){this.data.source?this.data.source instanceof HTMLTextAreaElement?(parseText(this.data,this.data.source.value),this.chart&&this.chart.draw()):this.data.source instanceof HTMLInputElement?doHttpRequest(this,
this.data.source.value,function(a,b){parseText(a.data,b);a.chart.draw()},function(b,c){a&&a(this,b,c)}):a&&a(this):this.data.xml?(parseXML(this,this.data.xml),this.chart.draw()):this.data.json&&(parseJSON(this,this.data.json),this.chart.draw())};this.valueOrLabel=function(a){var b=this.data.labels[a];if(!b||""==b)b=this.valueText(a);return b};this.toPercent=function(a){var b=this.data.values;return(100*b[a]/O(b)).toFixed(this.decimals)+" %"};this.dataText=function(a,b,c){c=c?this.labelOrTitle(a):
this.data.labels[a];return"value"==b?this.valueText(a):"percent"==b?this.toPercent(a):"percentlabel"==b?this.toPercent(a)+(c?" "+c:""):"valuelabel"==b||"auto"==b?this.valueText(a)+(c?" "+c:""):"label"==b?c||"":"index"==b?a.toFixed(0):"labelvalue"==b?(c?c+" ":"")+this.valueText(a):"labelpercent"==b?(c?c+" ":"")+this.toPercent(a):this.valueOrLabel(a)};this.markText=function(a){var b=this.marks,c=this.dataText(a,b.style,!1);return b.ongettext?b.ongettext(this,a,c):c};this.valueText=function(a){return(a=
(this.data._old||this.data.values)[a])?a instanceof Date?a.format(this.dateFormat):(a|0)==a?a.toFixed(0):a.toFixed(this.decimals):"0"};this.associatedToAxis=function(a){return a.horizontal?"both"==this.horizAxis||this._horizAxis==a:"both"==this.vertAxis||this._vertAxis==a};this.bounds=function(a){var b=this._horizAxis,c=this._vertAxis;a.x=b.calc(this.minXValue());a.width=b.calc(this.maxXValue())-a.x;a.y=c.calc(this.maxYValue());a.height=c.calc(this.minYValue())-a.y};this.calcStack=function(a,b,c){var c=
this.pointOrigin(a,!1)+c,d=this.mandatoryAxis;b.x=this.notmandatory.calc(this.data.x?this.data.x[a]:a);this.isStack100?(a=this.pointOrigin(a,!0),b.y=0==a?d.endPos:d.calc(100*c/a)):b.y=d.calc(c);this.yMandatory||(a=b.x,b.x=b.y,b.y=a)};this.pointOrigin=function(a,b){var c=0,d,e,k=this.chart.series.items;for(d=0;d<k.length&&!(e=k[d],!b&&e==this);d++)e.visible&&(e.constructor==this.constructor&&e.data.values.length>a)&&(e=e.data.values[a],c+=b&&0>e?-e:e);return c};this.doHover=function(a){var b=this.chart;
if(a!=this.over){if(b.onhover)b.onhover(this,a);this.over=a;this.hover.enabled&&window.requestAnimFrame(function(){b.draw()})}}};Tee.Series.prototype.setChart=function(d,c){d.chart=c;d.recalcAxes();d.format.setChart(c);d.marks.setChart(c);d.hover.setChart(c)};Tee.Series.prototype.calc=function(d,c){var a=this.data,b=this.notmandatory.calc(a.x?a.x[d]:d),a=this.mandatoryAxis.calc(a.values[d]);c.x=this.yMandatory?b:a;c.y=this.yMandatory?a:b};Tee.Series.prototype.getRect=function(){return new n};Tee.Series.prototype.clicked=
function(){return-1};Tee.Series.prototype.labelOrTitle=function(d){return this.data.labels[d]||this.title};Tee.Series.prototype.mousedown=function(){return!1};Tee.Series.prototype.mousemove=function(d){if(this.hover.enabled||"default"!=this.cursor){var c=this.clicked(d);this.doHover(c);if("default"!=this.cursor&&-1!=c)return this.chart.newCursor=this.cursor,!0}c=this.marks;if(c.visible){var a=this.data.values.length,b=new q,e;for(e=0;e<a;e+=c.drawEvery)if(this.calc(e,b),c.canDraw(b.x,b.y,e)&&c.bounds.contains(d)){this.doHover(e);
break}}return!1};Tee.Series.prototype.drawMarks=function(){var d=this.data.values.length,c=new q,a;for(a=0;a<d;a+=this.marks.drawEvery)this.calc(a,c),this.marks.drawMark(c.x,c.y,a)};Tee.Series.prototype.horizMargins=function(){};Tee.Series.prototype.vertMargins=function(){};Tee.Series.prototype.minXValue=function(){return this.data.x&&0<this.data.x.length?Math.min.apply({},this.data.x):0};Tee.Series.prototype.minYValue=function(){var d=this.data.values;return 0<d.length?Math.min.apply({},d):0};Tee.Series.prototype.maxXValue=
function(){if(this.data.x)return 0<this.data.x.length?Math.max.apply({},this.data.x):0;var d=this.data.values.length;return 0==d?0:d-1};Tee.Series.prototype.maxYValue=function(){var d=this.data.values;return 0<d.length?Math.max.apply({},d):0};Tee.Series.prototype.calcColorEach=function(){this.isColorEach="yes"==this.colorEach};Tee.Series.prototype.stackMaxValue=function(){if("100"==this.stacked)return 100;var d=Tee.Series.prototype.maxYValue;if("no"==this.stacked)return d.call(this);for(var d=d.call(this),
c=this.data.values,a=c.length;a--;)d=Math.max(d,this.pointOrigin(a,!1)+c[a]);return d};Tee.Series.prototype.count=function(){return this.data.values.length};Tee.Series.prototype.addRandom=function(d,c,a){c||(c=1E3);var b=this.data;b.values.length=d;a&&(b.x=Array(d));if(0<d){b.values[0]=Math.random()*c;a&&(b.x[0]=Math.random()*c);for(var e=1;e<d;e++)b.values[e]=b.values[e-1]+Math.random()*c-0.5*c,a&&(b.x[e]=Math.random()*c)}return this};Tee.Series.prototype.doSort=function(d,c){if("none"==d)return null;
for(var a=this.data.values,b=a.length,e=Array(b),h=0;h<b;h++)e[h]=h;"labels"==d?(a=this.data.labels,e.sort(c?function(b,c){return a[b]<a[c]?1:a[b]==a[c]?0:-1}:function(b,c){return a[c]<a[b]?1:a[b]==a[c]?0:-1})):e.sort(c?function(b,c){return a[b]-a[c]}:function(b,c){return a[c]-a[b]});return e};F.prototype.each=function(d){for(var c=this.items.length,a=0;a<c;a++)d(this.items[a])};Tee.Chart=function(d,c,a){function b(b){h.chart.addSeries(new (a||Tee.Bar)(h.chart)).data.values=b}var e="undefined"!=typeof navigator?
navigator.userAgent.toLowerCase():"";this.isChrome=-1<e.indexOf("chrome");this.isAndroid=-1<e.indexOf("android");this.isMozilla=window.mozRequestAnimationFrame;d&&(this.canvas="undefined"!==typeof HTMLCanvasElement&&d instanceof HTMLCanvasElement?d:"string"==typeof d?document.getElementById(d):d);this.canvas||(this.canvas=document.createElement("canvas"),this.canvas.width=600,this.canvas.height=400);var h=this.canvas;this.bounds=0==h.clientWidth?new n(0,0,h.width,h.height):new n(0,0,h.clientWidth,
h.clientHeight);this.chartRect=new n;this.chartRect.setFrom(this.bounds);this.palette=new Tee.Palette("#4466a3 #f39c35 #f14c14 #4e97a8 #2b406b #1d7b63 #b3080e #f2c05d #5db79e #707070 #f3ea8d #b4b4b4".split(" "));this.aspect={chart:this,view3d:!1,ortogonal:!0,rotation:0,elevation:315,perspective:50,clip:!0,clipRect:function(a){var b=this.chart.ctx;b.save();b.beginPath();b.rect(a.x,a.y,a.width,a.height);b.clip()}};this.panel=new M(this);this.walls={chart:this,visible:!0,left:new B(this),right:new B(this),
bottom:new B(this),back:new B(this),draw:function(){var a,b=this.chart.ctx,c=this.transparency;0<c&&(a=b.globalAlpha,b.globalAlpha=(1-c)*a);!this.back.visible||this.back.draw();this.chart.aspect.view3d&&(this.left.visible&&this.left.draw(),this.bottom.visible&&this.bottom.draw(),this.right.visible&&this.right.draw());0<c&&(b.globalAlpha=a)}};d=this.walls.back.format;d.fill="rgb(240,240,240)";d.shadow.visible=!0;this.axes=new P(this);this.legend=new N(this);this.series=new F(this);this.title=new C(this,
"blue");this.title.text="TeeChart";this.footer=new C(this,"red");this.zoom=new K(this);this.scroll=new L(this);this.tools=new J(this);this.oldPos=new q;this.calcMouse=function(a,b){if(null==a.pageX){var c=document.documentElement&&null!=document.documentElement.scrollLeft?document.documentElement:document.body;b.x=a.clientX+c.scrollLeft;b.y=a.clientY+c.scrollTop}else b.x=a.pageX,b.y=a.pageY;c=this.canvas;if(c.offsetParent){do b.x-=c.offsetLeft,b.y-=c.offsetTop;while(c=c.offsetParent)}};var f=new q(0,
0);this.domousemove=function(a){var b=this.chart;if(b.ctx){a=a||window.event;a.touches&&(a=a.touches[a.touches.length-1]);b.calcMouse(a,f);if(b.scroll.active){var c=b.scroll.direction,d="both"==c,e;if(d||"horizontal"==c)e=b.axes.bottom.fromSize(b.oldPos.x-f.x),b.axes.top.scroll(e),b.axes.bottom.scroll(e);if(d||"vertical"==c)e=-b.axes.left.fromSize(b.oldPos.y-f.y),b.axes.left.scroll(e),b.axes.right.scroll(e);b.oldPos.x=f.x;b.oldPos.y=f.y;b.scroll.done=!0;b.canvas.oncontextmenu=function(){return!1};
if(b.onscroll)b.onscroll(a);b.scroll.done&&window.requestAnimFrame(function(){b.draw()});return!1}if(b.zoom.active){if(f.x!=b.oldPos.x||f.y!=b.oldPos.y)b.zoom.old||(b.zoom.old=new q),b.zoom.old.x=f.x-b.oldPos.x,b.zoom.old.y=f.y-b.oldPos.y,window.requestAnimFrame(function(){b.draw()}),b.zoom.done=!0;return!1}b.newCursor=null;b.tools.mousemove(f);b.series.mousemove(f);b.legend.mousemove(f);b.title.mousemove(f);a=this.chart.canvas.style;b.newCursor?a.cursor!=b.newCursor&&(b.oldCursor=a.cursor,a.cursor=
b.newCursor):void 0!=b.oldCursor&&a.cursor!=b.oldCursor&&(a.cursor=b.oldCursor);return!0}};var g=new q(0,0);this.domousedown=function(a){var a=a||window.event,b=!1,c=this.chart;c.calcMouse(a.touches?a.touches[0]:a,g);var d=c.series.anyUsesAxes()&&c.chartRect.contains(g);a.touches?1<a.touches.length?(c.zoom.active=c.zoom.enabled&&d,c.zoom.active&&(c.scroll.active=!1)):(c.scroll.active=c.scroll.enabled&&d,c.scroll.active&&(c.zoom.active=!1)):(c.zoom.active=a.button==c.zoom.mouseButton&&c.zoom.enabled&&
d,c.scroll.active=a.button==c.scroll.mouseButton&&c.scroll.enabled&&d);c.zoom.done=!1;c.scroll.done=!1;c.oldPos=g;0==a.button&&((b=c.tools.mousedown(a))||(b=c.series.mousedown(a)));b?c.zoom.active=c.scroll.active=!1:b=c.zoom.active||c.scroll.active;b&&(a.preventDefault(),a.target.setCapture&&a.target.setCapture());return!b};this.domouseup=function(a){var a=a||window.event,b=this.chart,c;b.zoom.active=!1;b.scroll.active=!1;!b.zoom.done&&!b.scroll.done&&(b.canvas.oncontextmenu=null);if(b.zoom.done){b.zoom.apply();
if(b.onzoom)b.onzoom();b.draw();c=!0}else if(c=b.scroll.done,!c&&(c=b.series.clicked(b.oldPos),!c&&(c=b.tools.clicked(b.oldPos),!c&&(c=b.title.clicked(b.oldPos))&&b.title.onclick)))b.title.onclick(b.title);b.zoom.old=null;b.zoom.done=!1;b.scroll.done=!1;c&&a.preventDefault();a.target.releaseCapture&&a.target.releaseCapture()};h.onmousedown=h.ontouchstart=this.domousedown;h.onmouseup=h.ontouchstop=this.domouseup;h.onmousemove=h.ontouchmove=this.domousemove;h.onmouseout=function(a){a.target.setCapture||
(this.chart.scroll.active=!1)};this.addSeries=function(a){a.setChart(a,this);var b=this.series.items,c=b.indexOf(a);-1==c&&(c=b.push(a)-1);""==a.title&&(a.title="Series"+(1+c).toString());""==a.format.fill&&(a.format.fill=this.palette.get(c));return a};this.removeSeries=function(a){var b=this.series.items,a=b.indexOf(a);-1!=b&&b.splice(a,1)};h.chart=this;if(c&&0<c.length)if(c[0]instanceof Array)for(d=0;d<c.length;d++)b(c[d]);else b(c);this.getSeries=function(a){return this.series.items[a]};this.draw=
function(a){this.ctx=a||(this.canvas.getContext?this.canvas.getContext("2d"):null);if(!this.ctx)throw"Canvas does not provide Context";this.chartRect.setFrom(this.bounds);this.panel.draw();this.panel.margins.apply(this.chartRect);this.title.tryDraw(!0);this.footer.tryDraw(!1);this.series.beforeDraw();this.legend.visible&&(this.legend.calcrect(),this.legend.draw());var a=this.axes,b;a.visible&&this.series.anyUsesAxes()&&(a.each(u.adjustRect),a.each(u.calcRect),this.walls.visible&&(this.walls.back.bounds.setFrom(this.chartRect),
this.walls.draw()),0<a.transparency&&(b=this.ctx.globalAlpha,this.ctx.globalAlpha=(1-a.transparency)*b),a.each(u.draw),0<a.transparency&&(this.ctx.globalAlpha=b));this.series.draw();this.tools.draw();this.zoom.active&&this.zoom.draw();if(this.ondraw)this.ondraw(this)};this.toImage=function(a,b,c){if(a=document.getElementById(a))a.src=""!=b?this.canvas.toDataURL(b,c):this.canvas.toDataURL()}};Tee.CustomBar=function(d,c){Tee.Series.call(this,d,c);this.sideMargins=100;this.useOrigin=!0;this.origin=0;
this.marks.visible=!0;this.hover.enabled=!0;this.offset=0;this.barSize=70;this.barStyle="bar";var a=this.format;a.fill="";a.stroke.fill="black";a.shadow.visible=!0;a.round.x=4;a.round.y=4;a.gradient.visible=!0;this.stacked="no";this.drawBar=function(b){if("bar"==this.barStyle)a.rectPath(b.x,b.y,b.width,b.height);else if("line"==this.barStyle){var c;this.yMandatory?(c=b.x+0.5*b.width,a.rectPath(c,b.y,1,b.height)):(c=b.y+0.5*b.height,a.rectPath(b.x,c,b.width,1))}else a.ellipsePath(this.chart.ctx,b.x+
0.5*b.width,b.y+0.5*b.height,b.width,b.height)};this.countAll=function(a){var b=0,c=this.chart.series.items.length,d,e;for(d=0;d<c&&!(e=this.chart.series.items[d],e==this&&a);d++)e.visible&&e.constructor==this.constructor&&(b+=e.data.values.length);return b};var b=new q,e,h=new n,f={total:0,index:0};this._margin=0;this.calcBarOffset=function(a){this.countall="sideAll"==this.stacked?this.countAll(!0):0;var c;c="sideAll"==this.stacked?this.countAll():this.data.values.length;a/=c-1;"no"==this.stacked?
(a/=f.total,b.x=a*(1==f.total?-0.5:f.index-0.5*f.total),c=f.total):(b.x=0.5*-a,c=1);b.y=0.01*a*this.barSize;this._margin=0.5*c*b.y+0.0050*this.sideMargins*c*(a-b.y);b.x+=0.01*this.offset*a+0.5*(a-b.y)};this.calcStackPos=function(a,b){var c,d,f;this.isStacked?(this.calcStack(a,b,this.data.values[a]),c=this.pointOrigin(a,!1),f=this.mandatoryAxis,this.isStack100?(d=this.pointOrigin(a,!0),e=0==d?f.endPos:f.calc(100*c/d)):e=f.calc(c)):(this.calc(a,b),"sideAll"==this.stacked&&(d=this.notmandatory.calc(this.countall+
a),this.yMandatory?b.x=d:b.y=d))};this.draw=function(){var c=this.data.values.length;if(0<c){this.initOffsets();var d=new q,f=this.chart.ctx;this.hover.enabled||(a.stroke.prepare(),a.shadow.prepare(f));for(var k=0;k<c;k++){this.calcStackPos(k,d);this.calcBarBounds(d,h,b,e);this.drawBar(h);var l=this.hover.enabled&&this.over==k?this.hover:a;f.fillStyle=this.getFillStyle(h,this.getFill(k,l));this.hover.enabled&&l.shadow.prepare(f);f.fill();""!=l.stroke.fill&&(this.hover.enabled&&l.stroke.prepare(),
f.shadowColor="transparent",f.stroke(),l.shadow.visible&&(f.shadowColor=l.shadow.color))}}};this.calcColorEach=function(){this.chart.series.visibleCount(this,Tee.CustomBar,f);this.isColorEach="yes"==this.colorEach||"auto"==this.colorEach&&1==f.total};this.initOffsets=function(){var a=this.notmandatory,b=this.mandatoryAxis,c=this.yMandatory?this.maxXValue()-this.minXValue():this.maxYValue()-this.minYValue();this.calcBarOffset(a.calcSize(c));e=this.useOrigin?b.calc(this.origin):this.yMandatory?b.inverted?
b.startPos:b.endPos:b.inverted?b.endPos:b.startPos;this.isStacked="no"!=this.stacked&&"sideAll"!=this.stacked;this.isStack100="100"==this.stacked};this.clicked=function(a){this.initOffsets();var c=new q,d=this.data.values.length,f;for(f=0;f<d;f++)if(this.calcStackPos(f,c),this.calcBarBounds(c,h,b,e),h.contains(a))return f;return-1};this.drawMarks=function(){var a=this.data.values,c=a.length,d=this.marks;if(0<c){var e=new q,f=this.mandatoryAxis,h,n;n=b.x+0.5*b.y;this.yMandatory?(h=n,n=0):h=0;for(var p=
0;p<c;p+=d.drawEvery){this.calcStackPos(p,e);if("sideAll"==this.stacked){var r=this.notmandatory.calc(this.countall+p);this.yMandatory?e.x=r:e.y=r}r=this.useOrigin&&a[p]<this.origin;f.inverted&&(r=!r);d.drawMark(e.x+h,e.y+n,p,r)}}};this.labelOrTitle=function(a){var b=this.title,c=this.data.labels[a];return 1<f.total?b||c:this.parent.labelOrTitle(a)}};Tee.CustomBar.prototype=new Tee.Series;Tee.CustomBar.prototype.parent=Tee.Series.prototype;Tee.CustomBar.constructor=Tee.CustomBar;Tee.Bar=function(d,
c){Tee.CustomBar.call(this,d,c);this.calc=function(a,b){this.isStacked?this.calcStack(a,b,this.data.values[a]):this.parent.calc.call(this,a,b)};this.horizMargins=function(a){this.initOffsets();a.x=this._margin;a.y=this._margin};this.vertMargins=function(a){var b=this.marks,c=this.format.stroke,d=this.minYValue()<this.origin;b.visible&&(a.y=b.arrow.length+b.format.textHeight("Wj")+b.margins.top+b.margins.bottom,c=b.format.stroke);""!=c.fill&&(a.y+=2*c.size+1);d&&(a.x=a.y)};this.maxXValue=function(){return"sideAll"==
this.stacked?this.countAll()-1:this.parent.maxXValue.call(this)};this.minYValue=function(){var a=this.parent.minYValue.call(this);return this.useOrigin?Math.min(this.origin,a):a};this.maxYValue=function(){return this.stackMaxValue()};this.calcBarBounds=function(a,b,c,d){b.x=a.x+c.x;b.width=c.y;this._vertAxis.inverted?(b.y=d,b.height=a.y-b.y):(b.y=a.y,b.height=d-a.y);0>b.height&&(b.y+=b.height,b.height=-b.height)}};Tee.Bar.prototype=new Tee.CustomBar;Tee.Bar.prototype.parent=Tee.CustomBar.prototype;
Tee.HorizBar=function(d,c){Tee.CustomBar.call(this,d,c);this.yMandatory=!1;this.format.gradient.direction="rightleft";this.maxMarkWidth=function(){var a=0,b,c,d;if(this.marks.visible){b=this.marks.format;b.font.prepare();for(c=this.count();c--;)d=b.textWidth(this.markText(c)),d>a&&(a=d)}return a};this.horizMargins=function(a){if(this.marks.visible){var b=this.marks.arrow.length+this.maxMarkWidth();a.y=b;this.minXValue()<this.origin&&(a.x=b)}};this.vertMargins=function(a){this.initOffsets();a.x+=this._margin;
a.y+=this._margin};this.maxYValue=function(){return"sideAll"==this.stacked?this.countAll()-1:this.parent.maxXValue.call(this)};this.minYValue=function(){return"sideAll"==this.stacked?0:this.parent.minXValue.call(this)};this.minXValue=function(){var a=this.parent.minYValue.call(this);return this.useOrigin?Math.min(this.origin,a):a};this.maxXValue=function(){return this.stackMaxValue()};this.calcBarBounds=function(a,b,c,d){b.y=a.y+c.x;b.height=c.y;this._horizAxis.inverted?(b.x=a.x,b.width=d-a.x):(b.x=
d,b.width=a.x-b.x);0>b.width&&(b.x+=b.width,b.width=-b.width)}};Tee.HorizBar.prototype=new Tee.CustomBar;Tee.HorizBar.prototype.parent=Tee.CustomBar.prototype;Tee.CustomSeries=function(d,c){Tee.Series.call(this,d,c);this.stacked="no";this.stairs=!1;this.hover.enabled=!0;this.isStack100=this.isStacked=this.hover.line=!1;this.smooth=0;this.pointer=new function(a){this.setChart=function(a){this.chart=a;this.format.setChart(a)};this.chart=a;a=this.format=new Tee.Format(a);a.shadow.visible=!1;a.fill="";
a.gradient.colors=["white","white","white"];a.gradient.visible=!0;a.shadow.visible=!0;this.colorEach=this.visible=!1;this.style="rectangle";this.height=this.width=12;this.draw=function(a,c,d,f){var g=this.chart.ctx;this.transform&&(g.save(),this.transform(a.x,a.y,c));var c=0.5*this.width,i=0.5*this.height;"rectangle"==this.style?d.rectangle(a.x-c,a.y-i,this.width,this.height):"ellipse"==this.style?d.ellipse(a.x,a.y,this.width,this.height):"triangle"==this.style?d.polygon([new q(a.x,a.y-i),new q(a.x-
c,a.y+i),new q(a.x+c,a.y+i)]):"downtriangle"==this.style?d.polygon([new q(a.x,a.y+i),new q(a.x-c,a.y-i),new q(a.x+c,a.y-i)]):"diamond"==this.style?d.polygon([new q(a.x,a.y-i),new q(a.x-c,a.y),new q(a.x,a.y+i),new q(a.x+c,a.y)]):(g.beginPath(),"cross"==this.style&&(g.moveTo(a.x-c,a.y),g.lineTo(a.x+c,a.y),g.moveTo(a.x,a.y-i),g.lineTo(a.x,a.y+i)),"x"==this.style&&(g.moveTo(a.x-c,a.y-i),g.lineTo(a.x+c,a.y+i),g.moveTo(a.x-c,a.y+i),g.lineTo(a.x+c,a.y-i)),d.stroke.prepare(f),g.stroke());this.transform&&
g.restore()}}(this.chart);this.maxYValue=function(){return this.stackMaxValue()};this.calc=function(a,b){this.isStacked?this.calcStack(a,b,this.data.values[a]):Tee.Series.prototype.calc.call(this,a,b)};this.calcColorEach=function(){this.isColorEach="yes"==this.colorEach||this.pointer.colorEach}};Tee.CustomSeries.prototype=new Tee.Series;Tee.CustomSeries.prototype.drawPointers=function(){var d=this.data.values.length,c,a=this.pointer.format,b="yes"==this.colorEach||this.pointer.colorEach;!b&&""==a.fill&&
(a.fill=this.format.fill);var e=new q,h=a.gradient,f,g=a.fill;c=g;!b&&h.visible&&h.setEndColor(g);for(f=0;f<d;f++)this.calc(f,e),g=this.getFill(f,a),g!=c&&(h.visible?h.setEndColor(g):a.fill=g,c=g),this.getSize(f),this.pointer.draw(e,f,a,g),this.hover.enabled&&this.over==f&&this.pointer.draw(e,f,this.hover,g);b&&(a.fill=c)};Tee.CustomSeries.prototype.setChart=function(d,c){var a=Tee.Series.prototype.setChart;a(d,c);d.pointer.setChart(c)};Tee.CustomSeries.prototype.clicked=function(d){var c=new q,a=
new q,b=this.data.values.length,e;if(this.drawLine&&0<b&&(this.hover.line||!this.pointer.visible)){this.calc(0,c);for(e=1;e<b;e++){this.calc(e,a);if(G(d,c,a,3))return e;c.x=a.x;c.y=a.y}}if(this.pointer.visible){c=new n;a=this.pointer;for(e=0;e<b;e++)if(this.calc(e,c),this.getSize(e),c.x-=0.5*a.width,c.width=a.width,c.y-=0.5*a.height,c.height=a.height,c.contains(d))return e}return-1};Tee.CustomSeries.prototype.horizMargins=function(d){var c=this.pointer,a=c.format.stroke;c.visible&&(d.x=d.y=(""!=a.fill?
a.size:0)+1+0.5*c.width)};Tee.CustomSeries.prototype.vertMargins=function(d){var c=this.pointer,a=c.format.stroke;c.visible&&(d.x=d.y=(""!=a.fill?a.size:0)+1+0.5*c.height)};Tee.CustomSeries.prototype.getSize=function(){};Tee.Line=function(d,c){Tee.CustomSeries.call(this,d,c);this.drawLine=!0;var a=this.format;a.shadow.visible=!0;a.shadow.blur=10;a.lineCap="round";this.doDrawLine=function(b){this.isStacked="no"!=this.stacked;this.isStack100="100"==this.stacked;var c=new q,d,f=this.data.values.length,
g,i=0,j=f;g=this.notmandatory;!this.smooth&&!this.data.x&&(i=Math.max(0,(g.minimum|0)-1),j=Math.min(f,(g.maximum|0)+2));b.beginPath();if(0<this.smooth){d=Array(2*f);for(g=0;g<f;g++)this.calc(g,c),d[2*g]=c.x,d[2*g+1]=c.y;drawSpline(b,d,this.smooth,!0)}else for(g=i;g<j;g++)this.calc(g,c),g==i?b.moveTo(c.x,c.y):(this.stairs&&b.lineTo(d,c.y),b.lineTo(c.x,c.y)),d=c.x;f=a.stroke;this.chart.isChrome&&a.shadow.visible&&(f.size=Math.max(1.1,f.size));c=f.fill;f.prepare(""==c?a.fill:c);a.shadow.prepare(b);b.stroke()};
this.draw=function(){0<this.data.values.length&&(this.drawLine&&this.doDrawLine(this.chart.ctx),this.pointer.visible&&this.drawPointers())}};Tee.Line.prototype=new Tee.CustomSeries;Tee.PointXY=function(d,c){Tee.Line.call(this,d,c);this.hover.enabled=!0;this.pointer.visible=!0;this.drawLine=!1};Tee.PointXY.prototype=new Tee.Line;Tee.Series.prototype.cellRect=function(d,c,a){var b={total:0,index:-1};d.setFrom(this.chart.chartRect);this.chart.series.visibleCount(this,a,b);if(c&&1<b.total){c=Math.round(Math.sqrt(b.total));
a=Math.round(b.total/c);if(d.width>d.height)var e=c,c=a,a=e;d.width/=c;d.x+=1.03*(b.index%c)*d.width;d.height/=a;d.y+=1.03*(b.index/c|0)*d.height;d.width*=0.94;d.height*=0.94}return d};Tee.Pie=function(d,c){function a(a,b){b.x=j.x+Math.cos(a)*i;b.y=j.y+Math.sin(a)*i}Tee.Series.call(this,d,c);this.marks.style="percent";this.rotation=this.donut=0;this.colorEach="yes";this.useAxes=!1;var b=this.format;b.stroke.fill="black";b.shadow.visible=!0;b.gradient.visible=!0;b.gradient.direction="radial";b.gradient.colors=
["white","white","white"];this.hover.enabled=!0;this.sort="values";this.orderAscending=!1;this.explode=null;this.marks.visible=!0;this.concentric=!1;this.getValue=function(a){return this.data.values[a]};this.calcCenter=function(a,b,c,d){if(this.explode&&(a=this.explode[a]))a=0.01*b*a,d.x+=a*Math.cos(c),d.y+=a*Math.sin(c)};this.clicked=function(a){var b=this.chart.ctx,c=this.data.values.length,d,e;m=l=Math.PI*this.rotation/180;for(d=0;d<c;d++)if(e=k?k[d]:d,this.slice(b,e),b.isPointInPath(a.x,a.y))return e;
return-1};var e,h,f,g,i,j={x:0,y:0},k,l,m,v;this.slice=function(b,c){var d=new q;m+=2*Math.PI*(Math.abs(this.data.values[c])/e);j.x=h;j.y=f;this.calcCenter(c,g,0.5*(l+m),j);0==this.donut?(d.x=j.x,d.y=j.y):a(l,d);b.beginPath();b.moveTo(d.x,d.y);b.arc(j.x,j.y,g,l,m,!1);0!=this.donut&&a(m,d);b.lineTo(d.x,d.y);0!=this.donut&&b.arc(j.x,j.y,i,m,l,!0);b.closePath();c==this.over&&(v=l);l=m};this.fill=function(a){return this.getFillStyle(this.chart.chartRect,this.getFill(a))};this.slices=function(a){var c=
this.chart.ctx,d=this.data.values.length,e,f;m=l=Math.PI*this.rotation/180;for(e=0;e<d;e++)f=k?k[e]:e,this.slice(c,f),a?b.shadow.prepare(c):c.fillStyle=this.fill(f),c.fill(),a||(f=b.stroke,""!=f.fill&&(f.prepare(),c.stroke()))};var p=new n;this.draw=function(){if(0<this.data.values.length){var a=0,c=this.marks;b.shadow.visible&&(a+=2*b.shadow.height);c.visible&&(c.format.font.prepare(),a+=c.format.textHeight("Wj")+0.5*c.arrow.length);this.cellRect(p,!this.concentric,Tee.Pie);h=p.x+0.5*p.width;f=p.y+
0.5*p.height;g=0.5*p.width;a=0.5*(p.height-2*a);a<g&&(g=a);i=0.01*g*this.donut;for(var a=this.data.values,c=0,d=a.length;d--;)c+=0<a[d]?a[d]:-a[d];e=c;k=this.doSort(this.sort,this.orderAscending);this.slices(!0);this.slices(!1);this.hover.enabled&&-1!=this.over&&(a=this.hover,""!=a.stroke.fill&&(m=l=v,c=this.chart.ctx,this.slice(c,this.over),c.fillStyle=this.fill(this.over),a.draw(c,null,p.x,p.y,p.width,p.height)))}};this.drawMarks=function(){var a=l=Math.PI*this.rotation/180,b,c=this.data.values,
d=c.length,i,m;for(m=0;m<d;m+=this.marks.drawEvery)i=k?k[m]:m,a+=2*Math.PI*(c[i]/e),b=0.5*(l+a),j.x=h,j.y=f,this.calcCenter(m,g,b,j),this.marks.drawPolar(j,g,b,i),l=a}};Tee.Pie.prototype=new Tee.Series;Tee.Area=function(d,c){Tee.CustomSeries.call(this,d,c);this.useOrigin=!1;this.origin=0;this.drawLine=!0;var a=this.format;a.shadow.visible=!0;a.lineCap="round";a.stroke.fill="black";a.fill="";var b=new n;this.draw=function(){var c=this.data.values.length;if(0<c){var d=this.mandatoryAxis,f=this.notmandatory,
g,i=this.yMandatory;g=this.useOrigin?d.calc(this.origin):i&&d.inverted||!i&&!d.inverted?d.startPos:d.endPos;this.isStacked="no"!=this.stacked;this.isStack100="100"==this.stacked;var j=new q,k,l,d=this.chart.ctx,m,n=this.isStacked,p=0,r=c;!this.smooth&&!this.data.x&&(p=Math.max(0,(f.minimum|0)-1),r=Math.min(c,(f.maximum|0)+2));d.beginPath();if(0<this.smooth){m=Array(2*c);for(l=0;l<c;l++)this.calc(l,j),m[2*l]=j.x,m[2*l+1]=j.y;f=i?m[0]:m[1];drawSpline(d,m,this.smooth,!0);if(n){var s=0;for(l=c-1;0<=l;l--)this.calcStack(l,
j,0),m[s++]=j.x,m[s++]=j.y;d.lineTo(m[0],m[1]);drawSpline(d,m,this.smooth,!1)}}else if(this.calc(p,j),d.moveTo(j.x,j.y),f=i?j.x:j.y,k=i?j.y:j.x,this.stairs)for(l=p+1;l<r;l++)this.calc(l,j),d.lineTo(j.x,k),d.lineTo(j.x,j.y),k=i?j.y:j.x;else for(l=p+1;l<r;l++)this.calc(l,j),d.lineTo(j.x,j.y);if(n){if(0==this.smooth)for(l=r-1;l>=p;l--)this.calcStack(l,j,0),this.stairs?(d.lineTo(j.x,k),d.lineTo(j.x,j.y),k=i?j.y:j.x):d.lineTo(j.x,j.y)}else i?(d.lineTo(j.x,g),d.lineTo(f,g)):(d.lineTo(g,j.y),d.lineTo(g,
f));d.closePath();c=a.gradient;c.visible&&(c.colors[c.colors.length-1]=a.fill);this.bounds(b);a.draw(d,null,b.x,b.y,b.width,b.height);this.pointer.visible&&this.drawPointers()}};this.minYValue=function(){var a=this.yMandatory?Tee.Series.prototype.minYValue.call(this):Tee.Series.prototype.minXValue.call(this);return this.yMandatory?this.useOrigin?Math.min(a,this.origin):a:a};this.minXValue=function(){var a=this.yMandatory?Tee.Series.prototype.minXValue.call(this):Tee.Series.prototype.minYValue.call(this);
return this.yMandatory?a:this.useOrigin?Math.min(a,this.origin):a};this.maxYValue=function(){return this.yMandatory?this.stackMaxValue():Tee.Series.prototype.maxXValue.call(this)};this.maxXValue=function(){return this.yMandatory?Tee.Series.prototype.maxXValue.call(this):this.stackMaxValue()}};Tee.Area.prototype=new Tee.CustomSeries;Tee.HorizArea=function(d,c){Tee.Area.call(this,d,c);this.yMandatory=!1};Tee.HorizArea.prototype=new Tee.Area;Tee.Donut=function(d,c){Tee.Pie.call(this,d,c);this.donut=
50};Tee.Donut.prototype=new Tee.Pie;Tee.Gantt=function(d,c){Tee.Series.call(this,d,c);this.yMandatory=!1;this.dateFormat="mediumDate";this.hover.enabled=!0;this.hover.round.x=this.hover.round.y=8;this.colorEach="yes";this.data.start=this.data.values;this.data.x=[];this.data.end=[];this.height=70;this.margin=new q(6,6);var a=this.format;a.shadow.visible=!0;a.round.x=a.round.y=8;a.stroke.fill="black";a.gradient.visible=!0;var b=new n,e;this.addRandom=function(a){var b=this.data;b.x.length=a;b.start.length=
a;b.end.length=a;if(0<a)for(var c,d,e=0;e<a;e++)b.x[e]=e,c=12*Math.random()|0,d=10*Math.random()|0,b.start[e]=new Date(2012,c,d),5>c&&(c=5+(7*Math.random()|0)),b.end[e]=new Date(2012,c,d+10*Math.random())};this.bounds=function(a,b){this.calc(a,b);b.y-=0.5*e;b.width=this.data.end?this.mandatoryAxis.calcSize(this.data.end[a]-this.data.start[a]):0;b.height=e};this.add=function(a,b,c,d){var e=this.data;e.labels.push(b);e.x.push(a);e.start.push(c);e.end.push(d)};this.clicked=function(a){var c=this.data.values.length,
d;for(d=0;d<c;d++)if(this.bounds(d,b),b.contains(a))return d;return-1};this.draw=function(){var c=this.data.values.length,d,g;e=this.notmandatory.calcSize(0.01*this.height);for(d=0;d<c;d++)this.bounds(d,b),g=this.hover.enabled&&this.over==d?this.hover:a,this.chart.ctx.fillStyle=this.getFillStyle(b,this.getFill(d,g)),g.rectangle(b)};this.horizMargins=function(a){a.x=this.margin.x;a.y=this.margin.y};this.minYValue=function(){return this.parent.minXValue.call(this)-0.5};this.maxYValue=function(){return this.parent.maxXValue.call(this)+
0.5};this.minXValue=function(){return Math.min.apply({},this.data.start)};this.maxXValue=function(){return Math.max.apply({},this.data.end)}};Tee.Gantt.prototype=new Tee.Series;Tee.Gantt.prototype.parent=Tee.Series.prototype;Tee.Bubble=function(d,c){Tee.PointXY.call(this,d,c);var a=this.pointer;a.colorEach=!0;a.style="ellipse";a.format.gradient.visible=!0;a.format.gradient.direction="radial";this.addRandom=function(a){var c=this.data;c.values.length=a;c.radius.length=a;if(0<a)for(var d=0;d<a;d++)c.values[d]=
1E3*Math.random(),c.radius[d]=100*Math.random()}};Tee.Bubble.prototype=new Tee.PointXY;Tee.Bubble.prototype.getSize=function(d){d=this.data.radius?this._vertAxis.calcSize(this.data.radius[d]):0;this.pointer.width=d;this.pointer.height=d};Tee.Bubble.prototype.horizMargins=function(d){this.calcWidth=function(c){this.getSize(c);var c=1+0.5*this.pointer.width,a=this.pointer.format.stroke;""!=a.fill&&(c+=a.size);return c};this.pointer.visible&&(d.x=this.calcWidth(0),d.y=this.calcWidth(this.count()-1))};
Tee.Bubble.prototype.vertMargins=function(d){this.calcHeight=function(c){this.getSize(c);var c=1+0.5*this.pointer.height,a=this.pointer.format.stroke;""!=a.fill&&(c+=a.size);return c};this.pointer.visible&&(d.x=this.calcHeight(0),d.y=this.calcHeight(this.count()-1))};Tee.Volume=function(d,c){Tee.Bar.call(this,d,c);this.barStyle="line";this.colorEach=this.marks.visible=!1;var a=this.format;a.shadow.visible=!1;a.gradient.visible=!1;a.stroke.fill=""};Tee.Volume.prototype=new Tee.Bar;Tee.Candle=function(d,
c){Tee.PointXY.call(this,d,c);this.pointer.width=7;this.pointer.format.stroke.visible=!1;this.higher=this.pointer.format;this.higher.fill="green";this.lower=new Tee.Format(this.chart);this.lower.fill="red";this.lower.stroke.visible=!1;this.style="candle";this.setChart=function(a,b){var c=Tee.PointXY.prototype.setChart;c(a,b);this.lower.setChart(b)};this.draw=function(){var a=this.data,b=a.values.length,c,d=new q,f=this.pointer,g=0.5*f.width,i,j,k,l=this.mandatoryAxis,m,n,p=this.chart.ctx,r,s;for(c=
0;c<b;c++)if(this.calc(c,d),s=d.x,i=l.calc(a.open[c]),j=l.calc(a.high[c]),k=l.calc(a.low[c]),d.y>i?(m=i,n=d.y-i,r=this.lower):(m=d.y,n=i-m,r=this.higher),"bar"==this.style?(p.beginPath(),p.moveTo(s,j),p.lineTo(s,k),p.moveTo(s-g,i),p.lineTo(s,i),p.moveTo(s,d.y),p.lineTo(s+g,d.y),r.stroke.prepare(r.fill),p.stroke()):this.hover.enabled&&this.over==c?this.hover.rectangle(s-g,m,f.width,n):r.rectangle(s-g,m,f.width,n),"openclose"!=this.style&&(j<m||k>m+n))p.beginPath(),p.moveTo(s,m),p.lineTo(s,j),p.moveTo(s,
m+n),p.lineTo(s,k),this.hover.enabled&&this.over==c?this.hover.stroke.prepare(r.fill):r.stroke.prepare(r.fill),p.stroke()};this.minYValue=function(){return 0<this.data.low.length?Math.min.apply({},this.data.low):0};this.maxYValue=function(){return 0<this.data.high.length?Math.max.apply({},this.data.high):0};this.addRandom=function(a){var b=this.data;b.values.length=a;b.close=b.values;b.open?b.open.length=a:b.open=Array(a);b.high?b.high.length=a:b.high=Array(a);b.low?b.low.length=a:b.low=Array(a);
if(0<a)for(var c=25+100*Math.random(),d,f=0;f<a;f++)d=b.open[f]=c,c=b.close[f]=c+25*Math.random()-12.5,b.high[f]=Math.max(d,c)+15*Math.random(),b.low[f]=Math.min(d,c)-15*Math.random()}};Tee.Candle.prototype=new Tee.PointXY;Tee.Candle.prototype.clicked=function(d){var c=this.pointer.width,a=this.mandatoryAxis,b=this.notmandatory,e=this.data,h=e.values.length,f=new n,g,i,j;f.width=c;for(g=0;g<h;g++)if(f.x=b.calc(g)-0.5*c,i=a.calc(e.open[g]),j=a.calc(e.close[g]),f.y=i>j?j:i,f.height=Math.abs(i-j),f.contains(d))return g;
return-1};Tee.Candle.prototype.vertMargins=function(){}}).call(this);
