/*
 TeeChart(tm) for JavaScript(tm)
 @fileOverview TeeChart for JavaScript(tm)
 v2.7 Apr 2021
 Copyright(c) 2012-2021 by Steema Software SL. All Rights Reserved.
 http://www.steema.com

 Licensed with commercial and non-commercial attributes,
 specifically: http://www.steema.com/licensing/html5

 JavaScript is a trademark of Oracle Corporation.
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function a(e){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(e||"")+"_"+b++,e)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,b){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var e=0,d={next:function(){if(e<a.length){var f=e++;return{value:b(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
var $jscomp$lookupPolyfilledValue=function(a,b){var e=$jscomp.propertyToPolyfillSymbol[b];if(null==e)return a[b];e=a[e];return void 0!==e?e:a[b]};$jscomp.polyfill=function(a,b,e,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,e,d):$jscomp.polyfillUnisolated(a,b,e,d))};
$jscomp.polyfillUnisolated=function(a,b,e,d){e=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in e||(e[f]={});e=e[f]}a=a[a.length-1];d=e[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,e,d){var f=a.split(".");a=1===f.length;d=f[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var A=0;A<f.length-1;A++){var B=f[A];B in d||(d[B]={});d=d[B]}f=f[f.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?d[f]:null;b=b(e);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==e&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+f,f=$jscomp.propertyToPolyfillSymbol[f],
$jscomp.defineProperty(d,f,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.values",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(b,a){return a})}},"es8","es3");$jscomp.polyfill("Array.prototype.fill",function(a){return a?a:function(b,a,d){var f=this.length||0;0>a&&(a=Math.max(0,f+a));if(null==d||d>f)d=f;d=Number(d);0>d&&(d=Math.max(0,f+d));for(a=Number(a||0);a<d;a++)this[a]=b;return this}},"es6","es3");var Tee=Tee||{};
(function(){"undefined"!==typeof exports&&(exports.Tee=Tee);Tee.ColorGrid=function(a,e){Tee.PaletteSeries.call(this,a,e);this.dataChanged=this.smooth=!0;var b,f,A,B,u,k,v,y,x,h,p,g,n,D,m,w,C;this.addRandom=function(a,b){a=a||200;b=b||a;for(var f=this.data.values=[],d=0;d<a;d++){var e=Array(b);f[d]=e;var h=Math.cos(d/(.2*b));h*=.5*h;for(var g=0;g<b;g++){var z=Math.cos(g/(.2*a));e[g]=z*z-Math.cos(g/(.5*b))+h}}this.dataChanged=!0};this.fillPixels=function(a){for(var d=0,g,h,e=this.palette.grayScale,
z=this.palette.inverted,k=0;k<A;k++){g=b[k];for(var n=0;n<f;n++)e?(h=C*(z?m-g[n]:g[n]-D),u[d++]=h,u[d++]=h,u[d++]=h):(h=this.getColor(g[n]),u[d++]=h.r,u[d++]=h.g,u[d++]=h.b),u[d++]=a}};this.draw=function(){var a=this.chart.ctx;if(0<f){if(!B||k.width!=f||k.height!=A){k||(k=document.createElement("canvas"));if(!k||!k.getContext)return;k.width=f;k.height=A;v=k.getContext("2d");B=v.getImageData(0,0,f,A);u=B.data}this.dataChanged&&(this.fillPixels(255*(1-this.format.transparency)),this.dataChanged=!1);
v.putImageData(B,0,0);var b=this.smooth,d=this.chart.canvas.style;d&&(null!==d.getPropertyValue("image-rendering")&&d.setProperty("image-rendering",b?"optimizeQuality":"optimizeSpeed",null),void 0!==d.msInterpolationMode&&(d.msInterpolationMode=b?"bicubic":"nearest-neighbor"));a.imageSmoothingEnabled=b;y=this.mandatoryAxis;x=this.notmandatory;n=y.calc(-.5);p=y.calc(A-.5);h=x.calc(-.5);g=x.calc(f-.5);b=h;d=p;var e=1,m=1;y.inverted&&(m=-1,d=-n);x.inverted&&(e=-1,b=-g);a.scale(e,m);a.drawImage(v.canvas,
0,0,f,A,b,d,g-h,n-p);b=this.format.stroke;if(""!==b.fill){var w=Math.max(1+4*f/Math.abs(x.calc(f)-x.calc(0))|0,1);e=Math.max(1+4*A/Math.abs(y.calc(A)-y.calc(0))|0,1);a.beginPath();for(m=1;m<f;m+=w)d=x.calc(m-.5),a.moveTo(d,n),a.lineTo(d,p);for(m=1;m<A;m+=e)d=y.calc(m-.5),a.moveTo(h,d),a.lineTo(g,d);b.prepare();a.stroke()}}};this.valueText=function(a){return this.data.values[a/f|0][a%f].toFixed(this.decimals)};this.minXValue=function(){return-.5};this.maxXValue=function(){return f-.5};this.minYValue=
function(){return-.5};this.maxYValue=function(){return A-.5};this.recalcAxes=function(){Tee.Series.prototype.recalcAxes.call(this);b=this.data.values;A=b.length;f=0<A?b[0].length:0;this.size={x:f,y:A};if(0<f&&this.dataChanged){m=D=b[0][0];for(var a,d,h=0;h<A;h++){d=b[h];for(var e=0;e<f;e++)a=d[e],a<D?D=a:a>m&&(m=a)}w=m-D;C=m==D?1:255/(m-D);this._min=D;this._max=m;this._range=w;this.prepareColors()}};this.clicked=function(a){if(a.x>=h&&a.x<=g){var b=f*(a.x-h)/(g-h)|0;if(a.y>=p&&a.y<=n)return a=A*(a.y-
p)/(n-p)|0,a*f+b}return-1}};Tee.ColorGrid.prototype=new Tee.PaletteSeries;Tee.Surface=function(a,e){Tee.ColorGrid.call(this,a,e);var b;this.grid=(new Tee.Format(a)).stroke;this.wireFrame=!1;this.maxZ=3;this.getY=function(a,d){return b[a][d]};this.draw=function(){if(0<this.size.x&&0<this.size.y&&(b=this.data.values,this.chart.__webgl)){var a={};this.bounds(a);this.chart.ctx.surface(this.size,this.getY,a,this.wireFrame,this.grid.visible?this.grid.fill:null,this.maxZ)}};this.minXValue=function(){return 0};
this.maxXValue=function(){return this.size.y};this.minYValue=function(){return this._min};this.maxYValue=function(){return this._max}};Tee.Surface.prototype=new Tee.ColorGrid;THREE.SubdivisionModifier=function(a){this.subdivisions=void 0===a?1:a};THREE.SubdivisionModifier.prototype.modify=function(a){for(var b=this.subdivisions;0<b--;)this.smooth(a);delete a.__tmpVertices;a.computeFaceNormals();a.computeVertexNormals()};(function(){function a(a,b,d){return d[Math.min(a,b)+"_"+Math.max(a,b)]}function e(a,
b,d,e,k,v){var f=Math.min(a,b),A=Math.max(a,b),h=f+"_"+A;h in e?d=e[h]:(d={a:d[f],b:d[A],newEdge:null,faces:[]},e[h]=d);d.faces.push(k);v[a].edges.push(d);v[b].edges.push(d)}var d=["a","b","c"];THREE.SubdivisionModifier.prototype.smooth=function(b){var f=new THREE.Vector3,B,u;var k=b.vertices;var v=b.faces;var y=Array(k.length);var x={};var h=0;for(u=k.length;h<u;h++)y[h]={edges:[]};h=0;for(u=v.length;h<u;h++){var p=v[h];e(p.a,p.b,k,x,p,y);e(p.b,p.c,k,x,p,y);e(p.c,p.a,k,x,p,y)}u=[];for(z in x){h=
x[z];var g=new THREE.Vector3;p=.375;var n=.125;var D=h.faces.length;2!=D&&(p=.5,n=0);g.addVectors(h.a,h.b).multiplyScalar(p);f.set(0,0,0);for(p=0;p<D;p++){var m=h.faces[p];for(B=0;3>B;B++){var w=k[m[d[B]]];if(w!==h.a&&w!==h.b)break}f.add(w)}f.multiplyScalar(n);g.add(f);h.newEdge=u.length;u.push(g)}var C;m=[];var z=0;for(h=k.length;z<h;z++){B=k[z];D=y[z].edges;g=D.length;3==g?C=.1875:3<g&&(C=3/(8*g));w=1-g*C;n=C;2>=g&&2==g&&(w=.75,n=.125);var L=B.clone().multiplyScalar(w);f.set(0,0,0);for(p=0;p<g;p++)w=
D[p],w=w.a!==B?w.a:w.b,f.add(w);f.multiplyScalar(n);L.add(f);m.push(L)}f=m.concat(u);y=m.length;k=[];z=0;for(h=v.length;z<h;z++)m=v[z],C=a(m.a,m.b,x).newEdge+y,w=a(m.b,m.c,x).newEdge+y,u=a(m.c,m.a,x).newEdge+y,k.push(new THREE.Face3(C,w,u)),k.push(new THREE.Face3(m.a,C,u)),k.push(new THREE.Face3(m.b,w,C)),k.push(new THREE.Face3(m.c,u,w));b.vertices=f;b.faces=k}})();Tee.MyParametricGeometry=function(a,e,d,f){THREE.Geometry.call(this);var b=this.vertices,B=this.faces,u=this.faceVertexUvs[0];f=void 0===
f?!1:f;var k,v,y=e+1,x=1/e,h=1/y,p=1/d,g=1/(d+1);for(k=0;k<=d;k++)for(v=0;v<=e;v++)b.push(new THREE.Vector3(k*p-.5,a(k,v),.5-v*x));for(k=0;k<d;k++){var n=k*g;var D=(k+1)*g;var m=k*y;var w=(k+1)*y;for(v=0;v<e;v++){a=m+v;b=w+v;var C=v*h;var z=C+h;x=new THREE.Vector2(C,n);p=new THREE.Vector2(z,n);C=new THREE.Vector2(C,D);var L=new THREE.Vector2(z,D);if(f){z=a+1;var O=b+1;B.push(new THREE.Face3(a,z,b));B.push(new THREE.Face3(z,O,b));u.push([x,p,C]);u.push([p,L,C])}else B.push(new THREE.Face4(a,a+1,b+
1,b)),u.push([x,p,L,C])}}this.computeFaceNormals();this.computeVertexNormals()};"undefined"!==typeof THREE&&(Tee.MyParametricGeometry.prototype=new THREE.Geometry);var a="undefined"!==typeof HTMLCanvasElement;Tee.Three=function(b){function e(c,a,G,b,d,l,f,e){c&&(a=new THREE.MeshBasicMaterial({vertexColors:THREE.VertexColors}),a.wireframe=c);a.vertexColors=THREE.VertexColors;c||(a.side=THREE.DoubleSide);c=new THREE.Mesh(d,a);d=e-f;e===f&&(d=1);e=b.height/d;c.position.set(b.x+.5*(b.width-F),b.y+.5*
(b.height-E)-(f+.5*d)*e,.5*-h);c.scale.set(b.width,e,h*l);n.add(c)}function d(c){M.extrudeOptions.amount=h*M.depth;c=0==M.depth?new THREE.ShapeGeometry(c):c.extrude(M.extrudeOptions);c=THREE.SceneUtils.createMultiMaterialObject(c,[M.getMaterial()]);M.showShadows&&(c.receiveShadow=!0,c.castShadow=!0);return c}function f(c,a,G,b,d,l){c.moveTo(a,G+l);c.lineTo(a,G+d-l);c.quadraticCurveTo(a,G+d,a+l,G+d);c.lineTo(a+b-l,G+d);c.quadraticCurveTo(a+b,G+d,a+b,G+d-l);c.lineTo(a+b,G+l);c.quadraticCurveTo(a+b,
G,a+b-l,G);c.lineTo(a+l,G);c.quadraticCurveTo(a,G,a,G+l)}function A(c){if("rgb("==c.substr(0,4))return c=c.slice(4,c.length-1).split(","),c[2]|c[1]<<8|c[0]<<16;switch(c){case "white":return 16777215;case "silver":return 14737632;case "darkgray":case "darkgrey":return 8421504;case "black":return 0;case "red":return 16711680;case "green":return 65280;case "blue":return 255;default:return 16777215}}function B(c,a){var r,b=P.length;for(r=0;r<b;r++){var d=P[r];if(d.text===c&&d.size===a)return d.obj}return null}
function u(c,a){var r=J;r.width=c;r.height=a;t.setSize(c,a);H.aspect=c/a;H.updateProjectionMatrix()}function k(){y?(u(x.width,x.height),y=!1):(x.width=J.width,x.height=J.height,u(window.innerWidth,window.innerHeight),y=!0);M.refresh()}this.setEnabled=function(c,r){if(!c||!Detector||Detector.webgl){if(this.__webgl=c)t&&(r.__webgl=!0,r.canvas.style.display="none",r.canvas=this,r.ctx=this,t&&t.domElement&&(t.domElement.style.display="block"));else{var b=J;g||(a?(g=document.createElement("canvas"),b instanceof
HTMLCanvasElement?(b.parentElement.appendChild(g),g.style.background=b.style.background):b.appendChild(g)):"undefined"!=typeof G_vmlCanvasManager&&(g=document.createElement("canvas"),g=G_vmlCanvasManager.initElement(g),b.appendChild(g)));g&&(g.setAttribute("width",b.width),g.setAttribute("height",b.height),g.height=b.clientHeight,g.width=b.clientWidth);t&&t.domElement?t.domElement.style.display="none":a&&b instanceof HTMLCanvasElement&&(b.style.display="none");g&&(g.style.display="block");r.canvas=
g;r.ctx=null;r.__webgl=null;r.bounds.set(0,0,g.width,g.height);g&&(g.chart=r,g.onmousedown=g.ontouchstart=r.domousedown,g.onmouseup=g.ontouchstop=r.domouseup,g.onmousemove=g.ontouchmove=r.domousemove,g.onmousewheel=r._doWheel)}I&&(I.enabled=c);r.aspect.view3d=c;r.draw()}};this.zPos=function(){return h*(1-this.z-.5*this.depth)};this.Gradient=function(){this.colors=[];this.stops=[];this.addColorStop=function(c,a){this.stops.push(c);this.colors.push(a)}};this.clearRect=function(){n&&K.remove(n);n=new THREE.Object3D;
K.add(n);this.needsRender=!0};this.beginPath=function(){this.items=[];this.closedPath=!1};this.moveTo=function(c,a,b){this.items.push({kind:0,x:c,y:a,z:b})};this.lineTo=function(c,a,b){this.items.push({kind:1,x:c,y:a,z:b})};this.lineZ=function(c,a,b,d){this.moveTo(c,a,b);this.lineTo(c,a,d)};this.surface=function(c,a,b,d,R,l){a=new Tee.MyParametricGeometry(a,c.x-1,c.y-1,!0);a.computeBoundingBox();var r=a.boundingBox,G=r.min.y;r=r.max.y;var f=r-G,q,h=["a","b","c","d"],g=a.vertices;for(q=0;q<a.vertices.length;q++){var n=
new THREE.Color;var k=.7*(r-g[q].y)/f;n.setHSL(k,.9/(1>(k=.9)?k:2-k),.5*k);a.colors[q]=n}for(q=0;q<a.faces.length;q++)for(f=a.faces[q],n=0;3>n;n++)f.vertexColors[n]=a.colors[f[h[n]]];q=new THREE.MeshLambertMaterial({color:16777215,opacity:this.globalAlpha,wireframe:this.wireframe});e(d,q,c,b,a,l,G,r);R&&!d&&(d=new THREE.MeshBasicMaterial({color:this.colorToInt(R),opacity:this.globalAlpha}),d.wireframe=!0,e(!1,d,c,b,a,l,G,r))};this.slice=function(c,a,b,d,f,l,e,h){this.beveled=void 0===h?!1:h;0<l?(this.path=
8,this.p=c,this.torus=e,this.center=a,this.radius=b,this.angle0=d,this.angle1=f,this.donut=l,this.items=[]):(this.beginPath(),this.moveTo(c.x,c.y),this.arc(a.x,a.y,b,d,f,!1),this.closePath())};this.closePath=function(){this.closedPath=!0};this.createLinearGradient=function(){return new this.Gradient};this.createRadialGradient=function(){return new this.Gradient};var v;this.getMaterial=function(c){var a=this.fillStyle;return c?(v||(v=THREE.ImageUtils.loadTextureCube("textures/pisa/px.png textures/pisa/nx.png textures/pisa/py.png textures/pisa/ny.png textures/pisa/pz.png textures/pisa/nz.png".split(" "),
null,function(){M.refresh()})),new THREE.MeshBasicMaterial({color:16777215,envMap:v})):new THREE.MeshPhongMaterial({color:this.colorToInt(a),opacity:this.globalAlpha,wireframe:this.wireframe,specular:5592405,map:null})};this.spline=function(c,a){this.items=[];var b=this.path=0;if(a){for(a=[];b<c.length;)a.push(new THREE.Vector2(c[b],-c[b+1])),b+=2;this.items.push({kind:12,p:a})}else{for(a=new THREE.SplineCurve3;b<c.length;)a.points.push(new THREE.Vector3(c[b],-c[b+1],0)),b+=2;this.items.push({kind:8,
geo:a})}};this.bezierCurveTo=function(c,a,b,d,f,l){this.items.push({kind:11,a:c,b:a,c:b,d:d,e:f,f:l})};this.quadraticCurveTo=function(c,a,b,d){this.items.push({kind:7,x:c,y:a,width:b,height:d})};this.arc=function(c,a,b,d,f,l){this.items.push({kind:4,x:c,y:a,radius:b,angle:d,endAngle:f,clockwise:l})};this.extrudeOptions={amount:1,bevelEnabled:!1,bevelSegments:16,steps:12,curveSegments:64,bevelThickness:10,bevelSize:8};this.getContext=function(){return this};this.beginParent=function(){D=n;n=new THREE.Object3D;
D.add(n);return n};this.endParent=function(){n=D};this.translate=function(c,a){};this.rotate=function(c){};this.fill=function(){var c=M.getMaterial();var a=this.items,b=a.length,q=this.r;if(0<b)if(8==a[0].kind)a=new THREE.TubeGeometry(a[0].geo,100,.05*h*this.depth,8,!1,!1),c=new THREE.Mesh(a,c),c.position.set(.5*-F,.5*E,this.zPos()),n.add(c);else if(this.closedPath){c=new THREE.Shape;for(var e,l,g,k=0;k<b;k++)if(e=a[k],0==e.kind){if(0==k||l!==e.x||g!==-e.y)l=e.x,g=-e.y,c.moveTo(l,g)}else if(1==e.kind){if(0==
k||l!==e.x||g!==-e.y)l=e.x,g=-e.y,c.lineTo(l,g)}else 4==e.kind?c.absarc(l,g,e.radius,2*Math.PI-e.angle,2*Math.PI-e.endAngle,e.clockwise):7==e.kind?c.quadraticCurveTo(e.x,e.y,e.width,e.height):11==e.kind?c.bezierCurveTo(e.a,-e.b,e.c,-e.d,e.e,-e.f):12==e.kind&&(c.moveTo(e.p[0].x,e.p[0].y),c.splineThru(e.p));a=this.extrudeOptions.bevelEnabled;if(this.extrudeOptions.bevelEnabled=this.beveled)b=.02*this.extrudeOptions.bevelSize,this.depth-=b,this.z+=.5*b;c=d(c);c.position.set(.5*-F,.5*E,this.zPos()-h*
this.depth*.5);n.add(c);this.extrudeOptions.bevelEnabled=a}else{g=new THREE.Geometry;l=-h*this.depth;c.side=THREE.DoubleSide;for(k=0;k<b;k++)g.vertices.push(new THREE.Vector3(a[k].x,-a[k].y,0),new THREE.Vector3(a[k].x,-a[k].y,l)),0<k&&(e=new THREE.Face4(2*(k-1),2*k-1,2*k+1,2*k),g.faces.push(e));g.computeFaceNormals();c=new THREE.Mesh(g,c);c.position.set(.5*-F,.5*E,this.zPos()-.5*l);n.add(c)}else if(0==this.depth)if(0<this.rx)c=new THREE.Shape,f(c,q.x,-q.y,q.width,q.height,this.rx),c=d(c),c.position.set(.5*
-F,-q.height+.5*E,this.zPos()),n.add(c);else if(6==this.path)c=new THREE.Shape,c.absellipse(0,0,.5*q.width,.5*q.height,0,2*Math.PI,!0),c=d(c),c.position.set(this.cx-.5*F,-this.cy+.5*E,this.zPos()),n.add(c);else{var m=new THREE.PlaneGeometry(q.width,q.height);c.side=THREE.DoubleSide;m=new THREE.Mesh(m,c)}else 5==this.path?(1==this.topRadius?(w||(w=new THREE.CylinderGeometry(1,1,1,32,1)),m=w):(C||(C=new THREE.CylinderGeometry(0,1,1,32,1)),m=C),m=new THREE.Mesh(m,c),c=.5*Math.min(this.vertical?q.width:
q.height,h),m.scale.x=c,m.scale.z=c,m.scale.y=this.vertical?q.height:q.width,this.vertical||(m.rotation.z=.5*Math.PI,m.rotation.y=Math.PI)):7==this.path?(O||(O=new THREE.SphereGeometry(1,32,32)),m=new THREE.Mesh(O,c),m.scale.set(.5*q.width,.5*q.height,h*this.depth)):6==this.path?(c=new THREE.Shape,c.absellipse(0,0,.5*q.width,.5*q.height,0,2*Math.PI,!0),c=d(c),c.position.set(this.cx-.5*F,-this.cy+.5*E,this.zPos()),n.add(c)):8==this.path?(this.angle0=2*Math.PI-this.angle0,this.angle1=2*Math.PI-this.angle1,
this.torus?(a=Math.abs(this.angle1-this.angle0),a=new Tee.TorusGeometry(this.radius-.5*this.donut,.5*this.donut,16,Math.max(16,90*Math.PI/a|0),a),c=new THREE.Mesh(a,c),c.position.set(this.center.x-.5*F,-this.center.y+.5*E,this.zPos()+this.donut),c.rotation.z=this.angle1,n.add(c)):(c=new THREE.Shape,c.moveTo(this.p.x,this.p.y),c.absarc(this.center.x,this.center.y,this.radius,this.angle0,this.angle1,!0),c.absarc(this.center.x,this.center.y,this.donut,this.angle0,this.angle1,!1),a=this.extrudeOptions.bevelEnabled,
this.extrudeOptions.bevelEnabled=this.beveled,c=d(c),c.position.set(.5*-F,.5*-E,this.zPos()),n.add(c),this.extrudeOptions.bevelEnabled=a)):(1===p?(z||(z=new THREE.BoxGeometry(1,1,1)),m=z):(L||(L=new THREE.BoxGeometry(1,1,1,p,p,p),(new THREE.SubdivisionModifier(2)).modify(L)),m=L),m=new THREE.Mesh(m,c),m.scale.set(q.width,q.height,h*this.depth));m&&(m.position.set(q.x+.5*q.width-.5*F,-(q.y+.5*q.height)+.5*E,this.zPos()),this.showShadows&&(m.receiveShadow=!0,m.castShadow=!0),n.add(m))};this.setLineDash=
function(c){this.dash=c};this.lineMaterial=function(){var c={color:this.colorToInt(this.strokeStyle),opacity:this.globalAlpha};this.dash&&0<this.dash.length?(c=new THREE.LineDashedMaterial(c),c.dashSize=3,c.gapSize=1):(c=new THREE.LineBasicMaterial(c),c.linecap=this.cap,c.linejoin=this.join);c.linewidth=this.lineWidth;return c};this.polygon=function(c,a){var b,e=c.length,f=new THREE.Shape;f.moveTo(c[0].x,-c[0].y);for(b=1;b<e;b++){var l=c[b];f.lineTo(l.x,-l.y)}var g=f.makeGeometry();""!==a.fill&&(this.fillStyle=
a.fill,0<this.depth?b=d(f):(l=this.getMaterial(),b=new THREE.Mesh(g,l),this.wireFrame||(l.side=THREE.DoubleSide)),g=h*(1-this.z),b.position.set(.5*-F,.5*E,g-.5*this.depth),this.showShadows&&(b.castShadow=!0),n.add(b));if(""!==a.stroke.fill){g=new THREE.Geometry;for(b=0;b<e;b++)l=c[b],g.vertices.push(new THREE.Vector3(l.x,-l.y,0));c=new THREE.Line(g,this.lineMaterial());g=h*(1-this.z+this.depth);c.position.set(.5*-F,.5*E,g);n.add(c)}};this.stroke=function(){var c=this.items.length,a=this.lineMaterial();
if(0<c){var b=new THREE.Geometry;for(var d=0;d<c;d++){var e=this.items[d];var l=void 0===e.z?this.z:e.z;l=h*(1-l);0==e.kind?(0<b.vertices.length&&(b=new THREE.Line(b,a),n.add(b)),b=new THREE.Geometry,b.vertices.push(new THREE.Vector3(e.x-.5*F,-e.y+.5*E,l))):1==e.kind&&b.vertices.push(new THREE.Vector3(e.x-.5*F,-e.y+.5*E,l))}0<b.vertices.length&&(b=new THREE.Line(b,a),n.add(b))}else 0==this.depth&&(c=new THREE.Path,l=this.r,0==this.path||1==this.path?0<this.rx?f(c,l.x,-l.y-l.height,l.width,l.height,
this.rx):(c.moveTo(l.x,-l.y-l.height),c.lineTo(l.x+l.width,-l.y-l.height),c.lineTo(l.x+l.width,-l.y),c.lineTo(l.x,-l.y)):6==this.path&&c.absellipse(this.cx,-this.cy,.5*l.width,.5*l.height,0,2*Math.PI,!0),b=new THREE.Line(c.createPointsGeometry(),a),b.position.set(.5*-F,.5*E,this.zPos()),n.add(b))};this.measureText=function(c){return{width:1.4*S.measureText(c).width}};this.roundRect=function(c,a,b,d,e,f){this.path=0;this.r={x:c,y:a,width:b,height:d};this.depth=0;this.rx=e;this.ry=f};this.rect=function(c,
a,b,d){this.path=0;this.r={x:c,y:a,width:b,height:d};this.ry=this.rx=this.depth=0};this.cube=function(c,a){this.path=1;this.r=c;this.items=[];p=0<a?6:1};this.sphere=function(c,a,b,d){m||(m=new THREE.SphereGeometry(1,32,32));var e=new THREE.Mesh(m,this.getMaterial());e.position.set(c-.5*F,-a+.5*E,this.zPos());e.scale.set(.5*b,.5*d,.5*Math.min(b,h));n.add(e)};this.save=function(){};this.clip=function(){};this.restore=function(){};this.colorToInt=function(a){a=a instanceof this.Gradient?a.colors[a.colors.length-
1]:a;return"#"==a.substr(0,1)?parseInt(a.substr(1),16):A(a)};this.pyramid=function(a,b){a=[new THREE.Vector3(100,0,0),new THREE.Vector3(0,100,0),new THREE.Vector3(0,0,100),new THREE.Vector3(0,0,0)];new THREE.ConvexGeometry(a)};this.ellipsoid=function(a,b){this.path=7;this.r=a;this.vertical=b;this.items=[]};this.cylinder=function(a,b,d){this.path=5;this.r=a;this.topRadius=b;this.vertical=d;this.items=[]};this.ellipsePath=function(a,b,d,e){this.path=6;this.cx=a;this.cy=b;this.r={x:a,y:b,width:d,height:e};
this.items=[]};this.addLight=function(a,b,d,e,f,l){a=new a(b);a.position.set(d,e,f);a.shadowsEnabled=l;this.showShadows&&l&&(a instanceof THREE.SpotLight||a instanceof THREE.DirectionalLight)&&(a.castShadow=!0);K.add(a);this.lights.push(a);return a};this.fillText=function(a,b,d){if(""!==a){a:{var c=this.font.split(" ");var e,f;for(e=0;e<c.length;e++)if(f=parseFloat(c[e])){c=f;break a}c=20}f=B(a,c);e=0;f||(f=new THREE.TextGeometry(a,{size:c,height:this.textDepth,curveSegments:2,font:"helvetiker"}),
f.computeBoundingBox(),P.push({text:a,obj:f,size:c}));var g=B("Wj",c);g||(g=new THREE.TextGeometry("Wj",{size:c,height:this.textDepth,curveSegments:2,font:"helvetiker"}));g.computeBoundingBox();a=g.boundingBox;P.push({text:"Wj",obj:g,size:c});g=f.boundingBox;g=g.max.x-g.min.x;a=a.max.y-a.min.y;if("center"===this.textAlign)e=-.5*g;else if("right"===this.textAlign||"end"===this.textAlign)e=-g;g=new THREE.MeshLambertMaterial({color:this.colorToInt(this.fillStyle),opacity:this.globalAlpha,overdraw:!1});
f=new THREE.Mesh(f,g);g="top"===this.textBaseline?a:"middle"==this.textBaseline?.5*a:0;f.position.x=b+e-.5*F;f.position.y=-d+.5*E-g+(a-c);f.position.z=1+h*(1-this.z);f.rotation.x=0;f.rotation.y=2*Math.PI;n.add(f)}};this.update=function(){this.__webgl&&(I&&I.enabled&&I.update(1),this.needsRender&&(this.hitTest&&this.doHitTest(),this.doRender()))};this.setCamera=function(a){H&&K.remove(H);this.camera=H=a?new THREE.PerspectiveCamera(45,window.innerWidth/window.innerHeight,.1,1E4):new THREE.OrthographicCamera(-window.innerWidth/
2,window.innerWidth/2,window.innerHeight/2,-window.innerHeight/2,.1,1E4);H.lookAt(K.position);H.position.set(0,0,800);I&&(I.object=H);this.refresh()};this.refresh=function(){this.needsRender=!0;this.update()};this.createTrackball=function(){t&&"undefined"!==typeof THREE.TrackballControls&&(I=this.trackBall=new THREE.TrackballControls(H,t.domElement),I.enabled=!0,I.keys=[65,83,68],I.dynamicDampingFactor=.2,-1<("undefined"!=typeof navigator?navigator.userAgent.toLowerCase():"").indexOf("mac os x")&&
(I.zoomSpeed=.1),I instanceof THREE.TrackballControls&&I.addEventListener("change",function(){M.needsRender=!0}))};var y,x={};document.addEventListener("fullscreenchange",k,!1);document.addEventListener("mozfullscreenchange",k,!1);document.addEventListener("webkitfullscreenchange",k,!1);this.fullScreen=function(){var a=J,b=a.requestFullscreen||a.mozRequestFullscreen||a.webkitRequestFullscreen||a.msRequestFullScreen;b&&b.call(a)};this.onWindowResize=function(){H instanceof THREE.PerspectiveCamera&&
(H.aspect=window.innerWidth/Math.max(1,window.innerHeight));H.updateProjectionMatrix();t&&t.setSize(window.innerWidth,window.innerHeight)};this.setShowShadows=function(a){this.showShadows=a;for(a=0;a<this.lights.length;a++){var b=this.lights[a];(b instanceof THREE.SpotLight||b instanceof THREE.DirectionalLight)&&b.shadowsEnabled&&(b.castShadow=this.showShadows)}Q.receiveShadow=this.showShadows;t&&(t.shadowMapEnabled=this.showShadows,t.shadowMapType=THREE.PCFSoftShadowMap,this.showShadows&&(t.shadowMapAutoUpdate=
!0))};this.setShowLights=function(a){this.showLights=a;var b,c=this.lights.length;for(b=0;b<c;b++){var d=this.lights[b];if(d.__helper)a=d.visible&&this.showLights,d.__helper.traverse(function(b){b.visible=a});else if(this.showLights){if(d instanceof THREE.SpotLight)d.__helper=new THREE.SpotLightHelper(d,16,100);else if(d instanceof THREE.PointLight)d.__helper=new THREE.PointLightHelper(d,16);else if(d instanceof THREE.DirectionalLight)d.__helper=new THREE.DirectionalLightHelper(d,16,100);else continue;
K.add(d.__helper)}}this.needsRender||this.refresh()};this.showLight=function(a,b){a=this.lights[a];a.visible=b;a.__helper&&(b=b&&this.showLights,a.__helper.traverse(function(a){a.visible=b}));this.refresh()};this.doHitTest=function(){};this.doRender=function(){t&&(t.render(K,H),t.shadowMapAutoUpdate=!1,N&&N.visible&&N.update());this.needsRender=!1};this.clearTextCache=function(){P=[]};this.toogle=function(a,b){a.visible=b;a.visual?(a.visual.traverse(function(a){a.visible=b}),this.needsRender=!0):
a.chart.draw();this.update()};this.isEnabled=function(){return this.__webgl};this.__webgl="undefined"===typeof Detector||Detector&&Detector.webgl;this.needsRender=!0;var h=200;this.showShadows=this.showLights=!1;this.items=[];this.closedPath=!1;this.textDepth=this.z=0;this.beveled=!1;var p=1,g,n;this.wireframe=!1;this.globalAlpha=1;var D,m,w,C,z,L,O,M=this,P=[],J=document.getElementById(b),F=J.clientWidth,E=J.clientHeight,H;b=null;a&&J instanceof HTMLCanvasElement&&(b=J);if(this.__webgl){var K=new THREE.Scene;
var t=new THREE.WebGLRenderer({antialias:!0,canvas:b,clearAlpha:1})}var S=null;a&&(S=document.createElement("canvas").getContext("2d"));this.width=F;this.height=E;this.camera=H;this.scene=K;(this.renderer=t)?t.sortObjects=!1:this.__webgl=!1;var N=this.stats=null;document.addEventListener&&"undefined"!==typeof Stats&&(N=this.stats=new Stats,N.visible=!0,N.setVisible=function(a){N.visible=a;N.domElement.style.display=a?"block":"none"});t&&(t.setSize(F,E),this.showShadows&&(t.shadowMapEnabled=!0,t.shadowMapSoft=
!0));b="#AAAA77";window.getComputedStyle&&(b=window.getComputedStyle(J).backgroundColor);t&&(t.setClearColor(this.colorToInt(b)),J!==t.domElement&&J.appendChild(t.domElement));this.lights=[];if(t){this.addLight(THREE.SpotLight,12303291,-300,300,400,!0);this.addLight(THREE.DirectionalLight,8947848,400,1800,1600,!1);this.addLight(THREE.PointLight,8947848,500,120,-500,!1);this.setShowLights(this.showLights);b=this.ambientLight=new THREE.AmbientLight(2236962);b.visible=!1;K.add(b);b=this.hemiLight=new THREE.HemisphereLight(16777215,
16777215,.5);b.position.y=500;b.visible=!1;K.add(b);var Q=this.floor=new THREE.Mesh(new THREE.CylinderGeometry(4E3,4E3,50,32,1),new THREE.MeshLambertMaterial({color:this.colorToInt("silver"),map:null,opacity:.9,transparent:!0}));this.showShadows&&(Q.receiveShadow=!0);Q.position.y=-20-.5*E;K.add(Q);var I=this.trackBall=null;this.setCamera(!0);this.createTrackball()}this.needsRender=!0}}).call(this);
