/*
 TeeChart(tm) for JavaScript(tm)
 @fileOverview TeeChart for JavaScript(tm)
 v2.7 Apr 2021
 Copyright(c) 2012-2021 by Steema Software SL. All Rights Reserved.
 http://www.steema.com

 Licensed with commercial and non-commercial attributes,
 specifically: http://www.steema.com/licensing/html5

 JavaScript is a trademark of Oracle Corporation.
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(e){var k=0;return function(){return k<e.length?{done:!1,value:e[k++]}:{done:!0}}};$jscomp.arrayIterator=function(e){return{next:$jscomp.arrayIteratorImpl(e)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,k,f){if(e==Array.prototype||e==Object.prototype)return e;e[k]=f.value;return e};$jscomp.getGlobal=function(e){e=["object"==typeof globalThis&&globalThis,e,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var k=0;k<e.length;++k){var f=e[k];if(f&&f.Math==Math)return f}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.SymbolClass=function(e,k){this.$jscomp$symbol$id_=e;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:k})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};
$jscomp.Symbol=function(){function e(f){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(f||"")+"_"+k++,f)}var k=0;return e}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.iterator;e||(e=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[e]&&$jscomp.defineProperty(Array.prototype,e,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var e=$jscomp.global.Symbol.asyncIterator;e||(e=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(e){$jscomp.initSymbolIterator();e={next:e};e[$jscomp.global.Symbol.iterator]=function(){return this};return e};
$jscomp.iteratorFromArray=function(e,k){$jscomp.initSymbolIterator();e instanceof String&&(e+="");var f=0,b={next:function(){if(f<e.length){var a=f++;return{value:k(a,e[a]),done:!1}}b.next=function(){return{done:!0,value:void 0}};return b.next()}};b[Symbol.iterator]=function(){return b};return b};$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");
var $jscomp$lookupPolyfilledValue=function(e,k){var f=$jscomp.propertyToPolyfillSymbol[k];if(null==f)return e[k];f=e[f];return void 0!==f?f:e[k]};$jscomp.polyfill=function(e,k,f,b){k&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(e,k,f,b):$jscomp.polyfillUnisolated(e,k,f,b))};
$jscomp.polyfillUnisolated=function(e,k,f,b){f=$jscomp.global;e=e.split(".");for(b=0;b<e.length-1;b++){var a=e[b];a in f||(f[a]={});f=f[a]}e=e[e.length-1];b=f[e];k=k(b);k!=b&&null!=k&&$jscomp.defineProperty(f,e,{configurable:!0,writable:!0,value:k})};
$jscomp.polyfillIsolated=function(e,k,f,b){var a=e.split(".");e=1===a.length;b=a[0];b=!e&&b in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var d=0;d<a.length-1;d++){var c=a[d];c in b||(b[c]={});b=b[c]}a=a[a.length-1];f=$jscomp.IS_SYMBOL_NATIVE&&"es6"===f?b[a]:null;k=k(f);null!=k&&(e?$jscomp.defineProperty($jscomp.polyfills,a,{configurable:!0,writable:!0,value:k}):k!==f&&($jscomp.propertyToPolyfillSymbol[a]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(a):$jscomp.POLYFILL_PREFIX+a,a=$jscomp.propertyToPolyfillSymbol[a],
$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:k})))};$jscomp.polyfill("Array.prototype.values",function(e){return e?e:function(){return $jscomp.iteratorFromArray(this,function(e,f){return f})}},"es8","es3");$jscomp.polyfill("Array.prototype.fill",function(e){return e?e:function(e,f,b){var a=this.length||0;0>f&&(f=Math.max(0,a+f));if(null==b||b>a)b=a;b=Number(b);0>b&&(b=Math.max(0,a+b));for(f=Number(f||0);f<b;f++)this[f]=e;return this}},"es6","es3");
$jscomp.polyfill("Array.prototype.keys",function(e){return e?e:function(){return $jscomp.iteratorFromArray(this,function(e){return e})}},"es6","es3");var Tee=Tee||{};
(function(){function e(k,f,b){var a,d=f,c;do if(c=d.links){var h=c.length;for(a=0;a<h;a++){var g=c[a].dimension;do{var l=k;do if(g==l)return c[a].searchDimension=c[a].dimension,b.push(c[a]),c[a];while(l=l.parent);if((l=e(k,g,b))||(l=e(g,k,b)))return b.unshift(c[a]),l}while(g=g.parent)}}while(d=d.parent);c=f.subDimensions;for(a=0;a<c.length;a++)if(l=e(k,c[a],b))return l;return null}"undefined"!==typeof exports&&(exports.Tee=Tee);Tee.Data=function(){function k(b,a){if(a){var d,c=a.length;for(d=0;d<
c;d++)b.push({id:a[d],value:0,count:0})}}this.datasets=[];this.addDataSet=function(b,a,d,c){a&&a.implementation&&(a=f(a));b=new Tee.Data.Dimension(b,d,c);b.object=a;b.dataset=b;b.dimensions=[];b.engine=this;this.datasets.push(b);return b};this.addJSON=function(b,a,d,c){return this.addDataSet(b,JSON.parse(a),d,c)};this.applyStyle=function(b,a){switch(a){case 0:b.panel.transparent=!1,b.panel.format.round.x=0,b.panel.format.round.y=0,b.panel.format.stroke.size=2,b.panel.format.stroke.fill="darkgray"}};
this.groupOther=function(b,a,d){var c,h=b.values.length;if(h>a){var g=0;var l=h-a;for(c=a;c<h;c++)g+=b.values[c];b.values[a-1]=g;b.labels[a-1]=d;b.values.splice(a,l);b.labels.splice(a,l);b.code.splice(a,l);return l}return-1};this.slider=function(b,a,d,c,h,g){var l=new Tee.Slider(b);l.min=0;l.max=a.length-1;l.step=1;l.position=l.min;l.useRange=!1;l.thumbSize=12;l.horizontal=!0;l.bounds.x=d;l.bounds.y=c;l.bounds.width=h;l.bounds.height=g;b.tools.add(l);return l};var f=function(b){var a={};if(1==b.nodeType){if(0<
b.attributes.length)for(var d=0;d<b.attributes.length;d++){var c=b.attributes.item(d);a[c.nodeName]=c.value}}else 3==b.nodeType&&(a=b.nodeValue);if(b.hasChildNodes())for(d=0;d<b.childNodes.length;d++){c=b.childNodes.item(d);var h=c.nodeName;if("undefined"==typeof a[h])"#text"===h?c.hasChildNodes()?a[h]=f(c):(c=c.nodeValue.trim(),""!==c&&(a=c)):"xml"==h?a=f(c):a[h]=f(c);else{if("undefined"==typeof a[h].push){var g=a[h];a[h]=[];a[h].push(g)}a[h].push(f(c))}}return a};this.loadXMLDoc=function(b){var a=
window.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Microsoft.XMLHTTP");a.open("GET",b,!1);a.send();return a.responseXML};this.loadXMLString=function(b){window.DOMParser?(parser=new DOMParser,xmlDoc=parser.parseFromString(b,"text/xml")):(xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),xmlDoc.async=!1,xmlDoc.loadXML(b));return xmlDoc};this.queryDim=function(b,a,d){var c=b.dimension.getLinksTo(a),h;if(c){var g=c[0];b.initDims();var l="function"===typeof b.name?b.name:null;b.dimension.traverse(function(m,
h){if(!b.name||b.consider(m))if(a?null===g.field&&a==g.dimension?h=a.hasID?a.parent?a.data[a.id]:m[a.id]:a==b.dimension?h||d.length:a.field?m[a.field]:h:(h=a.searchAcross(c,m))&&a.hasID&&(h=h[a.id]):(h=b.dimension.title,h||(h=b.dimension.dataset.object,b.dimension.field&&(h=h[b.dimension.field]))),null!==h&&(!a||a.nulls||""!==h)){var e=-1,q;m=l?l(m):b.name?m[b.name]:m;"undefined"===typeof m?m=null:("number"!==typeof m&&(m=parseFloat(m)),m!==m&&(m=null));if(null!==m){a&&a.datetime&&(h=a.datePart(h));
for(q=0;q<d.length;q++)if(d[q].id==h){e=q;if(0===d[e].count)d[e].count=1,d[e].value=m;else{q=b.measure;var r=m,f=d[e];f.count++;switch(q){case "sum":case "average":f.value+=r;break;case "high":if(1==f.count||r>f.value)f.value=r;break;case "low":if(1==f.count||r<f.value)f.value=r}}break}-1==e&&d.push({id:h,value:m,count:1})}}return!0});if("count"==b.measure)for(h=0;h<d.length;h++){var m=d[h];m.value=m.count}else if("average"==b.measure)for(h=0;h<d.length;h++)m=d[h],0<m.count&&(m.value/=m.count);return!0}return!1};
this.query=function(b,a){var d,c,h=[],g,l;a=a instanceof Array?a:[a];b=b instanceof Array?b:[b];var m=b.length;if(0<m){var e=(l=b[0])?l.selected:null;var f=[];e?f=e instanceof Array?e:[e]:l&&(l.id||l.field)&&(f=l.getIds())}for(e=0;e<a.length;e++)if(d=a[e]){for(g=m-1;0<=g;g--){var n=b[g];if(0<g){if(n){var t=n.selected;if(t)if(t instanceof Array||(t=[t]),n.selectedInclude)var u=t;else for(u=n.getIds(),c=0;c<t.length;c++)u.splice(u.indexOf(t[c]),1);else u=n.getIds();for(var v=0;v<u.length;v++)if(n.selected=
u[v],n.nulls||""!==n.selected)if(c=[],k(c,f),this.queryDim(d,b[g-1],c,n)){var p;if(!(p=n.nulls)){var w=0;for(p=0;p<c.length;p++)w+=c[p].count;p=0<w}p&&h.push({metric:d,dimension:n,values:c,master:n.selected,masterdim:b[g-1]})}n.selected=t;break}}else c=[],k(c,f),this.queryDim(d,n,c)&&h.push({metric:d,dimension:n,values:c,master:null})}if(0<m&&l&&!l.nulls)for(n=0;n<h[0].values.length;){for(d=g=0;d<h.length;d++)g+=h[d].values[n].count;if(0===g)for(d=0;d<h.length;d++)h[d].values.splice(n,1);else n++}}return h};
this.Chart=function(b,a){function d(a,c){var g=0,d;for(d=0;d<a.length;d++)g+=a[d].data.values[c];return g}var c=new Tee.Chart(b);c.engine=this;c.panel.margins.left=0;b=new Tee.ToolTip(c);b.render="dom";c.tools.add(b);b.ongettext=function(a,c,d,b){a="";var g=d.data.labels;1<d.chart.series.count()&&(a="<br/>"+d.title);d.data.x&&(a+="<br/>"+d.data.x[b]);return c+" "+(0<g.length?g[b]:"")+a};var h=new Tee.Animation;h.onstart=function(){this.s.fill="yellow"};h.onstop=function(){this.s.fill=this.old};h.duration=
100;h.animateHover=function(a){this.s=a.series.items[0].hover.stroke;this.old=this.s.fill;this.animate(a)};c.title.text=a;c.guessStyle=function(a){return this.defaultStyle?this.defaultStyle:30<a.length?Tee.Line:Tee.Bar};c.newSeries=function(a,d){a=d.values;var g=d.dimension,b=d.master;d.masterdim||(b=b&&g&&g.id?b[g.id]:d.master||d.metric.title);d=c.guessStyle(a);var l=c.addSeries(new d),h=l.data;l.title=""+(b||"(none)");l.marks.style="value";l.cursor="pointer";h.values=[];h.labels=[];h.code=[];var f=
c.series.items.length;b=[];var k;g&&g.titles&&e(g.titles,g,b);if(1<f){var v=c.series.items[f-2].data;for(k=0;k<v.values.length;k++)h.values.push(0),h.labels.push(v.labels[k]),h.code.push(v.code[k]);for(k=0;k<a.length;k++){f=a[k];var p=v.code.indexOf(f.id);-1==p?(h.values.push(f.value),p=g&&g.titles?(p=g.searchAcross(b,f.id))?p[g.titles.id]:"":f.id[g.id],h.labels.push(p),h.code.push(f.id)):h.values[p]=f.value}}else for(k=0;k<a.length;k++)f=a[k],h.values.push(f.value),p=g&&g.titles?(p=g.searchAcross(b,
f.id))?p[g.titles.id]:"":""+f.id,h.labels.push(p),h.code.push(f.id);d==Tee.CircularGauge&&l.setValue(l.data.values[0]);if(this.onnewseries)this.onnewseries(this,l);return l};c.defaultStyle=null;c.animateChanges=!1;c.setSeriesStyle=function(a){if(a&&""!==a&&"auto"!==a){var c=this.series,g;this.defaultStyle=g="string"===typeof a?eval(a):a;for(var d=0;d<c.items.length;d++){var b=c.items[d].data;a=new g;a.setChart(a,this);a.format.fill=c.items[d].format.fill;a.data=b;c.items[d]=a}this.draw()}else this.defaultStyle=
null};c.fill=function(a,c,d){this.fillQuery(this.engine.query(a,c),a,c,d)};c.fillQuery=function(a,d,b,h){var g,l=c.series.items;c.series.items=[];if(a){for(g=0;g<a.length;g++){var e=a[g];var m=e.metric;this.newSeries(m,e).onclick=c.engine._onclickseries;if(""===c.title.text||"undefined"===typeof c.title.text)c.title.text=m.dimension.title;b instanceof Array||(c.legend.title.text=m.title+"\n"+m.measure,c.legend.title.format.font.textAlign="right");(e=d instanceof Array?d[0]:d)&&e!=m.dataset&&(c.axes.bottom.title.text=
e.datetime?e.title+" "+e.dateKeys[e.datetime.selected]:e.title)}0<a.length&&(c.axes.left.title.text=a[0].metric.title)}a=this.sort;""!==a.sortBy&&this.sortData(a.sortBy,"ascending"===a.order);""!==a.series&&this.sortSeries("ascending"==a.series);if(c.animateChanges&&l.length==c.series.items.length){a=c.series.items[0];var f=a.data.values;if(l[0].prototype==a.prototype&&l[0].data.values.length==f.length){var k=f.slice(0),q;a=new Tee.Animation(c,function(a){for(var c=0;c<f.length;c++)q=l[0].data.values[c],
f[c]=q+(k[c]-q)*a});d=c.axes.left.automatic;c.axes.left.automatic=!1;a.duration=150;a.animate();c.axes.left.automatic=d}}h||c.draw()};this.applyStyle(c,0);c.animateClick=function(){h.animateHover(c)};this.onclickseries=null;this._onclickseries=function(a,c){var d=a.chart;d.onclickseries&&(d.animateClick(),d.onclickseries(a,c))};c.setSeriesPalette=function(a,c){var d=a.palette,b=a.count();a=a.data.code;d.colors=Array(b);for(var g=0;g<b;g++){var h=a[g];c.isSelected(h)||(d.colors[g]="silver")}};c.sortData=
function(a,c){var b=this.series.count(),g=this.series.items[0];if(0<b){if(1<b&&"values"==a){a=g.data.values.length;var h=this.series.items;var e=Array(a);for(b=0;b<a;b++)e[b]=b;e.sort(function(a,b){a=d(h,a);b=d(h,b);return c?a-b:b-a})}else e=this.series.items[0].doSort(a,c);this.series.each(function(a){for(var c={values:[],labels:[],code:[]},d=a.data,b,g=0;g<d.values.length;g++)b=e[g],c.values.push(d.values[b]),c.labels.push(d.labels[b]),c.code.push(d.code[b]);a.data=c})}};c.sortSeries=function(a){var c=
this.series.items,d=c.length;if(!(2>d)){var b=Array(d),g,h,e=a?-1:1,f=a?1:-1;for(a=0;a<d;a++)b[a]=a;b.sort(function(a,d){g=c[a].title.toLowerCase();h=c[d].title.toLowerCase();return g<h?e:g==h?0:f});var k=Array(d);for(a=0;a<d;a++)k[a]=c[b[a]];this.series.items=k}};c.groupOther=function(a){this.series.each(function(c){var d=Engine.groupOther(c.data,a,"Other");-1<d&&(c.data.code[d]=null,c.data.code.splice(0,d))})};c.totalPoints=function(){var a=0;this.series.each(function(c){a+=c.data.values.length});
return a};c.sort={sortBy:"",order:"descending",series:"ascending"};c.setPositionPercent=function(a,c,d,b){var g=self.innerHeight?self.innerHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body?document.body.clientHeight:0,h=self.innerHeight?self.innerWidth:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientWidth:document.body?document.body.clientWidth:0,e=this.canvas;d=.01*d*h|0;b=.01*
b*g|0;e.style.position="absolute";e.style.left=a*h*.01+"px";e.style.top=c*g*.01+"px";e.style.width=d+"px";e.style.height=b+"px";e.setAttribute("width",d);e.setAttribute("height",b);this.bounds.width=d;this.bounds.height=b;this.draw()};Tee.SeriesAnimation&&(a=c.animation=new Tee.SeriesAnimation(c),a.kind="zoomin",a.duration=300,b=new Tee.FadeAnimation(c),b.fade.series=!0,a.items.push(b));return c}};Tee.Data.Metric=function(e,f,b){this.name=b;this.title=f||b;this.dimension=e;var a=(this.dataset=e.dataset).engine;
this.measure="sum";this.initDims=function(){var d,c=a.datasets.length,b,g=this.dimension;this.allDims=[];for(d=0;d<c;d++){var e=a.datasets[d].dimensions;var f=e.length;for(b=0;b<f;b++){var k=e[b];g!=k&&!g.hasParent(k)&&k.anySelected()&&(k._link=k.dataset==g.dataset?null:g.getLinksTo(k),this.allDims.push(k))}}};this.consider=function(a){var c,d=this.allDims.length;for(c=0;c<d;c++){var b=this.allDims[c];if(b._link){var e=a;for(var f=0;f<b._link.length;f++)e=b.search(b._link[f],e);e&&b.id&&(e=e[b.id])}else e=
a[b.field];if("undefined"===typeof e||null===e)return!1;b.datetime&&(e=b.datePart(e));if(!b.inSelected(e))return!1}return!0}};Tee.Data.Dimension=function(k,f,b){this.engine=this.parent=this.dataset=null;this.subDimensions=[];this.field=f;this.id=b;this.title=k||f;this.nulls=!0;this.hasID="undefined"!==typeof b&&null!==b&&""!==b;this.metrics=[];this.links=[];this.select=this.selected=null;this.selectedInclude=!0;this.dateKeys={c:"Century",x:"Decade",y:"Year",m:"Month",w:"Weekday",d:"Day"};this.addDimension=
function(a,d,c){return this.addSubDimension(this,a,d,c)};this.addSubDimension=function(a,d,c,b){d=new Tee.Data.Dimension(d,c,b);d.engine=this.engine;if(d.parent=a)d.dataset=a.dataset,d.dataset&&(d.index=d.dataset.dimensions.push(d)),a.subDimensions.push(d);return d};this.addMetric=function(a,d,c){a=new Tee.Data.Metric(this,a,d);c&&(a.measure=c);this.metrics.push(a);return a};this.addLink=function(a,d,c){a={field:a,dimension:d,datasetField:c,parent:this};this.links.push(a);return a};this.hasParent=
function(a){for(var d=this.parent;d;){if(d==a)return!0;d=d.parent}return!1};this.inSelected=function(a){return this.select?this.select(a):this.selected instanceof Array?this.selectedInclude?-1!=this.selected.indexOf(a):-1==this.selected.indexOf(a):this.selectedInclude?this.selected==a:this.selected!=a};this.get=function(a){var d=this.id,c,b=this.datetime,e=this;this.traverse(function(g){b&&(g=e.datePart(g));return a==(d?g[d]:g)?(c=g,!1):!0});return c};this.datePart=function(a){var b=this.datetime,
c=b.selected;if("string"==typeof a){var e=a.match(/(\d+)/g);if("y"==c)return e[b.yearField||2];if("m"==c)return e[b.monthField||0];if("x"==c)return 10*(parseInt(e[2],10)/10|0);if("d"==c)return e[b.dayField||1];if("w"==c)return(new Date(a)).getDay()}else if(a instanceof Date){if("y"==c)return a.getFullYear();if("m"==c)return a.getMonth()+1;if("x"==c)return 10*(a.getFullYear()/10|0);if("d"==c)return a.getDate();if("w"==c)return a.getDay()}return a};this.getValues=function(){var a=[],b=this.field,c=
this.id,e=this;this.traverse(function(d){c&&(d=b?d[b]:d[c]);e.datetime&&(d=e.datePart(d));-1==a.indexOf(d)&&a.push(d);return!0});return a};this.getIds=function(){var a=[],b,c=this.id,e=this.field,g=this;(this.parent?this.parent:this).traverse(function(d){b=c?d[c]:e?d[e]:d;g.datetime&&(b=g.datePart(b));(g.nulls||b)&&-1==a.indexOf(b)&&a.push(b);return!0});return a};this.isSelected=function(a){return this.select?this.select(a):this.selected?this.inSelected(a):!0};this.anySelected=function(){if(this.select)return!0;
var a=this.selected;if(null!==a&&"undefined"!=typeof a)if(a instanceof Array)for(var b=0;b<a.length;b++){if(a[b])return!0}else return!0;return!1};this.toggleSelected=function(a,b){this.selected||(this.selected=[]);b=a.data.code[b];var c=this.selected.indexOf(b);-1===c?this.selected.push(b):(this.selected.splice(c,1),0===this.selected.length&&(this.selected=null));a.chart.setSeriesPalette(a,this)};this.traverse=function(a){function b(d,e){var g=c[e];var h=g.anySelected();var f=g.field?d[g.field]:d;
d=g.parent?d:f;if(!h||g.isSelected(g.id?d[g.id]:d))if(g.data=d,f instanceof Array)if(h=f.length,0<e)for(g=0;g<h;g++){if(!b(f[g],e-1))return!1}else for(g=0;g<h;g++){if(!a(f[g],g))return!1}else if(0<e){a:if(f&&"object"===typeof f){d=Object.keys(f);var k=d.length,l=c[0],u=l.anySelected();for(e=0;e<k;e++)if(h=d[e],!u||l.isSelected(h))if(g=f[h],l.data=g,!a(g,h)){f=!1;break a}f=!0}else f=a(f,void 0);if(!f)return!1}else if(!a(d))return!1;return!0}var c=[],e=this;do c.push(e);while(e=e.parent);(e=this.dataset.object)&&
b(e,c.length-1)};this.searchAcross=function(a,b){for(var c=b,d=this,e=0;e<a.length;e++)c=d.search(a[e],c,0<e),e<a.length-1&&(d=a[e+1].parent,a[e+1].searchDimension=d);c&&this.engine.cache&&(b.cache||(b.cache=[]),b.cache[this.index]||(b.cache[this.index]=c));return c};this.search=function(a,b,c){if(b.cache&&b.cache[this.index])return b.cache[this.index];var d=null,e,f=a.search,k=c?a.field:a.datasetField;c=c?a.datasetField:a.field;var q=c instanceof Array;if(q){var r=[];for(e=0;e<c.length;e++)r.push(b[c[e]])}else r=
b[c];a=a.searchDimension||a.dimension;do if(a.traverse(function(a){if(f){if(f(a,b))return d=a,!1}else if(q){var c=!0;for(e=0;e<r.length;e++)if(a[k[e]]!==r[e]){c=!1;break}if(c)return d=a,!1}else if(a[k]==r)return d=a,!1;return!0}),d){if(a.dataset!==this.dataset)return d;if(a!==this)if(a.parent)a=a.parent,d=a.data;else break}else break;while(a!==this);return d?this.id?d:d[this.field]:null};this.getLinksTo=function(a){if(a&&a!=this.dataset&&a.dataset!=this.dataset){var b=[],c=e(a,this,b);c||(c=e(this,
a,b));return c?b:null}return[{field:null,dimension:a,datasetField:null,parent:this}]}}}).call(this);
