/*
 TeeChart(tm) for JavaScript(tm)
 @fileOverview TeeChart for JavaScript(tm)
 v1.3 October 2012
 Copyright(c) 2012 by Steema Software SL. All Rights Reserved.
 http://www.steema.com

 Licensed with commercial and non-commercial attributes,
 specifically: http://www.steema.com/licensing/html5

 JavaScript is a trademark of Oracle Corporation.
*/
var Tee=Tee||{};
(function(){function s(c,b){this.x=c;this.y=b}function M(c,b,a,d){function e(){var d,e;if(a.x==b.x&&a.y==b.y)d=c.x-b.x,e=c.y-b.y;else{d=a.x-b.x;e=a.y-b.y;var g=((c.x-b.x)*d+(c.y-b.y)*e)/(d*d+e*e);0>g?(d=c.x-b.x,e=c.y-b.y):1<g?(d=c.x-a.x,e=c.y-a.y):(d=c.x-(b.x+g*d),e=c.y-(b.y+g*e))}return Math.sqrt(d*d+e*e)}return c.x==b.x&&c.y==b.y||c.x==a.x&&c.y==a.y?!0:Math.abs(e())<=d+1}function q(c,b,a,d){this.set(c,b,a,d)}function I(){this.left=this.right=this.top=this.bottom=2;this.apply=function(c){var b=c.width,
a=c.height;c.x+=0.01*b*this.left;c.width-=0.01*b*Math.min(100,this.left+this.right);c.y+=0.01*a*this.top;c.height-=0.01*a*Math.min(100,this.top+this.bottom)}}function N(c,b,a){this.format=a;this.bounds=b;var d=this,b=a.shadow;this.old=new A;this.old.set(b);b.visible=!0;b.color="rgba(0,255,0,0.1)";b.blur=10;b.width=0;b.height=0;this.enabled=!0;a=new Tee.Animation(a.chart,function(a){d.enabled&&(1>a?d.format.shadow.color="rgba(0,255,0,"+a.toString()+")":d.autoHide&&d.restore())});a.duration=c;a.animate();
this.restore=function(){this.format.shadow.set(this.old);this.enabled=!1}}function z(c){this.chart=c;this.visible=!1;this.colors=["white","silver"];this.direction="topbottom";this.stops=null;this.offset={x:0,y:0};this.create=function(b,a){return this.rect(b.x,b.y,b.width,b.height,a)};this.rect=function(b,a,d,e,c){var f;f=this.chart.ctx;var g=f.createLinearGradient;"topbottom"==this.direction?f=g.call(f,b,a,b,a+e):"bottomtop"==this.direction?f=g.call(f,b,a+e,b,a):"leftright"==this.direction?f=g.call(f,
b,a,b+d,a):"rightleft"==this.direction?f=g.call(f,b+d,a,b,a):"radial"==this.direction?(b=b+0.5*d+this.offset.x,a=a+0.5*e+this.offset.y,d=Math.max(d,e),f=f.createRadialGradient(b,a,0,b,a,d)):f="diagonalup"==this.direction?g.call(f,b,a+e,b+d,a):g.call(f,b,a,b+d,a+e);c&&this.setEndColor(c);d=this.colors;e=d.length;b=(a=this.stops)?a.length:0;if(1<e)for(c=0;c<e;c++)f.addColorStop(b<=c?c/(e-1):a[c],d[c]);else f.addColorStop(0,0<e?d[0]:"white");return f}}function A(c){this.chart=c;this.visible=!1;this.blur=
4;this.color="rgba(80,80,80,0.75)";this.height=this.width=4;this.prepare=function(b){this.visible?(b.shadowBlur=this.blur,b.shadowColor=this.color,b.shadowOffsetX=this.width,b.shadowOffsetY=this.chart.isAndroid?-this.height:this.height):b.shadowColor="transparent"}}function J(c){this.url="";this.chart=c;this.visible=!0;this.tryDraw=function(b,a,d,e){this.image||(this.image=new Image,this.image.onload=function(){c.draw()});""==this.image.src?(c=this.chart,this.image.src=this.url):c.ctx.drawImage(this.image,
b,a,d,e)}}function B(c){this.chart=c;this.fill="black";this.size=1;this.join="round";this.cap="square";this._g=this.dash=null;x?x(this,"gradient",{get:function(){this._g||(this._g=new z(this.chart));return this._g}}):this._g=this.gradient=new z(c);this.prepare=function(b,a){var a=a||this.chart.ctx,d=this._g;a.strokeStyle=d&&d.visible?d.create(this.chart.bounds):b?b:this.fill;a.lineWidth=this.size;a.lineJoin=this.join;a.lineCap=this.cap;a.shadowColor="transparent";a.setLineDash?a.setLineDash(this.dash):
a.mozCurrentTransform?a.mozDash=this.dash:this.chart.isChrome&&(a.webkitLineDash=this.dash)};this.setChart=function(b){this.chart=b;this._g&&(this._g.chart=b)}}function C(c){this.chart=c;this.style="11px Tahoma";this._g=null;x?x(this,"gradient",{get:function(){this._g||(this._g=new z(this.chart));return this._g}}):this._g=this.gradient=new z(c);this.fill="black";this._sh=null;x?x(this,"shadow",{get:function(){this._sh||(this._sh=new A(this.chart));return this._sh}}):this._sh=this.shadow=new A(c);
this._s=null;x?x(this,"stroke",{get:function(){this._s||(this._s=new B(this.chart),this._s.fill="");return this._s}}):(this._s=this.stroke=new B(c),this._s.fill="");this.textAlign="center";this.baseLine="alphabetic"}function O(c){this.chart=c;this.items=[];this.draw=function(){for(var b=0,a;a=this.items[b++];)a.active&&a.draw()};this.mousemove=function(b){for(var a=0,d;d=this.items[a++];)d.active&&d.mousemove(b)};this.mousedown=function(b){for(var a=0,d,e=!1;d=this.items[a++];)d.active&&d.mousedown(b)&&
(e=!0);return e};this.mouseout=function(){for(var b=0,a;a=this.items[b++];)a.active&&a.mouseout()};this.clicked=function(b){for(var a=0,d,e=!1;d=this.items[a++];)d.active&&d.clicked(b)&&(e=!0,d.onclick&&(e=d.onclick(d,b.x,b.y)));return e};this.add=function(b){this.items.push(b);return b}}function P(c){function b(a){var b=a.chart.chartRect,c=a.direction,g="both"==c;d.set(b.x,b.y,b.width,b.height);if(a.old){if(g||"horizontal"==c)0>a.old.x?(d.x=a.chart.oldPos.x+a.old.x,d.width=-a.old.x):(d.x=a.chart.oldPos.x,
d.width=a.old.x);if(g||"vertical"==c)0>a.old.y?(d.y=a.chart.oldPos.y+a.old.y,d.height=-a.old.y):(d.y=a.chart.oldPos.y,d.height=a.old.y)}return d}this.chart=c;this.active=!1;this.enabled=!0;this.done=!1;this.direction="both";this.mouseButton=0;var a=this.format=new Tee.Format(c);a.fill="rgba(255,255,255,0.5)";a.stroke.fill="darkgray";a.stroke.size=2;var d=new q;this.draw=function(){a.rectangle(b(this))};this.apply=function(){if(0>this.old.x||0>this.old.y){if(this.reset(),this.onreset)this.onreset()}else if(b(this),
3<d.width&&3<d.height)return this.chart.axes.each(function(){this.horizontal?this.calcMinMax(d.x,d.x+d.width):this.calcMinMax(d.y+d.height,d.y)}),!0;return!1};this.reset=function(){this.chart.axes.each(function(){this.automatic=!0})}}function Q(c){this.chart=c;this.active=!1;this.enabled=!0;this.done=!1;this.mouseButton=2;this.direction="both";this.position=new s(0,0)}function H(c,b){Tee.Annotation.call(this,c);this.transparent=!0;this._expand=!1;x?x(this,"expand",{get:function(){return this._expand},
set:function(a){this._expand=a;this._expand||(a=this.format,a.round.x=8,a.round.y=8,a.round.corners=null,a.stroke.fill="black")}}):this._expand=this.expand=!1;var a=this.format.font,d=a.shadow,e=this.position;d.visible=!0;d.width=2;d.height=2;d.blur=8;a.style="18px Tahoma";a.fill=b;this.padding=4;this.calcRect=function(a){this.resize();var d=this.bounds,b=d.height+(this.transparent?1:2)*this.padding,j=c.chartRect;a?(e.y=j.y,j.setTop(j.y+b)):(e.y=j.y+j.height-d.height-this.padding,j.height-=b);0>j.height&&
(j.height=0);e.x=0.5*(c.canvas.width-d.width)};this.tryDraw=function(a){if(this.visible&&this.text&&""!==this.text){this.calcRect(a);var d=this.bounds;if(this._expand){var b=c.panel.format;e.x=""!=b.stroke.fill?b.stroke.size:0;e.y=a?e.x:c.canvas.height-(b.shadow.visible?b.shadow.height:0)-e.x-d.height;d.width=c.canvas.width-(b.shadow.visible?b.shadow.width:0)-2*e.x;var j=this.format;j.round.x=b.round.x;j.round.y=b.round.y;j.round.corners=[a,a,!a,!a];j.stroke.fill="";this.transparent=!1}d.x=e.x;d.y=
e.y;this.doDraw()}}}function R(c){var b=this.format=new Tee.Format(c);b.round.x=12;b.round.y=12;b.stroke.size=3;b.gradient.visible=!0;b.gradient.direction="bottomtop";b.shadow.visible=!0;b.stroke.fill="#606060";this.transparent=!1;this.margins=new I;this.clear=function(){var a=c.bounds;c.ctx.clearRect(a.x,a.y,a.width,a.height)};this.draw=function(){if(this.transparent)this.clear();else{var a=c.chartRect,d=b.shadow;d.visible&&(a.width-=0.5*Math.abs(d.width)+2,a.height-=0.5*Math.abs(d.height)+2,0>d.width&&
(a.x-=d.width),0>d.height&&(a.y-=d.height));var e=0;""!=b.stroke.fill&&(e=b.stroke.size,1<e&&(e*=0.5,a.x+=e,a.y+=e,a.width-=2*e,a.height-=2*e));(d.visible||0<b.round.x||0<b.round.y)&&this.clear();b.rectangle(a);0<e&&(a.x+=e,a.y+=e,a.width-=2*e,a.height-=2*e)}}}function F(c){this.format=new Tee.Format(c);this.format.fill="#E6E6E6";this.format.stroke.fill="black";this.visible=!0;this.bounds=new q;this.draw=function(){this.format.rectangle(this.bounds)}}function v(c,b,a){function d(a){this.chart=a;this.stroke=
new B(a);this.stroke.cap="butt";this.visible=!0;this.length=4}function e(a){Tee.Annotation.call(this,a);this.padding=4;this.transparent=!0;this.format.font.textAlign="center"}function i(a,d){var b=0,e,c=d.split(" "),f;for(f=0;f<c.length;f++)e=a.textWidth(c[f]),e>b&&(b=e);return b}function f(a){return isFinite(a)?10<=a?10*f(0.1*a):1>a?0.1*f(10*a):2>a?2:5>a?5:10:1}this.chart=c;this.visible=!0;this.inverted=!1;this.horizontal=b;this.otherSide=a;this.bounds=new q;this.position=0;this.format=new Tee.Format(c);
this.format.stroke.size=2;this.custom=!1;this.labels=new function(a,d){this.chart=a;this.format=new Tee.Format(a);this.decimals=2;this.padding=4;this.separation=10;this.visible=!0;this.rotation=0;this.alternate=!1;this.maxWidth=0;this.wordWrap="no";this.labelStyle="auto";this.dateFormat="shortDate";this.checkStyle=function(){var a=this.labelStyle,b=d.firstSeries;this._text=null;if("auto"==a)0<b.data.labels.length&&b.notmandatory==d&&(this._text=b);else if("mark"==a||"text"==a)this._text=b};this.getLabel=
function(b){var e=b|0,c;if(this._text&&e==b){if(c=this._text.data,c.x&&(e=c.x.indexOf(e)),c=c.labels[e],!c){var f=a.series.items,i,g;for(i=0;(g=f[i++])&&(!(g!=this._text&&g.visible&&g.associatedToAxis(d))||!(c=g.data.labels[e])););"undefined"===typeof c&&(c="")}}else c=d.dateTime&&Date.prototype.format?(new Date(b)).format(this.dateFormat):this.valueFormat?b.toLocaleString():b.toFixed(e==b?0:this.decimals);this.ongetlabel&&(c=this.ongetlabel(b,c),this.format.font.prepare());return""+c};this.width=
function(a){return this.format.textWidth(this.getLabel(a))}}(c,this);var g=this.labels.format.font;this.scroll=function(a){this.automatic=!1;this.inverted&&(a=-a);this.minimum+=a;this.maximum+=a};b?(g.textAlign="center",g.baseLine=a?"bottom":"top"):(g.textAlign=a?"left":"right",g.baseLine="middle");this.grid=new function(a){this.chart=a;a=this.format=new Tee.Format(a);a.stroke.fill="silver";a.stroke.cap="butt";a.fill="";this.visible=!0;this.lineDash=!1}(c);this.ticks=new d(c);this.innerTicks=new d(c);
this.innerTicks.visible=!1;g=this.minorTicks=new d(c);g.visible=!1;g.length=2;g.count=3;e.prototype=new Tee.Annotation;this.title=new e(c);this.automatic=!0;this.increment=this.maximum=this.minimum=0;this.log=!1;this.start=this.endPos=this.startPos=0;this.end=100;this.increm=this.scale=this.axisSize=0;this.minmaxLabelWidth=function(){var a=this.labels,d=a._text,b=0,e,c;if(null!=d){c="auto"==a.wordWrap||"yes"==a.wordWrap;for(var f=0,g=d.data.labels.length;f<g;f++)e=d.data.labels[f],this.ongetlabel&&
(e=this.ongetlabel(f,e)),e&&(b=Math.max(b,c?i(a.format,e):a.format.textWidth(e)))}else b=this.roundMin(),d=this.maximum,b=Math.max(a.width(b),a.width(0.5*(b+d))),b=Math.max(b,a.width(1E-7)),b=Math.max(b,a.width(d));return b};this.checkMinMax=function(){var a=this.chart.series,d=this.horizontal;this.automatic&&(this.minimum=d?a.minXValue(this):a.minYValue(this),this.maximum=d?a.maxXValue(this):a.maxYValue(this))};this.calcAxisScale=function(){var a=this.maximum-this.minimum;0==a?a=1:this.log&&(a=Math.log(a));
this.scale=this.axisSize/a};this.calcScale=function(){var a=this.labels,d;a.format.font.prepare();d=this.horizontal?this.minmaxLabelWidth():a.format.textHeight("Wj");a.alternate&&(d*=0.5);d*=1+0.02*a.separation;if(0==this.increment)if(this.maximum==this.minimum)a=1;else{a=this.axisSize/d;b:{d=a;var b,e,c;for(b=0;e=this.chart.series.items[b++];)if(e.visible&&((c=e.yMandatory)&&this.horizontal||!c&&!this.horizontal)&&e.associatedToAxis(this)&&e.count()<=d){d=!0;break b}d=!1}a=Math.abs(this.maximum-
this.minimum)/(a+1);a=d?Math.max(1,a):f(a)}else a=this.increment;this.increm=a;0>=this.increm&&(this.increm=0.1)};this.hasAnySeries=function(){var a=this.chart.series.items,d,b;for(d=0;b=a[d++];)if(b.visible&&b.associatedToAxis(this))return a=this.horizontal,b.yMandatory&&(a=!a),this.dateTime=(a=a?b.data.values:b.data.x)&&0<a.length&&a[0]instanceof Date,b;return null};this.drawAxis=function(){var a=this.chart.ctx;a.beginPath();b?(a.moveTo(this.startPos,this.axisPos),a.lineTo(this.endPos,this.axisPos)):
(a.moveTo(this.axisPos,this.startPos),a.lineTo(this.axisPos,this.endPos));this.format.stroke.prepare();a.stroke()};this.drawGrids=function(){var d=this.chart.ctx,e,c=this.chart.chartRect,f=this.grid.format,i,g,m,t,l=this.roundMin();this.grid.centered&&(e=0.5*this.increm,l=l-e>=this.minimum?l-e:l+e);d.beginPath();b?(g=this.bounds.y,t=a?c.getBottom()-1:c.y+1):(i=this.bounds.x,m=a?c.x+1:c.getRight()-1);if(""!=f.fill){var c=l,w=f.stroke.fill;f.stroke.fill="";for(var u,s=-1;c<=this.maximum;)e=this.calc(c),
0==s%2&&(b?f.rectangle(u,t,e-u,g-t):f.rectangle(i,u,m-i,e-u)),u=e,c+=this.increm,s++;f.stroke.fill=w;d.fillStyle=""}for(c=l;c<=this.maximum;){b?i=m=this.calc(c):g=t=this.calc(c);if(f.stroke.dash&&!d.setLineDash&&!d.mozCurrentTransform){l=d;u=i;var s=g,q=m,w=t;e=void 0;e=[10,5];l.save();var q=q-u,p=w-s,w=Math.sqrt(q*q+p*p),q=Math.atan2(p,q);l.translate(u,s);l.moveTo(0,0);l.rotate(q);s=e.length;q=0;p=!0;for(u=0;w>u;)u+=e[q++%s],u>w&&(u=w),p?l.lineTo(u,0):l.moveTo(u,0),p=!p;l.restore()}else d.moveTo(i,
g),d.lineTo(m,t);c+=this.increm}f.stroke.prepare();f.shadow.prepare(d);d.stroke()};this.roundMin=function(){var a=this.minimum/this.increm|0;return this.increm*(0>=this.minimum?a:1+a)};this.drawTicks=function(d,e,c){var f=this.roundMin(),i=1+d.length,g=1;if(b&&a||!b&&!a)i=-i,g=-1;var i=i*e+this.axisPos,g=g*e+this.axisPos,m,t=1,l=0;0==c?m=this.increm:(t+=c,m=this.increm/t);var w=this.chart.ctx;for(w.beginPath();f<=this.maximum;){if(0==c||0!=l++%t)e=this.calc(f),b?(w.moveTo(e,g),w.lineTo(e,i)):(w.moveTo(g,
e),w.lineTo(i,e));f+=m}d.stroke.prepare();w.stroke()};this.drawTitle=function(){var a=this.labels,d,e;""!=this.title.text&&(b?(e=this.axisPos+this.title.padding,this.ticks.visible&&(e+=this.ticks.length),a.visible&&(a.format.font.prepare(),d=a.format.textHeight("Wj"),a.alternate&&(d*=2),e+=d),d=this.startPos+0.5*this.axisSize-0.5*this.title.bounds.width,this.title.position.x=d,this.title.position.y=e,this.title.forceDraw()):(d=this.axisPos-this.title.bounds.height-this.title.padding,this.ticks.visible&&
(d-=this.ticks.length),a.visible&&(e=a.maxWidth,a.alternate&&(e*=2),d-=e),e=this.startPos+0.5*(this.axisSize+this.title.bounds.width)+this.title.bounds.height,a=this.chart.ctx,a.save(),a.translate(d,e),a.rotate(-Math.PI/2),a.textAlign="center",this.title.position.x=0,this.title.position.y=0,this.title.forceDraw(),a.restore()))};this.drawLabel=function(a,d){var b=this.labels,e=b.getLabel(a);d.width=b.format.textWidth(e);d.width>b.maxWidth&&(b.maxWidth=d.width);this.horizontal?d.x-=0.5*d.width:d.y+=
0.5*d.height;if(0!=b.rotation){var c=this.chart.ctx;c.save();c.translate(d.x,d.y);c.rotate(-Math.PI*b.rotation/180);c.textAlign="right";d.x=-8;d.y=3}"right"==b.format.font.textAlign&&(d.x-=d.width);b.format.drawText(d,e);0!=b.rotation&&this.chart.ctx.restore()};this.drawLabels=function(){var a=this.roundMin(),d=new q,b=this.axisPos,e=this.labels;e.maxWidth=0;e.format.font.prepare();var c=this.ticks.visible?this.ticks.length:0,c=c+e.padding;this.horizontal?this.otherSide?b-=c:b+=c:this.otherSide?b+=
c:b-=c;c=b;d.height=e.format.textHeight("Wj");for(var f=(e=e.alternate)?this.horizontal?-d.height:this.minmaxLabelWidth():0,i;a<=this.maximum;)i=this.calc(a),this.horizontal?(d.x=i,d.y=b):(d.x=b,d.y=i-0.5*d.height),e&&(b=b==c?this.otherSide?c+f:c-f:c),this.drawLabel(a,d),a+=this.increm};this.calc=function(a){a!==a?a=0:this.log?(a-=this.minimum,a=0>=a?0:Math.log(a)*this.scale):a=(a-this.minimum)*this.scale;return this.horizontal?this.inverted?this.endPos-a:this.startPos+a:this.inverted?this.startPos+
a:this.endPos-a};this.fromPos=function(a){var d=this.horizontal;this.inverted&&(d=!d);return this.minimum+(d?a-this.startPos:this.endPos-a)/this.scale};this.fromSize=function(a){return a/this.scale};this.calcSize=function(a){return Math.abs(this.calc(a)-this.calc(0))};this.calcMinMax=function(a,d){this.automatic=!1;var b=this.fromPos(a),e=this.fromPos(d),c;b>e&&(c=b,b=e,e=c);this.minimum=b;this.maximum=e};this.setMinMax=function(a,d){this.automatic=!1;this.minimum=a;this.maximum=d}}function S(c){this.chart=
c;this.transparent=!1;var b=this.format=new Tee.Format(c);b.fill="white";b.round.x=8;b.round.y=8;b.font.baseLine="top";b.shadow.visible=!0;this.title=new Tee.Annotation(c);this.title.transparent=!0;this.bounds=new q;this.position="right";this.visible=!0;this.inverted=!1;this.margin=this.padding=5;this.align=0;this.fontColor=!1;var a=this.dividing=new B(c);a.fill="";a.cap="butt";this.over=-1;this.symbol=new function(a){this.chart=a;var d=this.format=new Tee.Format(a),b=d.shadow;b.visible=!0;b.color=
"silver";b.width=2;b.height=2;this.padding=this.height=this.width=8;this.style="rectangle";this.visible=!0;this.draw=function(b,e,c,f){var i=a.ctx,h;a:{if(b.hover.enabled&&((h=a.legend.showValues())&&b.over==e||!h&&0<=b.over)){h=b.hover;break a}h=null}var g=d.fill,j=d.stroke;d.fill=b.isColorEach&&-1!=e?b.getFill(e):b.format.fill;"rectangle"===this.style?(h&&(d.stroke=h.stroke),d.rectangle(c,f-0.5*this.height-1,this.width,this.height)):(i.beginPath(),i.moveTo(c,f),i.lineTo(c+this.width,f),h?h.stroke.prepare():
d.stroke.prepare(d.fill),i.stroke());d.fill=g;d.stroke=j}}(c);this.itemHeight=10;this.innerOff=0;this.textStyle=this.legendStyle="auto";this.totalWidth=function(){var a=j+8,d=this.symbol;d.visible&&(a+=d.width+d.padding);return a};var d=0;this._space=function(){return this.bounds.y+d+0.01*this.margin*c.bounds.height};this.availRows=function(){var a=this._space()+0.5*this.itemHeight;a||(a=0);return(c.bounds.getBottom()-a)/this.itemHeight|0};this.itemsCount=function(){var a=c.series,d=a.visibleCount(),
b=c.bounds;if(0==d)return 0;"values"==this.legendStyle&&0<d?d=a.firstVisible().count():"auto"==this.legendStyle&&1<d||"series"==this.legendStyle||1==d&&(d=a.firstVisible().count());if(this.isVertical())(0.5+d)*this.itemHeight>b.height-this._space()&&(d=this.availRows());else{this.rows=1;var a=this.totalWidth(),e=this.calcPadding(b),e=b.width-2*e;d*a>e?(this.perRow=e/a|0,d>this.perRow&&(this.rows=1+(d/this.perRow|0),this.rows*this.itemHeight>b.height-this.bounds.y&&(this.rows=this.availRows(),d=this.rows*
this.perRow))):this.perRow=d}return d};this.showValues=function(){var a=this.legendStyle;return"values"==a||"auto"==a&&1==c.series.visibleCount()};this.itemText=function(a,d){var b=a.dataText(d,this.textStyle,!1,!0);return this.ongettext?this.ongettext(this,a,d,b):b};this.calcItemPos=function(a,b){var e=this.itemHeight,c=this.bounds;b.x=c.x;b.y=c.y+this.innerOff;this.isVertical()?(b.x+=c.width-6-this.innerOff,b.y+=0.4*e+a*e+d):(b.x+=this.innerOff+(1+a%this.perRow)*this.totalWidth(),b.y+=e*((a/this.perRow|
0)+0.25))};this.calcItemRect=function(a,b){var e=this.itemHeight,c=this.bounds;b.height=e;b.x=c.x;b.y=c.y;this.isVertical()?(b.width=c.width,b.y+=0.4*e+a*e+d):(b.width=this.totalWidth(),b.x+=this.innerOff+a%this.perRow*b.width,b.y+=e*((a/this.perRow|0)+0.25))};var e=new q;this.mousemove=function(a){var d=this.over;if(this.bounds.contains(a))for(var b=this.itemsCount(),c=0;c<b;c++){if(this.calcItemRect(c,e),e.contains(a)){d=c;break}}else d=-1;if(d!=this.over){if(this.onhover)this.onhover(this.over,
d);this.over=d;var f=this.chart;window.requestAnimFrame(function(){f.draw()})}};this.drawSymbol=function(a,d,b){var e=this.symbol;e.draw(a,d,b.x-j-e.width-e.padding,b.y+0.4*this.itemHeight)};var i={x:0,y:0},f=new q,g;this.drawItem=function(a,d,e,y){var m=this.isVertical();this.calcItemPos(e,i);f.x=i.x;f.y=i.y;m?f.y-=this.chart.isMozilla?0:2:this.chart.isMozilla?f.y++:f.y--;var t=b.font.fill;this.over==e?b.font.fill="red":this.fontColor&&(b.font.fill=this.showValues()?d.getFill(e):d.format.fill);var l=
this.chart.ctx;if(y)b.font.textAlign="start",f.x-=h[0],l.textAlign=b.font.textAlign,b.drawText(f,a);else if(a instanceof Array||(a=[a]),m){for(var y=a.length,m=f.width,s=b.textWidth(" ");y--;)b.font.textAlign=g[y]?"start":"end",f.x-=h[y],l.textAlign=b.font.textAlign,b.drawText(f,a[y]),f.width-=h[y]+s;f.width=m}else b.font.textAlign="start",f.x-=j,l.textAlign=b.font.textAlign,b.drawText(f,a.join(" "));b.font.fill=t;l=!d.isColorEach||this.showValues();this.symbol.visible&&l&&this.drawSymbol(d,e,i);
0<e&&""!=this.dividing.fill&&(l=c.ctx,d=this.bounds,l.beginPath(),this.isVertical()?(l.moveTo(d.x,f.y-2),l.lineTo(d.getRight(),f.y-2)):(e=f.x-j-4,a=this.symbol,a.visible&&(e-=a.width+a.padding),l.moveTo(e,d.y),l.lineTo(e,d.getBottom())),this.dividing.prepare(),l.stroke())};this.drawSeries=function(a,d){var b=c.series.items[a];return b.visible?(this.drawItem(""==b.title?"Series "+a.toString():b.title,b,d,!0),!0):!1};this.draw=function(){var a=this.itemsCount(),e,i;e=this.title;var h=c.ctx,m,t=this.format.transparency,
l=this.isVertical();if(0<a){this.transparent||b.rectangle(this.bounds);0<t&&(m=h.globalAlpha,h.globalAlpha=(1-t)*m);l&&0<d&&(e.bounds.x=this.bounds.x-4,e.bounds.y=this.bounds.y,e.doDraw());b.font.prepare();f.width=j;f.height=this.itemHeight;if(this.showValues()){l=c.series.firstVisible();i=0;e=a;switch(this.textStyle){case "auto":case "percentlabel":case "valuelabel":g=[!1,!0];break;case "labelpercent":case "labelvalue":g=[!0,!1];break;case "label":g=[!0];break;default:g=[!1]}if(this.inverted)for(;e--;)this.drawItem(this.itemText(l,
e),l,i++);else for(i=0;i<e;i++)this.drawItem(this.itemText(l,i),l,i)}else if(e=c.series.count(),l&&(e=Math.min(e,this.availRows())),a=0,g=[!0],this.inverted)for(;e--;)this.drawSeries(e,a)&&a++;else for(i=0;i<e;i++)this.drawSeries(i,a)&&a++;0<t&&(h.globalAlpha=m)}};var j,h;this.calcWidths=function(){var a,d,e,f,i=c.series;j=0;h=[0,0];if(this.showValues()){a=i.firstVisible();f=this.itemsCount();for(d=0;d<f;d++)i=this.itemText(a,d),i instanceof Array||(i=[i]),0<i.length&&(e=b.textWidth(i[0]),e>h[0]&&
(h[0]=e),1<i.length&&(e=b.textWidth(i[1]),e>h[1]&&(h[1]=e)))}else{f=i.count();for(d=0;d<f;d++)a=i.items[d],a.visible&&(e=b.textWidth(a.title),e>h[0]&&(h[0]=e))}j=h[0]+h[1]};this.calcPadding=function(a){return 0.01*this.padding*(this.isVertical()?a.width:a.height)};this.isVertical=function(){return"right"==this.position||"left"==this.position};this.calcrect=function(){var a=0,e=this.title,f=c.chartRect,i=this.align,h=this.bounds,g=this.isVertical();e.visible&&""!=e.text?(e.resize(),d=e.bounds.height,
a=e.bounds.width):d=0;g?h.y=0==i?f.y:0.01*c.bounds.height*i:h.x=0==i?f.x:0.01*c.bounds.width*i;b.font.prepare();this.itemHeight=b.textHeight("Wj");this.calcWidths();var i=this.calcPadding(f),l=this.itemsCount();g?(g=this.symbol.visible?this.symbol.width+this.symbol.padding:0,h.width=Math.max(a,12+j+g),h.height=(0.5+l)*this.itemHeight+d,h.width-6>a&&(e.bounds.width=h.width-6)):(h.width=i+this.perRow*this.totalWidth(),h.x+=0.5*(f.width-h.width),h.height=this.itemHeight*(this.rows+0.25));""!=b.stroke.fill&&
(g=+b.stroke.size,1<g&&(h.width+=g,h.height+=g,this.innerOff=0.5*g));0!=l&&("right"==this.position?(h.x=f.getRight()-h.width-0.01*this.margin*h.width,f.setRight(Math.max(f.x,h.x-i))):"left"==this.position?(h.x=f.x,f.setLeft(h.x+h.width+i)):"top"==this.position?(h.y=f.y+i,f.setTop(h.getBottom()+i)):(h.y=f.getBottom()-h.height-i,f.setBottom(h.y-i)))}}function K(c,b){Tee.Annotation.call(this,b);this.series=c;this.arrow=new Tee.Format(b);this.arrow.length=10;this.arrow.underline=!1;this.style="auto";
this.drawEvery=1;this.visible=!1;this.setChart=function(a){this.chart=a;this.format.setChart(a);this.arrow.setChart(a)};this.drawPolar=function(a,d,b,c){var f=this.series.markText(c),c=a.x+Math.cos(b)*d,g=a.y+Math.sin(b)*d,j=this.chart.ctx;this.text=f;this.resize();var f=this.bounds,h,n=this.position,d=d+this.arrow.length;h=a.x+Math.cos(b)*d;d=a.y+Math.sin(b)*d;0>h-f.width&&(h-=h-f.width-4);n.x=Math.abs(h-a.x)<f.width?h-0.5*f.width:h<a.x?h-f.width:h;n.y=Math.abs(d-a.y)<f.height?d-0.5*f.height:d<a.y?
d-f.height:d;j.beginPath();j.moveTo(c,g);j.lineTo(h,d);if(this.arrow.underline&&(d<=n.y||d>=n.y+f.height))j.moveTo(n.x,d),j.lineTo(n.x+f.width,d);this.arrow.stroke.prepare();j.stroke();this.draw()};this.canDraw=function(a,d,b,c){var f=this.series.markText(b),b=this.arrow;if(f&&""!=f&&(this.showZero||"0"!=f)){this.text=f;this.resize();var f=c?-1:1,g=this.bounds;this.series.yMandatory?(g.x=a-0.5*g.width,g.y=d-f*(b.length+(c?0:g.height))):(g.x=a+f*b.length,c&&(g.x-=g.width),g.y=d-0.5*g.height);this.position.x=
g.x;this.position.y=g.y;return!0}return!1};this.drawMark=function(a,d,b,c){if(this.canDraw(a,d,b,c)){this.draw();var b=this.bounds,f=this.series.yMandatory,g=this.arrow,j=c?b.y:b.getBottom(),h=this.chart.ctx;h.beginPath();f?(h.moveTo(a,j),h.lineTo(a,d),g.underline&&(h.moveTo(b.x,j),h.lineTo(b.x+b.width,j))):(d=b.y+0.5*b.height,h.moveTo(a,d),c&&(b.x+=b.width),h.lineTo(b.x,d),g.underline&&(h.moveTo(b.x,b.y+b.height),h.lineTo(b.x+(c?-b.width:b.width),b.y+b.height)));g.stroke.prepare();h.stroke()}}}function T(c){for(var b=
0,a=c.length;a--;)b+=c[a];return b}function L(c){this.chart=c;this.items=[];this.count=function(){return this.items.length};this.clicked=function(b){var a=!1;this.each(function(d){if(d.visible&&d.onclick){var e=d.clicked(b);-1!=e&&(a=d.onclick(d,e,b.x,b.y))}});return a};this.mousedown=function(b){for(var a=0,d,e=!1;d=this.items[a++];)d.visible&&d.mousedown(b)&&(e=!0);return e};this.mousemove=function(b){for(var a=0,d;d=this.items[a++];)d.visible&&d.mousemove(b)};this.mouseout=function(){this.each(function(b){b.visible&&
b.mouseout()})};this.visibleCount=function(b,a,d){for(var e=0,c=this.items.length,f;c--,f=this.items[c];)if(f.visible&&(!a||f instanceof a))d&&f==b&&(d.index=e),e++;d&&(d.total=e,d.index=d.total-1-d.index);return e};this.beforeDraw=function(){this.each(function(b){b.useAxes&&b.recalcAxes();b.calcColorEach()})};this.anyUsesAxes=function(){for(var b=this.items.length,a;b--;)if(a=this.items[b],a.visible&&a.useAxes)return!0;return!1};this.firstVisible=function(){for(var b=0,a;a=this.items[b++];)if(a.visible)return a;
return null};this.vertMargins=function(){var b,a=this.items,d=a.length,e,c;if(0<d){b={x:0,y:0};e={x:0,y:0};a[0].vertMargins(b);for(c=1;c<d;c++)e.x=e.y=0,a[c].vertMargins(e),e.x>b.x&&(b.x=e.x),e.y>b.y&&(b.y=e.y)}return b};this.horizMargins=function(){var b,a=this.items,d=a.length,e,c;if(0<d){b={x:0,y:0};e={x:0,y:0};a[0].horizMargins(b);for(c=1;c<d;c++)e.x=e.y=0,a[c].horizMargins(e),e.x>b.x&&(b.x=e.x),e.y>b.y&&(b.y=e.y)}return b};this.minXValue=function(b){for(var a=Infinity,d=this.items.length,e;d--;)if(e=
this.items[d],e.visible&&(!b||e.associatedToAxis(b)))e=e.minXValue(),e<a&&(a=e);return a};this.minYValue=function(b){for(var a=Infinity,d=this.items.length,e;d--;)if(e=this.items[d],e.visible&&(!b||e.associatedToAxis(b)))e=e.minYValue(),e<a&&(a=e);return a};this.maxXValue=function(b){for(var a=-Infinity,d=this.items.length,e;d--;)if(e=this.items[d],e.visible&&(!b||e.associatedToAxis(b)))e=e.maxXValue(),e>a&&(a=e);return a};this.maxYValue=function(b){for(var a=-Infinity,d=this.items.length,e;d--;)if(e=
this.items[d],e.visible&&(!b||e.associatedToAxis(b)))e=e.maxYValue(),e>a&&(a=e);return a};this.draw=function(){var b=this.items.length,a=this.chart,d=a.ctx,e=a.aspect,c,f;if(0<b){var g=e.clip&&this.anyUsesAxes();g&&e.clipRect(a.chartRect);try{for(c=0;c<b;c++)if(f=this.items[c],f.visible){var j=d.globalAlpha;d.globalAlpha=1-f.format.transparency;f.transform&&(d.save(),f.transform());f.draw();if(f.ondraw)f.ondraw(f);f.transform&&d.restore();d.globalAlpha=j}}finally{g&&d.restore()}for(c=0;c<b;c++)f=
this.items[c],f.visible&&f.marks.visible&&(f.transform&&(d.save(),f.transform()),f.drawMarks(),f.transform&&d.restore())}}}function U(c){this.chart=c;this.visible=!0;this.transparency=0;this.left=new v(c,!1,!1);this.top=new v(c,!0,!0);this.right=new v(c,!1,!0);this.bottom=new v(c,!0,!1);this.items=[this.left,this.top,this.right,this.bottom];this.each=function(b){for(var a=0,d;d=this.items[a++];)b.call(d)};this.add=function(b,a){var d=new v(c,b,a);d.custom=!0;this.items.push(d);return d}}"undefined"!==
typeof exports&&(exports.Tee=Tee);"undefined"!==typeof window&&(window.requestAnimFrame=window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(c){window.setTimeout(c,1E3/60,(new Date).getTime())});var x;try{Object.defineProperty({},"x",{}),x=Object.defineProperty}catch(V){}"indexOf"in Array.prototype||(Array.prototype.indexOf=function(c,b){void 0===b&&(b=0);0>b&&(b+=this.length);0>b&&
(b=0);for(var a=this.length;b<a;b++)if(b in this&&this[b]===c)return b;return-1});q.prototype.set=function(c,b,a,d){this.x=c;this.y=b;this.width=a;this.height=d};q.prototype.setFrom=function(c){this.x=c.x;this.y=c.y;this.width=c.width;this.height=c.height};q.prototype.getRight=function(){return this.x+this.width};q.prototype.getBottom=function(){return this.y+this.height};q.prototype.setTop=function(c){this.height-=c-this.y;this.y=c};q.prototype.setBottom=function(c){this.height=c-this.y};q.prototype.setLeft=
function(c){this.width-=c-this.x;this.x=c};q.prototype.setRight=function(c){this.width=c-this.x};q.prototype.contains=function(c){return c.x>=this.x&&c.x<=this.x+this.width&&c.y>=this.y&&c.y<=this.y+this.height};Tee.Tool=function(c){this.chart=c;this.active=!0};Tee.Animation=function(c,b){Tee.Tool.call(this,c);this.active=!0;this.mode="linear";this.duration=500;this.items=[];this.running=!1;this.onstop=this.onstart=null;c&&(c instanceof Tee.Chart?this.chart=c:c instanceof Tee.Animation&&(this.chart=
c.chart,c.items.push(this)));var a=null;this.animate=function(d){if(!this.running){this.running=!0;d&&(this.chart=d);this.init=(new Date).getTime();a=this;a.start();for(var d=0,b;b=a.items[d++];)b.active&&(b.chart=a.chart,b.start());a.chart.draw();requestAnimFrame(this.step,this)}};this.start=function(){if(this.onstart)this.onstart()};this.stop=function(){if(this.onstop)this.onstop()};this.doStep=function(a){b&&b(a)};this.step=function(){var d,b;d=((new Date).getTime()-a.init)/a.duration;var c="linear"==
a.mode?d:Math.pow(2,10*(d-1));if(0<=c&&1>c){a.doStep(c);for(d=0;b=a.items[d++];)b.active&&(b.chart=a.chart,b.doStep(c));a.chart.draw();requestAnimFrame(a.step,a)}else{a.stop();for(d=0;b=a.items[d++];)b.active&&(b.chart=a.chart,b.stop());if(a.onstop)a.onstop(a);a.running=!1;a.chart.draw()}}};Tee.Animation.prototype=new Tee.Tool;Tee.Tool.prototype.mousedown=function(){};Tee.Tool.prototype.mousemove=function(){};Tee.Tool.prototype.mouseout=function(){};Tee.Tool.prototype.clicked=function(){return!1};
Tee.Tool.prototype.draw=function(){};z.prototype.setEndColor=function(c){if(c&&""!==c)for(var b=1,a=this.colors.length;b<a;b++)this.colors[b]=c};A.prototype.set=function(c){this.visible=c.visible;this.color=c.color;this.blur=c.blur;this.width=c.width;this.height=c.height};C.prototype.getSize=function(){var c=this.style.split(" "),b,a;for(b=0;b<c.length;b++)if(a=parseFloat(c[b]))return a;return 20};C.prototype.setSize=function(c){var b="",a=this.style.split(" "),d;for(d=0;d<a.length;d++)parseFloat(a[d])?
b+=c.toString()+"px ":b+=a[d]+" ";this.style=b};C.prototype.prepare=function(){var c=this.chart.ctx;c.textAlign=this.textAlign;c.textBaseline=this.baseLine;this._sh&&this._sh.prepare(c);c.font!=this.style&&(c.font=this.style)};C.prototype.setChart=function(c){this.chart=c;this._g&&(this._g.chart=c);this._sh&&(this._sh.chart=c);this._s&&this._s.setChart(c)};Tee.Format=function(c){this.chart=c;this.gradient=new z(c);this.fill="rgb(200,200,200)";this.stroke=new B(c);this.round={x:0,y:0};this.transparency=
0;this.font=new C(c);this._img=null;x?x(this,"image",{get:function(){this._img||(this._img=new J(this.chart));return this._img}}):this._img=this.image=new J(c);this.shadow=new A(c);this.roundRect=function(a,d,b,c,f){if(a.roundRect)a.roundRect(d,b,c,f,this.round.x,this.round.y);else{var g=d+c,j=b+f,h=this.round.x,n=this.round.y,k=this.round.corners;0>f&&(b=j,j=b-f);0>c&&(d=g,g=d-c);2*h>c&&(h=0.5*c);2*n>f&&(n=0.5*f);!k||k[0]?a.moveTo(d+h,b):a.moveTo(d,b);!k||k[1]?(a.lineTo(g-h,b),a.quadraticCurveTo(g,
b,g,b+n)):a.lineTo(g,b);!k||k[2]?(a.lineTo(g,j-n),a.quadraticCurveTo(g,j,g-h,j)):a.lineTo(g,j);!k||k[3]?(a.lineTo(d+h,j),a.quadraticCurveTo(d,j,d,j-n)):a.lineTo(d,j);!k||k[0]?(a.lineTo(d,b+n),a.quadraticCurveTo(d,b,d+h,b)):a.lineTo(d,b);a.closePath()}};this.textHeight=function(){return 1.3*this.font.getSize()};this.textWidth=function(a){return this.chart.ctx.measureText(a).width};this.draw=function(a,d,b,c,f,g){var j=this._img,h;0<this.transparency&&(h=a.globalAlpha,a.globalAlpha=(1-this.transparency)*
h);this.shadow.prepare(a);j&&j.visible&&""!=j.url?(a.save(),a.clip(),d?(d=d(),j.tryDraw(d.x,d.y,d.width,d.height)):j.tryDraw(b,c,f,g),a.restore()):(a.fillStyle=this.gradient.visible?d?this.gradient.create(d()):this.gradient.rect(b,c,f,g):this.fill,a.fill());""!=this.stroke.fill&&(this.stroke.prepare(),a.stroke());0<this.transparency&&(a.globalAlpha=h)};this.drawText=function(a,d){function b(a){f.fillText(a,h,n);g&&""!=g.fill&&(g.prepare(),f.strokeText(a,h,n))}var c=this.font._g,f=this.chart.ctx,g=
this.font._s,j=this.font.textAlign,h=a.x,n=a.y;f.fillStyle=c&&c.visible&&a?c.create(a):this.font.fill;if("center"==j)h+=0.5*a.width;else if("right"==j||"end"==j)h+=a.width;c=d.split("\n");j=c.length;if(1<j)for(var k=this.textHeight(c[0]),r=0;r<j;r++)b(c[r]),n+=k;else b(d)};this.rectPath=function(a,b,c,i){var f=this.chart.ctx;f.beginPath();0<this.round.x&&0<this.round.y?this.roundRect(f,a,b,c,i):f.rect(a,b,c,i)};this.rectangle=function(a,b,c,i){1>this.transparency&&("object"===typeof a?this.rectangle(a.x,
a.y,a.width,a.height):(this.rectPath(a,b,c,i),this.draw(this.chart.ctx,null,a,b,c,i)))};var b=new q;this.polygon=function(a){var d=this.chart.ctx,c=a.length,i;d.beginPath();d.moveTo(a[0].x,a[0].y);for(i=1;i<c;i++)d.lineTo(a[i].x,a[i].y);d.closePath();this.draw(d,function(){var d=0,c=0,e=0,h=0,i=a.length,k,r;if(0<i){d=e=a[0].x;c=h=a[0].y;for(r=1;r<i;r++)k=a[r].x,k<d?d=k:k>e&&(e=k),k=a[r].y,k<c?c=k:k>h&&(h=k)}b.x=d;b.y=c;b.width=e-d;b.height=h-c;return b})};this.ellipsePath=function(a,b,c,i,f){a.save();
a.translate(b,c);a.scale(0.5*i,0.5*f);a.beginPath();a.arc(0,0,1,0,2*Math.PI,!1);a.restore()};this.ellipse=function(a,b,c,i){var f=this.chart.ctx;this.ellipsePath(f,a,b,c,i);this.draw(f,null,a-0.5*c,b-0.5*i,c,i)}};Tee.Format.prototype.setChart=function(c){this.chart=c;this.shadow.chart=c;this.gradient.chart=c;this.font.setChart(c);this._img&&(this._img.chart=c);this.stroke.setChart(c)};Tee.Annotation=function(c,b,a,d){Tee.Tool.call(this,c);this.position=new s(a||10,d||10);var e=this.margins=new I;
this.items=[];var i=this.bounds=new q;this.visible=!0;this.transparent=!1;this.text=b||"";var f=this.format=new Tee.Format(c);f.font.textAlign="center";f.font.baseLine="top";f.fill="beige";f.round={x:4,y:4};f.stroke.fill="silver";f.shadow.visible=!0;var g,j,h;this.moveTo=function(a,b){this.position.x=a;this.position.y=b;this.resize()};this.resize=function(){if(this.text){f.font.prepare();this.rows=this.text.split("\n");g=f.textHeight(this.text);var a=this.rows.length;j=g*a+e.top;var b,d=j+e.bottom;
if(1<a)for(b=0;a--;)b=Math.max(b,f.textWidth(this.rows[a]+"W"));else b=f.textWidth(this.text+"W");b+=e.left+e.right;var a=this.position,c=a.y+j,h,t;for(h=0;t=this.items[h++];){var l=t.bounds;t.resize();d+=l.height;b=Math.max(b,l.width);l.x=a.x;l.y=c;c+=l.height}for(h=0;t=this.items[h++];)t.bounds.width=b-e.right;i.set(a.x,a.y,b,d)}};this.add=function(a){a=new Tee.Annotation(this.chart,a);this.items.push(a);a.transparent=!0;return a};this.doDraw=function(){if(""!=this.text){this.transparent||f.rectangle(i);
var a,b=this.format.transparency,d=this.chart?this.chart.ctx:null;0<b&&(a=d.globalAlpha,d.globalAlpha=(1-b)*a);f.font.prepare();i.y+=e.top+0.1*g;i.x+=e.left;var c=i.width;i.width-=e.right;f.drawText(i,this.text);i.x=this.position.x;i.y=this.position.y;i.width=c}for(var c=0,h;h=this.items[c++];)h.doDraw();0<b&&(d.globalAlpha=a)};this.clicked=function(a){return this.visible&&i.contains(a)};this.doMouseMove=function(a){(this.mouseinside=this.clicked(a))?(this.cursor&&(this.chart.newCursor=this.cursor),
this.wasinside||(h=new N(250,i,f))):this.wasinside&&(h.restore(),this.chart.draw());this.wasinside=this.mouseinside};this.mousemove=function(a){this.cursor&&"default"!=this.cursor&&this.doMouseMove(a)};this.forceDraw=function(){this.resize();this.doDraw()}};Tee.Annotation.prototype=new Tee.Tool;Tee.Annotation.prototype.draw=function(){this.visible&&this.forceDraw()};Tee.DragTool=function(c){Tee.Tool.call(this,c);this.series=null;var b=this.target={series:null,index:-1};this.clicked=function(){b.series=
null;b.index=-1};var a=new s(0,0);this.mousedown=function(d){var c=this.chart.series.items,i=c.length;this.chart.calcMouse(d,a);b.series=null;b.index=-1;if(this.series&&this.series.visible)b.index=this.series.clicked(a),-1!=b.index&&(b.series=this.series);else for(d=0;d<i;d++)if(c[d].visible&&(b.index=c[d].clicked(a),-1!=b.index)){b.series=c[d];break}return-1!=b.index};this.mousemove=function(a){if(-1!=b.index){var c=b.series,a=c.mandatoryAxis.fromPos(c.yMandatory?a.y:a.x);this.onchanging&&(a=this.onchanging(this,
a));c.data.values[b.index]=a;if(this.onchanged)this.onchanged(this,a);this.chart.draw()}}};Tee.DragTool.prototype=new Tee.Tool;Tee.CursorTool=function(c){Tee.Tool.call(this,c);this.direction="both";this.size=new s(0,0);this.followMouse=!0;this.dragging=-1;this.format=new Tee.Format(c);this.horizAxis=c?c.axes.bottom:null;this.vertAxis=c?c.axes.left:null;var b,a=new q;this.over=function(d){var c=-1;if(a.contains(d)){var e=3>Math.abs(b.x-d.x),d=3>Math.abs(b.y-d.y),h=this.direction;if("both"==h&&e&&d)c=
0;else if(e&&("both"==h||"vertical"==h))c=1;else if(d&&("both"==h||"horizontal"==h))c=2}return c};this.calcRect=function(){var b=c.chartRect;a.x=this.horizAxis?this.horizAxis.startPos:b.x;a.width=this.horizAxis?this.horizAxis.endPos-a.x:b.width;a.y=this.vertAxis?this.vertAxis.startPos:b.y;a.height=this.vertAxis?this.vertAxis.endPos-a.y:b.height};var d=new s(0,0);this.mousedown=function(a){this.chart.calcMouse(a,d);this.dragging=this.followMouse?-1:this.over(d);return-1<this.dragging};this.clicked=
function(){this.dragging=-1};this.mousemove=function(d){var g=this.dragging,j=this.followMouse;if(j||-1<g)if(b||(b=new s),b.x!=d.x||b.y!=d.y)if(this.calcRect(),a.contains(d)){if(j||0==g||1==g)b.x=d.x;if(j||0==g||2==g)b.y=d.y;"full"==this.render?this.chart.draw():(e&&("copy"==this.render?this.chart.ctx.drawImage(e,0,0):(g=c.bounds,i.clearRect(g.x,g.y,g.width,g.height))),this.dodraw("copy"==this.render?this.chart.ctx:i));if(this.onchange)this.onchange(d);return}d=this.over(d);this.chart.newCursor=b&&
-1<d?0==d?"move":1==d?"e-resize":"n-resize":"default"};this.render="copy";var e,i;this.setRender=function(a){this.render=a;e&&(this.resetCopy(),this.chart.draw())};this.resetCopy=function(){var a=this.chart.canvas;"layer"==this.render?(e.style.position="absolute",a.parentNode.appendChild(e),e.style.left=a.offsetLeft,e.style.top=a.offsetTop,e.style.zIndex=10,e.style.pointerEvents="none"):e.parentNode&&e.parentNode.removeChild(e)};this.draw=function(){"full"==this.render?this.dodraw(this.chart.ctx):
(e||(e=this.chart.canvas.cloneNode(),this.resetCopy(),i=e.getContext("2d")),"copy"==this.render?(i.drawImage(c.canvas,0,0),this.dodraw(this.chart.ctx)):this.dodraw(i))};this.dodraw=function(d){var c=this.direction,e="both"==c,h;this.calcRect();b||(b=new s(a.x+0.5*a.width,a.y+0.5*a.height));d.beginPath();if(e||"vertical"==c)h=0.5*this.size.y,d.moveTo(b.x,0==h?a.y:b.y-h),d.lineTo(b.x,0==h?a.y+a.height:b.y+h);if(e||"horizontal"==c)h=0.5*this.size.x,d.moveTo(0==h?a.x:b.x-h,b.y),d.lineTo(0==h?a.x+a.width:
b.x+h,b.y);this.format.stroke.prepare(this.format.stroke.fill,d);d.stroke()}};Tee.CursorTool.prototype=new Tee.Tool;Tee.ToolTip=function(c){function b(){function a(b){d.moveTo(d.oldX+b*d.deltaX,d.oldY+b*d.deltaY);d.autoRedraw&&d.chart.draw()}var c=((new Date).getTime()-d.init)/d.animated;1>c?(a(c),window.requestAnimFrame(b,d)):a(1)}Tee.Annotation.call(this,c);this.visible=!1;this.currentSeries=null;this.currentIndex=-1;this.timID=null;this.autoHide=!1;this.delay=1E3;this.animated=100;this.autoRedraw=
!0;this.render="dom";this.hide=function(){if(this.visible||"dom"==this.render){if(this.onhide)this.onhide(this);this.visible=!1;this.autoRedraw&&("dom"==this.render?Tee.DOMTip.hide():this.chart.draw());this.currentIndex=-1;this.currentSeries=null}};var a=function(a){a&&a[0].hide()};this.mousemove=function(b){for(var d=this.chart.series,c=d.count(),g=null,j,h=0;h<c;h++){var n=d.items[h];if(n.visible&&(j=n.clicked(b),-1!=j)){g=n;break}}if(-1==j)this.hide(),this.currentIndex=-1,this.currentSeries=null;
else if(j!=this.currentIndex||g!=this.currentSeries)if(this.currentIndex=j,this.currentSeries=g)this.refresh(g,j),this.autoHide&&0<this.delay&&(clearTimeout(this.timID),this.timID=window.setTimeout(a,this.delay,[this]))};var d=null;this.refresh=function(a,c){this.visible="dom"!==this.render;this.text=a.markText(c);this.ongettext&&(this.text=this.ongettext(this,this.text,a,c));if(""!=this.text){this.resize();var f=new s;a.calc(c,f);f.x-=0.5*this.bounds.width;f.y-=1.5*this.bounds.height;0>f.x&&(f.x=
0);0>f.y&&(f.y=0);"dom"!==this.render&&!this.autoHide&&0<this.animated&&!isNaN(this.position.x)&&!isNaN(this.position.y)?(this.oldX=this.position.x,this.oldY=this.position.y,this.deltaX=f.x-this.oldX,this.deltaY=f.y-this.oldY,this.init=(new Date).getTime(),d=this,window.requestAnimFrame(b,this)):(this.moveTo(f.x,f.y),this.autoRedraw&&("dom"==this.render?Tee.DOMTip.show(this.text):this.chart.draw()));if(this.onshow)this.onshow(this,a,c)}}};Tee.ToolTip.prototype=new Tee.Annotation;Tee.RainbowPalette=
function(){return"#FF0000 #FF7F00 #FFFF00 #00FF00 #0000FF #6600FF #8B00FF".split(" ")};Tee.Palette=function(c){this.colors=c};Tee.Palette.prototype.get=function(c){return this.colors[-1==c?0:c%this.colors.length]};H.prototype=new Tee.Annotation;v.adjustRect=function(){if(this.visible){var c=0,b=this.labels,a=this.chart.chartRect;if((this.firstSeries=this.hasAnySeries())&&this.visible)this.checkMinMax(),b.checkStyle(),this.custom||(b.visible&&(b.format.font.prepare(),c=this.horizontal?b.format.textHeight("Wj"):
this.minmaxLabelWidth(),b.alternate&&(c*=2),c+=b.padding),this.ticks.visible&&(c+=this.ticks.length),b=this.title,b.visible&&(b.text&&""!=b.text)&&(b.resize(),c+=b.bounds.height),this.horizontal?this.otherSide?a.setTop(a.y+c):a.height-=c:this.otherSide?a.width-=c:a.setLeft(a.x+c))}};v.prototype.setPos=function(c,b){this.startPos=c+0.01*this.start*b;this.endPos=c+0.01*this.end*b;this.axisSize=this.endPos-this.startPos};v.calcRect=function(){if(this.firstSeries){this.checkMinMax();var c=this.chart.chartRect,
b=this.bounds;this.horizontal?(b.y=this.otherSide?c.y:c.y+c.height,b.width=c.width,this.setPos(c.x,c.width)):(b.x=this.otherSide?c.x+c.width:c.x,b.height=c.height,this.setPos(c.y,c.height));this.calcAxisScale();if(this.automatic){var b=this.chart.series,b=this.horizontal?b.horizMargins():b.vertMargins(),a=0<b.x,d=0<b.y;a&&(this.minimum-=this.fromSize(b.x));d&&(this.maximum+=this.fromSize(b.y));(a||d)&&this.calcAxisScale()}this.calcScale();b=this.horizontal?c.height:c.width;b*=0.01*this.position;this.axisPos=
this.horizontal?this.otherSide?c.y+b:c.getBottom()-b:this.otherSide?c.getRight()-b:c.x+b}};v.draw=function(){this.visible&&this.firstSeries&&(""!=this.format.stroke.fill&&this.drawAxis(),this.roundMin()+1E3*this.increm>this.maximum&&(this.grid.visible&&this.drawGrids(),this.ticks.visible&&this.drawTicks(this.ticks,1,0),this.innerTicks.visible&&this.drawTicks(this.innerTicks,-1,0),this.minorTicks.visible&&this.drawTicks(this.minorTicks,1,Math.max(0,this.minorTicks.count)),this.labels.visible&&this.drawLabels()),
this.title.visible&&(this.title.text&&""!=this.title.text)&&this.drawTitle())};K.prototype=new Tee.Annotation;Tee.Series=function(c,b){this.chart=null;this.data={values:[],labels:[],source:null};this.yMandatory=!0;this.horizAxis="bottom";this.vertAxis="left";var a=this.format=new Tee.Format(this.chart),d=this.hover=new Tee.Format(this.chart),e=d.shadow;a.fill="";a.stroke.fill="";this.visible=!0;d.stroke.size=3;d.fill="";d.stroke.fill="red";e.visible=!0;e.color="red";e.blur=10;e.width=0;e.height=0;
this.cursor="default";this.over=-1;this.marks=new K(this,this.chart);this.palette=new Tee.Palette;this.colorEach="auto";this.useAxes=!0;this.decimals=2;this.init=function(a,b){"object"===typeof a&&a&&(a instanceof Array?(this.data.values=a,b instanceof Array&&(this.data.labels=b)):a instanceof Tee.Chart?(this.chart=a,b instanceof Array&&(this.data.values=b)):(this.data.source=a,this.refresh()))};this.init(c,b);this.getFill=function(a,b){var d=this.palette,d=d&&d.colors?d.get(a):null;return null==
d?this.isColorEach||!b?this.chart.palette.get(a):b.fill:d};this.isNull=function(a){return null===this.data.values[a]};this.getFillStyle=function(b,d){return a.gradient.visible?a.gradient.create(b,d):d};this.recalcAxes=function(){var a=this.chart.axes;this._horizAxis=this.horizAxis instanceof v?this.horizAxis:"top"==this.horizAxis?a.top:a.bottom;this._vertAxis=this.vertAxis instanceof v?this.vertAxis:"right"==this.vertAxis?a.right:a.left;this.mandatoryAxis=this.yMandatory?this._vertAxis:this._horizAxis;
this.notmandatory=this.yMandatory?this._horizAxis:this._vertAxis};this.title="";this.refresh=function(a){this.data.source?this.data.source instanceof HTMLTextAreaElement?(parseText(this.data,this.data.source.value),this.chart&&this.chart.draw()):this.data.source instanceof HTMLInputElement?Tee.doHttpRequest(this,this.data.source.value,function(a,b){parseText(a.data,b);a.chart.draw()},function(b,d){a&&a(this,b,d)}):a&&a(this):this.data.xml?(parseXML(this,this.data.xml),this.chart.draw()):this.data.json&&
(parseJSON(this,this.data.json),this.chart.draw())};this.valueOrLabel=function(a){var b=this.data.labels[a];if(!b||""==b)b=this.valueText(a);return b};this.toPercent=function(a){var b=this.data.values;return(100*b[a]/T(b)).toFixed(this.decimals)+" %"};this.dataText=function(a,b,d,c){function e(a,b){return c?n?[a,b]:[a,""]:a+(b?" "+b:"")}var n=d?this.labelOrTitle(a):this.data.labels[a];return"value"==b?this.valueText(a):"percent"==b?this.toPercent(a):"percentlabel"==b?e(this.toPercent(a),n):"valuelabel"==
b||"auto"==b?e(this.valueText(a),n):"label"==b?n||"":"index"==b?a.toFixed(0):"labelvalue"==b?e(n,this.valueText(a)):"labelpercent"==b?e(n,this.toPercent(a)):this.valueOrLabel(a)};this.markText=function(a){var b=this.marks,d=this.dataText(a,b.style,!1);return b.ongettext?b.ongettext(this,a,d):d};this.valueText=function(a){return(a=(this.data._old||this.data.values)[a])?a instanceof Date?a.format(this.dateFormat):this.valueFormat?a.toLocaleString():(a|0)==a?a.toFixed(0):a.toFixed(this.decimals):"0"};
this.associatedToAxis=function(a){return a.horizontal?"both"==this.horizAxis||this._horizAxis==a:"both"==this.vertAxis||this._vertAxis==a};this.bounds=function(a){var b=this._horizAxis,d=this._vertAxis;a.x=b.calc(this.minXValue());a.width=b.calc(this.maxXValue())-a.x;a.y=d.calc(this.maxYValue());a.height=d.calc(this.minYValue())-a.y};this.calcStack=function(a,b,d){var d=this.pointOrigin(a,!1)+d,c=this.mandatoryAxis;b.x=this.notmandatory.calc(this.data.x?this.data.x[a]:a);this.isStack100?(a=this.pointOrigin(a,
!0),b.y=0==a?c.endPos:c.calc(100*d/a)):b.y=c.calc(d);this.yMandatory||(a=b.x,b.x=b.y,b.y=a)};this.pointOrigin=function(a,b){var d=0,c,e,n=this.chart.series.items,k;for(c=0;c<n.length&&!(e=n[c],!b&&e==this);c++)k=e.data.values,e.visible&&(e.constructor==this.constructor&&k.length>a)&&(e=k[a],void 0!==e&&(d+=b&&0>e?-e:e));return d};this.doHover=function(a){var b=this.chart;if(a!=this.over){if(b.onhover)b.onhover(this,a);this.over=a;this.hover.enabled&&window.requestAnimFrame(function(){b.draw()})}}};
Tee.Series.prototype.setChart=function(c,b){c.chart=b;c.recalcAxes();c.format.setChart(b);c.marks.setChart(b);c.hover.setChart(b)};Tee.Series.prototype.calc=function(c,b){var a=this.data,d=this.notmandatory.calc(a.x?a.x[c]:c),a=this.mandatoryAxis.calc(a.values[c]);b.x=this.yMandatory?d:a;b.y=this.yMandatory?a:d};Tee.Series.prototype.getRect=function(){return new q};Tee.Series.prototype.clicked=function(){return-1};Tee.Series.prototype.labelOrTitle=function(c){return this.data.labels[c]||this.title};
Tee.Series.prototype.mousedown=function(){return!1};Tee.Series.prototype.mousemove=function(c){if(this.hover.enabled||"default"!=this.cursor){var b=this.clicked(c);this.doHover(b);if("default"!=this.cursor&&-1!=b){this.chart.newCursor||(this.chart.newCursor=this.cursor);return}}b=this.marks;if(b.visible){var a=this.data.values.length,d=new s,e;for(e=0;e<a;e+=b.drawEvery)if(!this.isNull(e)&&(this.markPos(e,d),b.canDraw(d.x,d.y,e)&&b.bounds.contains(c))){this.doHover(e);break}}};Tee.Series.prototype.mouseout=
function(){};Tee.Series.prototype.markPos=function(c,b){this.calc(c,b);return!1};Tee.Series.prototype.drawMarks=function(){var c=this.data.values.length,b=new s,a,d;for(a=0;a<c;a+=this.marks.drawEvery)this.isNull(a)||(d=this.markPos(a,b),this.marks.drawMark(b.x,b.y,a,d))};Tee.Series.prototype.horizMargins=function(){};Tee.Series.prototype.vertMargins=function(){};Tee.Series.prototype.minXValue=function(){return this.data.x&&0<this.data.x.length?Math.min.apply({},this.data.x):0};Tee.Series.prototype.minYValue=
function(){var c=this.data.values;return 0<c.length?Math.min.apply({},c):0};Tee.Series.prototype.maxXValue=function(){if(this.data.x)return 0<this.data.x.length?Math.max.apply({},this.data.x):0;var c=this.data.values.length;return 0==c?0:c-1};Tee.Series.prototype.maxYValue=function(){var c=this.data.values,b=c.length,a,d,e;if(0<b){e=Math.max.apply({},c);if(e!==e)for(a=0;a<b;a++)d=c[a],void 0!==d&&(e!==e?e=d:d>e&&(e=d));return e===e?e:0}return 0};Tee.Series.prototype.calcColorEach=function(){this.isColorEach=
"yes"==this.colorEach};Tee.Series.prototype.stackMaxValue=function(){if("100"==this.stacked)return 100;var c=Tee.Series.prototype.maxYValue;if("no"==this.stacked)return c.call(this);for(var c=c.call(this),b=this.data.values,a=b.length,d;a--;)d=b[a],void 0===d&&(d=0),c=Math.max(c,this.pointOrigin(a,!1)+d);return c};Tee.Series.prototype.count=function(){return this.data.values.length};Tee.Series.prototype.addRandom=function(c,b,a){b||(b=1E3);var d=this.data;d.values.length=c;a&&(d.x=Array(c));if(0<
c){d.values[0]=Math.random()*b;a&&(d.x[0]=Math.random()*b);for(var e=1;e<c;e++)d.values[e]=d.values[e-1]+Math.random()*b-0.5*b,a&&(d.x[e]=Math.random()*b)}return this};Tee.Series.prototype.doSort=function(c,b){if("none"==c)return null;for(var a=this.data.values,d=a.length,e=Array(d),i=0;i<d;i++)e[i]=i;if("labels"==c){var a=this.data.labels,f,g,j=b?-1:1,h=b?1:-1;e.sort(function(b,d){f=a[b].toLowerCase();g=a[d].toLowerCase();return f<g?j:f==g?0:h})}else e.sort(b?function(b,d){return a[b]-a[d]}:function(b,
d){return a[d]-a[b]});return e};L.prototype.each=function(c){for(var b=this.items.length,a=0;a<b;a++)c(this.items[a])};Tee.Chart=function(c,b,a){function d(b){i.chart.addSeries(new (a||Tee.Bar)(i.chart)).data.values=b}var e="undefined"!=typeof navigator?navigator.userAgent.toLowerCase():"";this.isChrome=-1<e.indexOf("chrome");this.isAndroid=-1<e.indexOf("android");this.isMozilla=window.mozRequestAnimationFrame;c&&(this.canvas="undefined"!==typeof HTMLCanvasElement&&c instanceof HTMLCanvasElement?
c:"string"==typeof c?document.getElementById(c):c);this.canvas||(this.canvas=document.createElement("canvas"),this.canvas.width=600,this.canvas.height=400);var i=this.canvas;this.bounds=0==i.clientWidth?new q(0,0,i.width,i.height):new q(0,0,i.clientWidth,i.clientHeight);this.chartRect=new q;this.chartRect.setFrom(this.bounds);this.palette=new Tee.Palette("#4466a3 #f39c35 #f14c14 #4e97a8 #2b406b #1d7b63 #b3080e #f2c05d #5db79e #707070 #f3ea8d #b4b4b4".split(" "));this.aspect={chart:this,view3d:!1,
ortogonal:!0,rotation:0,elevation:315,perspective:50,clip:!0,clipRect:function(a){var b=this.chart.ctx;b.save();b.beginPath();b.rect(a.x,a.y,a.width,a.height);b.clip()}};this.panel=new R(this);this.walls={chart:this,visible:!0,left:new F(this),right:new F(this),bottom:new F(this),back:new F(this),draw:function(){var a,b=this.chart.ctx,d=this.transparency;0<d&&(a=b.globalAlpha,b.globalAlpha=(1-d)*a);!this.back.visible||this.back.draw();this.chart.aspect.view3d&&(this.left.visible&&this.left.draw(),
this.bottom.visible&&this.bottom.draw(),this.right.visible&&this.right.draw());0<d&&(b.globalAlpha=a)}};c=this.walls.back.format;c.fill="rgb(240,240,240)";c.shadow.visible=!0;this.axes=new U(this);this.legend=new S(this);this.series=new L(this);this.title=new H(this,"blue");this.title.text="TeeChart";this.footer=new H(this,"red");this.zoom=new P(this);this.scroll=new Q(this);this.tools=new O(this);this.oldPos=new s;this.calcMouse=function(a,b){if(null==a.pageX){var d=document.documentElement&&null!=
document.documentElement.scrollLeft?document.documentElement:document.body;b.x=a.clientX+d.scrollLeft;b.y=a.clientY+d.scrollTop}else b.x=a.pageX,b.y=a.pageY;d=this.canvas;if(d.getBoudingClientRect)d=d.getBoundingClientRect(),b.x-=d.left,b.y-=d.top;else if(d.offsetParent){do b.x-=d.offsetLeft,b.y-=d.offsetTop;while(d=d.offsetParent)}};var f=new s(0,0);this.domousemove=function(a){var b=this.chart;if(b.ctx){a=a||window.event;a.touches&&(a=a.touches[a.touches.length-1]);b.calcMouse(a,f);if(b.scroll.active){var d=
b.scroll.direction,c="both"==d,e;if(c||"horizontal"==d)e=b.axes.bottom.fromSize(b.oldPos.x-f.x),b.axes.top.scroll(e),b.axes.bottom.scroll(e);if(c||"vertical"==d)e=-b.axes.left.fromSize(b.oldPos.y-f.y),b.axes.left.scroll(e),b.axes.right.scroll(e);b.oldPos.x=f.x;b.oldPos.y=f.y;b.scroll.done=!0;if(b.onscroll)b.onscroll(a);b.scroll.done&&window.requestAnimFrame(function(){b.draw()});return!1}if(b.zoom.active){if(f.x!=b.oldPos.x||f.y!=b.oldPos.y)b.zoom.old||(b.zoom.old=new s),b.zoom.old.x=f.x-b.oldPos.x,
b.zoom.old.y=f.y-b.oldPos.y,window.requestAnimFrame(function(){b.draw()}),b.zoom.done=!0;return!1}b.newCursor=null;b.tools.mousemove(f);b.series.mousemove(f);b.legend.mousemove(f);b.title.mousemove(f);a=this.chart.canvas.style;b.newCursor?a.cursor!=b.newCursor&&(b.oldCursor=a.cursor,a.cursor=b.newCursor):void 0!=b.oldCursor&&a.cursor!=b.oldCursor&&(a.cursor=b.oldCursor);return!0}};var g=new s(0,0);this.domousedown=function(a){var a=a||window.event,b=!1,d=this.chart;d.calcMouse(a.touches?a.touches[0]:
a,g);var c=d.series.anyUsesAxes()&&d.chartRect.contains(g);a.touches?1<a.touches.length?(d.zoom.active=d.zoom.enabled&&c,d.zoom.active&&(d.scroll.active=!1)):(d.scroll.active=d.scroll.enabled&&c,d.scroll.active&&(d.zoom.active=!1)):(d.zoom.active=a.button==d.zoom.mouseButton&&d.zoom.enabled&&c,d.scroll.active=a.button==d.scroll.mouseButton&&d.scroll.enabled&&c);d.zoom.done=!1;d.scroll.done=!1;d.oldPos=g;0==a.button?((b=d.tools.mousedown(a))||(b=d.series.mousedown(a)),d.canvas.oncontextmenu=null):
2==a.button&&(d.canvas.oncontextmenu=function(){return!1});b?d.zoom.active=d.scroll.active=!1:b=d.zoom.active||d.scroll.active;a.preventDefault();b&&a.target.setCapture&&a.target.setCapture();return!b};this.domouseup=function(a){var a=a||window.event,b=this.chart,d;b.zoom.active=!1;b.scroll.active=!1;if(b.zoom.done){if(b.zoom.apply()&&b.onzoom)b.onzoom();b.draw();d=!0}else if(d=b.scroll.done,!d&&(d=b.series.clicked(b.oldPos),!d&&(d=b.tools.clicked(b.oldPos),!d&&(d=b.title.clicked(b.oldPos))&&b.title.onclick)))b.title.onclick(b.title);
b.zoom.old=null;b.zoom.done=!1;b.scroll.done=!1;d?a.preventDefault():b.canvas.oncontextmenu=null;a.target.releaseCapture&&a.target.releaseCapture()};i.onmousedown=i.ontouchstart=this.domousedown;i.onmouseup=i.ontouchstop=this.domouseup;i.onmousemove=i.ontouchmove=this.domousemove;i.onmouseout=function(a){a&&!a.target.setCapture&&(this.chart.scroll.active=!1);this.chart.series.mouseout();this.chart.tools.mouseout()};this.addSeries=function(a){a.setChart(a,this);var b=this.series.items,d=b.indexOf(a);
-1==d&&(d=b.push(a)-1);""==a.title&&(a.title="Series"+(1+d).toString());""==a.format.fill&&(a.format.fill=this.palette.get(d));return a};this.removeSeries=function(a){var b=this.series.items,a=b.indexOf(a);-1!=b&&b.splice(a,1)};i.chart=this;if(b&&0<b.length)if(b[0]instanceof Array)for(c=0;c<b.length;c++)d(b[c]);else d(b);this.getSeries=function(a){return this.series.items[a]};this.draw=function(a){this.ctx=a||(this.canvas.getContext?this.canvas.getContext("2d"):null);if(!this.ctx)throw"Canvas does not provide Context";
this.chartRect.setFrom(this.bounds);this.panel.draw();this.panel.margins.apply(this.chartRect);this.title.tryDraw(!0);this.footer.tryDraw(!1);this.series.beforeDraw();this.legend.visible&&(this.legend.calcrect(),this.legend.draw());var a=this.axes,b;a.visible&&this.series.anyUsesAxes()&&(a.each(v.adjustRect),a.each(v.calcRect),this.walls.visible&&(this.walls.back.bounds.setFrom(this.chartRect),this.walls.draw()),0<a.transparency&&(b=this.ctx.globalAlpha,this.ctx.globalAlpha=(1-a.transparency)*b),
a.each(v.draw),0<a.transparency&&(this.ctx.globalAlpha=b));this.series.draw();this.tools.draw();this.zoom.active&&this.zoom.draw();if(this.ondraw)this.ondraw(this)};this.toImage=function(a,b,d){if(a=document.getElementById(a))a.src=""!=b?this.canvas.toDataURL(b,d):this.canvas.toDataURL()}};Tee.CustomBar=function(c,b){Tee.Series.call(this,c,b);this.sideMargins=100;this.useOrigin=!0;this.origin=0;this.marks.visible=!0;this.marks.location="end";this.hover.enabled=!0;this.offset=0;this.barSize=70;this.barStyle=
"bar";var a=this.format;a.fill="";a.stroke.fill="black";a.shadow.visible=!0;a.round.x=4;a.round.y=4;a.gradient.visible=!0;this.stacked="no";this.drawBar=function(b){if("bar"==this.barStyle)a.rectPath(b.x,b.y,b.width,b.height);else if("line"==this.barStyle){var d;this.yMandatory?(d=b.x+0.5*b.width,a.rectPath(d,b.y,1,b.height)):(d=b.y+0.5*b.height,a.rectPath(b.x,d,b.width,1))}else a.ellipsePath(this.chart.ctx,b.x+0.5*b.width,b.y+0.5*b.height,b.width,b.height)};this.countAll=function(a){var b=0,d=this.chart.series.items.length,
c,e;for(c=0;c<d&&!(e=this.chart.series.items[c],e==this&&a);c++)e.visible&&e.constructor==this.constructor&&(b+=e.data.values.length);return b};var d=new s,e,i=new q,f={total:0,index:0};this._margin=0;this.calcBarOffset=function(a){this.countall="sideAll"==this.stacked?this.countAll(!0):0;var b;b="sideAll"==this.stacked?this.countAll():this.data.values.length;1<b&&(a/=b-1);"no"==this.stacked?(a/=f.total,d.x=a*(1==f.total?-0.5:f.index-0.5*f.total),b=f.total):(d.x=0.5*-a,b=1);d.y=0.01*a*this.barSize;
this._margin=0.5*b*d.y+0.0050*this.sideMargins*b*(a-d.y);d.x+=0.01*this.offset*a+0.5*(a-d.y)};this.calcStackPos=function(a,b){var d,c,f;this.isStacked?(this.calcStack(a,b,this.data.values[a]),d=this.pointOrigin(a,!1),f=this.mandatoryAxis,this.isStack100?(c=this.pointOrigin(a,!0),e=0==c?f.endPos:f.calc(100*d/c)):e=f.calc(d)):(this.calc(a,b),"sideAll"==this.stacked&&(c=this.notmandatory.calc(this.countall+a),this.yMandatory?b.x=c:b.y=c))};this.draw=function(){var b=this.data.values.length;if(0<b){this.initOffsets();
var c=new s,f=this.chart.ctx;this.hover.enabled||(a.stroke.prepare(),a.shadow.prepare(f));for(var n=0;n<b;n++)if(!this.isNull(n)){this.calcStackPos(n,c);this.calcBarBounds(c,i,d,e);this.drawBar(i);var k=this.hover.enabled&&this.over==n?this.hover:a;f.fillStyle=this.getFillStyle(i,this.getFill(n,k));this.hover.enabled&&k.shadow.prepare(f);f.fill();""!=k.stroke.fill&&(this.hover.enabled&&k.stroke.prepare(),f.shadowColor="transparent",f.stroke(),k.shadow.visible&&(f.shadowColor=k.shadow.color))}}};this.calcColorEach=
function(){this.chart.series.visibleCount(this,Tee.CustomBar,f);this.isColorEach="yes"==this.colorEach||"auto"==this.colorEach&&1==f.total};this.initOffsets=function(){var a=this.notmandatory,b=this.mandatoryAxis,d=this.yMandatory?this.maxXValue()-this.minXValue():this.maxYValue()-this.minYValue();this.calcBarOffset(0==d?a.axisSize:a.calcSize(d));e=this.useOrigin?b.calc(this.origin):this.yMandatory?b.inverted?b.startPos:b.endPos:b.inverted?b.endPos:b.startPos;this.isStacked="no"!=this.stacked&&"sideAll"!=
this.stacked;this.isStack100="100"==this.stacked};this.clicked=function(a){this.initOffsets();var b=new s,c=this.data.values.length,f;for(f=0;f<c;f++)if(!this.isNull(f)&&(this.calcStackPos(f,b),this.calcBarBounds(b,i,d,e),i.contains(a)))return f;return-1};this.markPos=function(a,b){var c=this.yMandatory,f=d.x+0.5*d.y,k=this.marks;this.calcStackPos(a,b);if("sideAll"==this.stacked){var r=this.notmandatory.calc(this.countall+a);c?b.x=r:b.y=r}r=this.useOrigin&&this.data.values[a]<this.origin;this.mandatoryAxis.inverted&&
(r=!r);"center"==k.location&&(this.calcBarBounds(b,i,d,e),k.canDraw(b.x,b.y,a,r)&&(c?b.y=i.y+0.5*i.height+0.5*k.bounds.height:b.x=i.x+0.5*i.width-0.5*k.bounds.width));c?b.x+=f:b.y+=f;return r};this.drawMarks=function(){var a=this.data.values.length,b=this.marks,d=new s,c;if(0<a)for(var e=0;e<a;e+=b.drawEvery)this.isNull(e)||(c=this.markPos(e,d),b.drawMark(d.x,d.y,e,c))};this.labelOrTitle=function(a){var b=this.title,d=this.data.labels[a];return 1<f.total?b||d:this.parent.labelOrTitle(a)}};Tee.CustomBar.prototype=
new Tee.Series;Tee.CustomBar.prototype.parent=Tee.Series.prototype;Tee.CustomBar.constructor=Tee.CustomBar;Tee.Bar=function(c,b){Tee.CustomBar.call(this,c,b);this.calc=function(a,b){this.isStacked?this.calcStack(a,b,this.data.values[a]):this.parent.calc.call(this,a,b)};this.horizMargins=function(a){this.initOffsets();a.x=this._margin;a.y=this._margin};this.vertMargins=function(a){var b=this.marks,c=this.format.stroke,i=this.minYValue()<this.origin;b.visible&&"center"!==b.location&&(a.y=b.arrow.length+
b.format.textHeight("Wj")+b.margins.top+b.margins.bottom,c=b.format.stroke);""!=c.fill&&(a.y+=2*c.size+1);i&&(a.x=a.y)};this.maxXValue=function(){return"sideAll"==this.stacked?this.countAll()-1:this.parent.maxXValue.call(this)};this.minYValue=function(){var a=this.parent.minYValue.call(this);return this.useOrigin?Math.min(this.origin,a):a};this.maxYValue=function(){return this.stackMaxValue()};this.calcBarBounds=function(a,b,c,i){b.x=a.x+c.x;b.width=c.y;this._vertAxis.inverted?(b.y=i,b.height=a.y-
b.y):(b.y=a.y,b.height=i-a.y);0>b.height&&(b.y+=b.height,b.height=-b.height)}};Tee.Bar.prototype=new Tee.CustomBar;Tee.Bar.prototype.parent=Tee.CustomBar.prototype;Tee.HorizBar=function(c,b){Tee.CustomBar.call(this,c,b);this.yMandatory=!1;this.format.gradient.direction="rightleft";this.maxMarkWidth=function(){var a=0,b,c,i=this.marks,f=this.count(),g;if(i.visible){b=this.marks.format;b.font.prepare();for(c=0;c<f;c+=i.drawEvery)this.isNull(c)||(g=b.textWidth(this.markText(c)+"W"),g>a&&(a=g))}return a};
this.horizMargins=function(a){var b=this.marks,c=this.format.stroke,i=this.minXValue()<this.origin;b.visible&&"center"!==b.location&&(a.y=b.arrow.length+this.maxMarkWidth()+b.margins.left+b.margins.right,c=b.format.stroke);""!=c.fill&&(a.y+=2*c.size+1);i&&(a.x=a.y)};this.vertMargins=function(a){this.initOffsets();a.x+=this._margin;a.y+=this._margin};this.maxYValue=function(){return"sideAll"==this.stacked?this.countAll()-1:this.parent.maxXValue.call(this)};this.minYValue=function(){return"sideAll"==
this.stacked?0:this.parent.minXValue.call(this)};this.minXValue=function(){var a=this.parent.minYValue.call(this);return this.useOrigin?Math.min(this.origin,a):a};this.maxXValue=function(){return this.stackMaxValue()};this.calcBarBounds=function(a,b,c,i){b.y=a.y+c.x;b.height=c.y;this._horizAxis.inverted?(b.x=a.x,b.width=i-a.x):(b.x=i,b.width=a.x-b.x);0>b.width&&(b.x+=b.width,b.width=-b.width)}};Tee.HorizBar.prototype=new Tee.CustomBar;Tee.HorizBar.prototype.parent=Tee.CustomBar.prototype;Tee.CustomSeries=
function(c,b){Tee.Series.call(this,c,b);this.stacked="no";this.stairs=!1;this.hover.enabled=!0;this.isStack100=this.isStacked=this.hover.line=!1;this.smooth=0;this.pointer=new function(a){this.setChart=function(a){this.chart=a;this.format.setChart(a)};this.chart=a;a=this.format=new Tee.Format(a);a.shadow.visible=!1;a.fill="";a.gradient.colors=["white","white","white"];a.gradient.visible=!0;a.shadow.visible=!0;this.colorEach=this.visible=!1;this.style="rectangle";this.height=this.width=12;this.draw=
function(a,b,c,f){var g=this.chart.ctx;this.transform&&(g.save(),this.transform(a.x,a.y,b));var b=0.5*this.width,j=0.5*this.height;"rectangle"==this.style?c.rectangle(a.x-b,a.y-j,this.width,this.height):"ellipse"==this.style?c.ellipse(a.x,a.y,this.width,this.height):"triangle"==this.style?c.polygon([new s(a.x,a.y-j),new s(a.x-b,a.y+j),new s(a.x+b,a.y+j)]):"downtriangle"==this.style?c.polygon([new s(a.x,a.y+j),new s(a.x-b,a.y-j),new s(a.x+b,a.y-j)]):"diamond"==this.style?c.polygon([new s(a.x,a.y-j),
new s(a.x-b,a.y),new s(a.x,a.y+j),new s(a.x+b,a.y)]):(g.beginPath(),"cross"==this.style&&(g.moveTo(a.x-b,a.y),g.lineTo(a.x+b,a.y),g.moveTo(a.x,a.y-j),g.lineTo(a.x,a.y+j)),"x"==this.style&&(g.moveTo(a.x-b,a.y-j),g.lineTo(a.x+b,a.y+j),g.moveTo(a.x-b,a.y+j),g.lineTo(a.x+b,a.y-j)),c.stroke.prepare(f),g.stroke());this.transform&&g.restore()}}(this.chart);this.maxYValue=function(){return this.stackMaxValue()};this.calc=function(a,b){this.isStacked?this.calcStack(a,b,this.data.values[a]):Tee.Series.prototype.calc.call(this,
a,b)};this.calcColorEach=function(){this.isColorEach="yes"==this.colorEach||this.pointer.colorEach}};Tee.CustomSeries.prototype=new Tee.Series;Tee.CustomSeries.prototype.drawPointers=function(){var c=this.data.values.length,b,a=this.pointer.format,d="yes"==this.colorEach||this.pointer.colorEach;!d&&""==a.fill&&(a.fill=this.format.fill);var e=new s,i=a.gradient,f,g=a.fill;b=g;!d&&i.visible&&i.setEndColor(g);for(f=0;f<c;f++)this.isNull(f)||(this.calc(f,e),g=this.getFill(f,a),g!=b&&(i.visible?i.setEndColor(g):
a.fill=g,b=g),this.getSize(f),this.pointer.draw(e,f,a,g),this.hover.enabled&&this.over==f&&this.pointer.draw(e,f,this.hover,g));d&&(a.fill=b)};Tee.CustomSeries.prototype.setChart=function(c,b){var a=Tee.Series.prototype.setChart;a(c,b);c.pointer.setChart(b)};Tee.CustomSeries.prototype.clicked=function(c){var b=new s,a=new s,d=this.data.values.length,e;if(this.drawLine&&0<d&&(this.hover.line||!this.pointer.visible)){this.calc(0,b);for(e=1;e<d;e++){this.calc(e,a);if(M(c,b,a,3))return e;b.x=a.x;b.y=
a.y}}if(this.pointer.visible){b=new q;a=this.pointer;for(e=0;e<d;e++)if(!this.isNull(e)&&(this.calc(e,b),this.getSize(e),b.x-=0.5*a.width,b.width=a.width,b.y-=0.5*a.height,b.height=a.height,b.contains(c)))return e}return-1};Tee.CustomSeries.prototype.horizMargins=function(c){var b=this.pointer,a=b.format.stroke;b.visible&&(c.x=c.y=(""!=a.fill?a.size:0)+1+0.5*b.width)};Tee.CustomSeries.prototype.vertMargins=function(c){var b=this.pointer,a=b.format.stroke;b.visible&&(c.x=c.y=(""!=a.fill?a.size:0)+
1+0.5*b.height)};Tee.CustomSeries.prototype.getSize=function(){};Tee.Line=function(c,b){Tee.CustomSeries.call(this,c,b);this.drawLine=!0;var a=this.format;a.shadow.visible=!0;a.shadow.blur=10;a.lineCap="round";this.doDrawLine=function(b){var c=new s,i,f=this.data.values.length,g,j=0,h=f;g=this.notmandatory;!this.smooth&&!this.data.x&&(j=Math.max(0,(g.minimum|0)-1),h=Math.min(f,(g.maximum|0)+2));b.beginPath();if(0<this.smooth&&"undefined"!==typeof Tee.drawSpline){i=Array(2*f);for(g=0;g<f;g++)this.calc(g,
c),i[2*g]=c.x,i[2*g+1]=c.y;Tee.drawSpline(b,i,this.smooth,!0)}else for(g=j;g<h;g++)this.isNull(g)||(this.calc(g,c),g==j?b.moveTo(c.x,c.y):(this.stairs&&b.lineTo(i,c.y),b.lineTo(c.x,c.y)),i=c.x);f=a.stroke;this.chart.isChrome&&a.shadow.visible&&(f.size=Math.max(1.1,f.size));c=f.fill;f.prepare(""==c?a.fill:c);a.shadow.prepare(b);b.stroke()};this.draw=function(){0<this.data.values.length&&(this.isStacked="no"!=this.stacked,this.isStack100="100"==this.stacked,this.drawLine&&this.doDrawLine(this.chart.ctx),
this.pointer.visible&&this.drawPointers())}};Tee.Line.prototype=new Tee.CustomSeries;Tee.PointXY=function(c,b){Tee.Line.call(this,c,b);this.hover.enabled=!0;this.pointer.visible=!0;this.drawLine=!1};Tee.PointXY.prototype=new Tee.Line;Tee.Series.prototype.cellRect=function(c,b,a){var d={total:0,index:-1};c.setFrom(this.chart.chartRect);this.chart.series.visibleCount(this,a,d);if(b&&1<d.total){b=Math.round(Math.sqrt(d.total));a=Math.round(d.total/b);if(c.width>c.height)var e=b,b=a,a=e;c.width/=b;c.x+=
1.03*(d.index%b)*c.width;c.height/=a;c.y+=1.03*(d.index/b|0)*c.height;c.width*=0.94;c.height*=0.94}return c};Tee.Pie=function(c,b){function a(a,b){b.x=h.x+Math.cos(a)*j;b.y=h.y+Math.sin(a)*j}Tee.Series.call(this,c,b);this.marks.style="percent";this.rotation=this.donut=0;this.colorEach="yes";this.useAxes=!1;var d=this.format;d.stroke.fill="black";d.shadow.visible=!0;d.gradient.visible=!0;d.gradient.direction="radial";d.gradient.colors=["white","white","white"];this.hover.enabled=!0;this.sort="values";
this.orderAscending=!1;this.explode=null;this.marks.visible=!0;this.concentric=!1;this.getValue=function(a){return this.data.values[a]};this.calcCenter=function(a,b,d,c){if(this.explode&&(a=this.explode[a]))a=0.01*b*a,c.x+=a*Math.cos(d),c.y+=a*Math.sin(d)};this.clicked=function(a){var b=this.chart.ctx,d=this.data.values.length,c,e;r=k=Math.PI*this.rotation/180;for(c=0;c<d;c++)if(e=n?n[c]:c,!this.isNull(e)&&(this.slice(b,e),b.isPointInPath(a.x,a.y)))return e;return-1};var e,i,f,g,j,h={x:0,y:0},n,k,
r,p;this.slice=function(b,d){var c=new s;r+=2*Math.PI*(Math.abs(this.data.values[d])/e);h.x=i;h.y=f;this.calcCenter(d,g,0.5*(k+r),h);0==this.donut?(c.x=h.x,c.y=h.y):a(k,c);b.beginPath();b.moveTo(c.x,c.y);b.arc(h.x,h.y,g,k,r,!1);0!=this.donut&&a(r,c);b.lineTo(c.x,c.y);0!=this.donut&&b.arc(h.x,h.y,j,r,k,!0);b.closePath();d==this.over&&(p=k);k=r};this.fill=function(a){return this.getFillStyle(this.chart.chartRect,this.getFill(a))};this.slices=function(a){var b=this.chart.ctx,c=this.data.values.length,
e,f;r=k=Math.PI*this.rotation/180;for(e=0;e<c;e++)f=n?n[e]:e,this.isNull(f)||(this.slice(b,f),a?d.shadow.prepare(b):b.fillStyle=this.fill(f),b.fill(),a||(f=d.stroke,""!=f.fill&&(f.prepare(),b.stroke())))};var m=new q;this.draw=function(){if(0<this.data.values.length){var a=0,b=this.marks;d.shadow.visible&&(a+=2*d.shadow.height);b.visible&&(b.format.font.prepare(),a+=b.format.textHeight("Wj")+0.5*b.arrow.length);this.cellRect(m,!this.concentric,Tee.Pie);i=m.x+0.5*m.width;f=m.y+0.5*m.height;g=0.5*m.width;
a=0.5*(m.height-2*a);0>a&&(a=0);a<g&&(g=a);j=0.01*g*this.donut;for(var a=this.data.values,b=0,c=a.length;c--;)b+=0<a[c]?a[c]:-a[c];e=b;n=this.doSort(this.sort,this.orderAscending);this.slices(!0);this.slices(!1);this.hover.enabled&&-1!=this.over&&(a=this.hover,""!=a.stroke.fill&&(r=k=p,b=this.chart.ctx,this.slice(b,this.over),b.fillStyle=this.fill(this.over),a.draw(b,null,m.x,m.y,m.width,m.height)))}};this.drawMarks=function(){var a=k=Math.PI*this.rotation/180,b,d=this.data.values,c=d.length,j,m;
for(m=0;m<c;m+=this.marks.drawEvery)j=n?n[m]:m,this.isNull(j)||(a+=2*Math.PI*(d[j]/e),b=0.5*(k+a),h.x=i,h.y=f,this.calcCenter(m,g,b,h),this.marks.drawPolar(h,g,b,j),k=a)}};Tee.Pie.prototype=new Tee.Series;Tee.Area=function(c,b){Tee.CustomSeries.call(this,c,b);this.useOrigin=!1;this.origin=0;this.drawLine=!0;var a=this.format;a.shadow.visible=!0;a.lineCap="round";a.stroke.fill="black";a.fill="";var d=new q;this.draw=function(){var b=this.data.values.length;if(0<b){var c=this.mandatoryAxis,f=this.notmandatory,
g,j=this.yMandatory;g=this.useOrigin?c.calc(this.origin):j&&c.inverted||!j&&!c.inverted?c.startPos:c.endPos;this.isStacked="no"!=this.stacked;this.isStack100="100"==this.stacked;var h=new s,n,k,c=this.chart.ctx,r,p=this.isStacked,m=0,q=b;!this.smooth&&!this.data.x&&(m=Math.max(0,(f.minimum|0)-1),q=Math.min(b,(f.maximum|0)+2));c.beginPath();if(0<this.smooth&&"undefined"!==typeof Tee.drawSpline){r=Array(2*b);for(k=0;k<b;k++)this.calc(k,h),r[2*k]=h.x,r[2*k+1]=h.y;f=j?r[0]:r[1];Tee.drawSpline(c,r,this.smooth,
!0);if(p){var l=0;for(k=b-1;0<=k;k--)this.calcStack(k,h,0),r[l++]=h.x,r[l++]=h.y;c.lineTo(r[0],r[1]);Tee.drawSpline(c,r,this.smooth,!1)}}else if(this.calc(m,h),c.moveTo(h.x,h.y),f=j?h.x:h.y,n=j?h.y:h.x,this.stairs)for(k=m+1;k<q;k++)this.calc(k,h),c.lineTo(h.x,n),c.lineTo(h.x,h.y),n=j?h.y:h.x;else for(k=m+1;k<q;k++)this.calc(k,h),c.lineTo(h.x,h.y);if(p){if(0==this.smooth)for(k=q-1;k>=m;k--)this.calcStack(k,h,0),this.stairs?(c.lineTo(h.x,n),c.lineTo(h.x,h.y),n=j?h.y:h.x):c.lineTo(h.x,h.y)}else j?(c.lineTo(h.x,
g),c.lineTo(f,g)):(c.lineTo(g,h.y),c.lineTo(g,f));c.closePath();b=a.gradient;b.visible&&(b.colors[b.colors.length-1]=a.fill);this.bounds(d);a.draw(c,null,d.x,d.y,d.width,d.height);this.pointer.visible&&this.drawPointers()}};this.minYValue=function(){var a=this.yMandatory?Tee.Series.prototype.minYValue.call(this):Tee.Series.prototype.minXValue.call(this);return this.yMandatory?this.useOrigin?Math.min(a,this.origin):a:a};this.minXValue=function(){var a=this.yMandatory?Tee.Series.prototype.minXValue.call(this):
Tee.Series.prototype.minYValue.call(this);return this.yMandatory?a:this.useOrigin?Math.min(a,this.origin):a};this.maxYValue=function(){var a=this.yMandatory?this.stackMaxValue():Tee.Series.prototype.maxXValue.call(this);return this.yMandatory?this.useOrigin?Math.max(a,this.origin):a:a};this.maxXValue=function(){var a=this.yMandatory?Tee.Series.prototype.maxXValue.call(this):this.stackMaxValue();return this.yMandatory?a:this.useOrigin?Math.max(a,this.origin):a};this.vertMargins=function(b){this.yMandatory&&
""!==a.stroke.fill&&(b.y+=a.stroke.size+2)};this.horizMargins=function(b){!this.yMandatory&&""!==a.stroke.fill&&(b.y+=a.stroke.size+2)}};Tee.Area.prototype=new Tee.CustomSeries;Tee.HorizArea=function(c,b){Tee.Area.call(this,c,b);this.yMandatory=!1};Tee.HorizArea.prototype=new Tee.Area;Tee.Donut=function(c,b){Tee.Pie.call(this,c,b);this.donut=50};Tee.Donut.prototype=new Tee.Pie;Tee.Gantt=function(c,b){Tee.Series.call(this,c,b);this.yMandatory=!1;this.dateFormat="mediumDate";this.hover.enabled=!0;this.hover.round.x=
this.hover.round.y=8;this.colorEach="yes";this.data.start=this.data.values;this.data.x=[];this.data.end=[];this.height=70;this.margin=new s(6,6);var a=this.format;a.shadow.visible=!0;a.round.x=a.round.y=8;a.stroke.fill="black";a.gradient.visible=!0;var d=new q,e;this.addRandom=function(a){var b=this.data;b.x.length=a;b.start.length=a;b.end.length=a;if(0<a)for(var c,d,e=0;e<a;e++)b.x[e]=e,c=12*Math.random()|0,d=10*Math.random()|0,b.start[e]=new Date(2012,c,d),5>c&&(c=5+(7*Math.random()|0)),b.end[e]=
new Date(2012,c,d+10*Math.random())};this.bounds=function(a,b){if(this.isNull(a))return!1;this.calc(a,b);b.y-=0.5*e;b.width=this.data.end?this.mandatoryAxis.calcSize(this.data.end[a]-this.data.start[a]):0;b.height=e;return!0};this.add=function(a,b,c,d){var e=this.data;e.labels.push(b);e.x.push(a);e.start.push(c);e.end.push(d)};this.clicked=function(a){var b=this.data.values.length,c;for(c=0;c<b;c++)if(this.bounds(c,d)&&d.contains(a))return c;return-1};this.draw=function(){var b=this.data.values.length,
c,g;e=this.notmandatory.calcSize(0.01*this.height);for(c=0;c<b;c++)this.bounds(c,d)&&(g=this.hover.enabled&&this.over==c?this.hover:a,this.chart.ctx.fillStyle=this.getFillStyle(d,this.getFill(c,g)),g.rectangle(d))};this.horizMargins=function(a){a.x=this.margin.x;a.y=this.margin.y};this.minYValue=function(){return this.parent.minXValue.call(this)-0.5};this.maxYValue=function(){return this.parent.maxXValue.call(this)+0.5};this.minXValue=function(){return Math.min.apply({},this.data.start)};this.maxXValue=
function(){return Math.max.apply({},this.data.end)}};Tee.Gantt.prototype=new Tee.Series;Tee.Gantt.prototype.parent=Tee.Series.prototype;Tee.Bubble=function(c,b){Tee.PointXY.call(this,c,b);var a=this.pointer;a.colorEach=!0;a.style="ellipse";a.format.gradient.visible=!0;a.format.gradient.direction="radial";this.addRandom=function(a){var b=this.data;b.values.length=a;b.radius.length=a;if(0<a)for(var c=0;c<a;c++)b.values[c]=1E3*Math.random(),b.radius[c]=100*Math.random()}};Tee.Bubble.prototype=new Tee.PointXY;
Tee.Bubble.prototype.getSize=function(c){c=this.data.radius?this._vertAxis.calcSize(this.data.radius[c]):0;this.pointer.width=c;this.pointer.height=c};Tee.Bubble.prototype.horizMargins=function(c){this.calcWidth=function(b){this.getSize(b);var b=1+0.5*this.pointer.width,a=this.pointer.format.stroke;""!=a.fill&&(b+=a.size);return b};this.pointer.visible&&(c.x=this.calcWidth(0),c.y=this.calcWidth(this.count()-1))};Tee.Bubble.prototype.vertMargins=function(c){this.calcHeight=function(b){this.getSize(b);
var b=1+0.5*this.pointer.height,a=this.pointer.format.stroke;""!=a.fill&&(b+=a.size);return b};this.pointer.visible&&(c.x=this.calcHeight(0),c.y=this.calcHeight(this.count()-1))};Tee.Volume=function(c,b){Tee.Bar.call(this,c,b);this.barStyle="line";this.colorEach=this.marks.visible=!1;var a=this.format;a.shadow.visible=!1;a.gradient.visible=!1;a.stroke.fill=""};Tee.Volume.prototype=new Tee.Bar;Tee.Candle=function(c,b){Tee.PointXY.call(this,c,b);this.pointer.width=7;this.pointer.format.stroke.visible=
!1;this.higher=this.pointer.format;this.higher.fill="green";this.lower=new Tee.Format(this.chart);this.lower.fill="red";this.lower.stroke.visible=!1;this.style="candle";this.setChart=function(a,b){var c=Tee.PointXY.prototype.setChart;c(a,b);this.lower.setChart(b)};this.draw=function(){var a=this.data,b=a.values.length,c,i=new s,f=this.pointer,g=0.5*f.width,j,h,n,k=this.mandatoryAxis,r,q,m=this.chart.ctx,p,l;for(c=0;c<b;c++)if(!this.isNull(c)&&(this.calc(c,i),l=i.x,j=k.calc(a.open[c]),h=k.calc(a.high[c]),
n=k.calc(a.low[c]),i.y>j?(r=j,q=i.y-j,p=this.lower):(r=i.y,q=j-r,p=this.higher),"bar"==this.style?(m.beginPath(),m.moveTo(l,h),m.lineTo(l,n),m.moveTo(l-g,j),m.lineTo(l,j),m.moveTo(l,i.y),m.lineTo(l+g,i.y),p.stroke.prepare(p.fill),m.stroke()):this.hover.enabled&&this.over==c?this.hover.rectangle(l-g,r,f.width,q):p.rectangle(l-g,r,f.width,q),"openclose"!=this.style&&(h<r||n>r+q)))m.beginPath(),m.moveTo(l,r),m.lineTo(l,h),m.moveTo(l,r+q),m.lineTo(l,n),this.hover.enabled&&this.over==c?this.hover.stroke.prepare(p.fill):
p.stroke.prepare(p.fill),m.stroke()};this.minYValue=function(){return 0<this.data.low.length?Math.min.apply({},this.data.low):0};this.maxYValue=function(){return 0<this.data.high.length?Math.max.apply({},this.data.high):0};this.addRandom=function(a){var b=this.data;b.values.length=a;b.close=b.values;b.open?b.open.length=a:b.open=Array(a);b.high?b.high.length=a:b.high=Array(a);b.low?b.low.length=a:b.low=Array(a);if(0<a)for(var c=25+100*Math.random(),i,f=0;f<a;f++)i=b.open[f]=c,c=b.close[f]=c+25*Math.random()-
12.5,b.high[f]=Math.max(i,c)+15*Math.random(),b.low[f]=Math.min(i,c)-15*Math.random()}};Tee.Candle.prototype=new Tee.PointXY;Tee.Candle.prototype.clicked=function(c){var b=this.pointer.width,a=this.mandatoryAxis,d=this.notmandatory,e=this.data,i=e.values.length,f=new q,g,j,h;f.width=b;for(g=0;g<i;g++)if(!this.isNull(g)&&(f.x=d.calc(g)-0.5*b,j=a.calc(e.open[g]),h=a.calc(e.close[g]),f.y=j>h?h:j,f.height=Math.abs(j-h),f.contains(c)))return g;return-1};Tee.Candle.prototype.vertMargins=function(){};var D=
0,p,G,E="undefined"!==typeof document&&document.all?!0:!1;Tee.DOMTip={show:function(c,b){null==p&&(p=document.createElement("div"),p.setAttribute("id","teetip1"),p.className="teetip",p.setAttribute("style","padding:5px; margin-left:5px; background-color:#666; border-radius:4px 4px; color:#FFF;"),document.body.appendChild(p),p.style.opacity=0,E&&(p.style.filter="alpha(opacity=0)"));document.onmousemove=this.pos;p.style.display="block";p.style.position="absolute";p.innerHTML=c;p.style.width=b?b+"px":
"auto";!b&&E&&(p.style.width=p.offsetWidth);300<p.offsetWidth&&(p.style.width="300px");G=parseInt(p.offsetHeight)+3;p.timer&&clearInterval(p.timer);p.timer=setInterval(function(){Tee.DOMTip.fade(1)},10)},pos:function(c){var b=document.documentElement,a=E?event.clientY+b.scrollTop:c.pageY,c=E?event.clientX+b.scrollLeft:c.pageX;0>a-G&&(a=G);0>c&&(c=0);p.style.top=a-G+"px";p.style.left=c+3+"px"},fade:function(c){var b=D;if(97!=b&&1==c||0!=b&&-1==c){var a=10;10>97-b&&1==c?a=97-b:10>D&&-1==c&&(a=b);D=
b+a*c;p.style.opacity=0.01*D;E&&(p.style.filter="alpha(opacity="+D+")")}else clearInterval(p.timer),-1==c&&(p.style.display="none",document.onmousemove=null)},hide:function(){p&&(clearInterval(p.timer),p.timer=setInterval(function(){Tee.DOMTip.fade(-1)},10))}}}).call(this);
